- docs/openapi.yaml
- routes/resourcePages.js
https://github.com/isomerpages/isomercms-backend/issues/10
> Update docs for resources, resourcepages, and menus

- .gitignore
- classes/ImageFile.js
- routes/images.js
- server.js
This PR will allow one to retrieve/upload larger images using Git blobs. (#18)
The commit edac009 addresses the retrieving issue.
The commit 54a41a3 addresses the uploading issue.
> Retrieve and upload large images (>1mb)

- package.json
This PR adds a new npm command which sources the `.env` file before running the program for local development
> fix: add a npm command for local development

- .travis.yml
This PR sets up travis to deploy to our staging environment on AWS
> feat: setup deploy to staging

- package-lock.json
- package.json
This PR makes the repo commitizen-friendly so that we can use the `git cz` command line tool for commits.
For more information, refer to this page: https://github.com/commitizen/cz-cli#making-your-repo-commitizen-friendly
> [feat] make repo commitizen-friendly

- routes/auth.js
This PR adds functionality to send the username to the frontend for display when users successfully log in.
> feat: sends user id through redirect upon successful login

- middleware/auth.js
- routes/navigation.js
- server.js
This PR adds in endpoints related to retrieving and updating the navigation file. To be reviewed in conjunction with PR#[348](https://github.com/isomerpages/isomercms-frontend/pull/348) on the isomercms-frontend repo.
> Feat: add endpoints to retrieve navigation data

- classes/Collection.js
- classes/Config.js
- classes/ResourceRoom.js
- classes/Settings.js
- classes/Tree.js
- package-lock.json
- package.json
- routes/collectionPages.js
- routes/collections.js
- routes/navigation.js
- routes/pages.js
- utils/menu-utils.js
For more details, see PR #390 on the frontend: https://github.com/isomerpages/isomercms-frontend/pull/390
> fix: replace npm js-yaml library with npm yaml library

- classes/Collection.js
- classes/Config.js
- classes/ResourceRoom.js
- classes/Tree.js
- routes/collectionPages.js
- routes/collections.js
- routes/homepage.js
- routes/pages.js
- routes/resourcePages.js
- utils/menu-utils.js
Hotfix to master, see #163 for details.
> (hotfix to master) misc bugs

- classes/Collection.js
- classes/Config.js
- classes/ResourceRoom.js
- classes/Tree.js
- middleware/auth.js
- routes/auth.js
- routes/collectionPages.js
- routes/collections.js
- routes/homepage.js
- routes/pages.js
- routes/resourcePages.js
- utils/menu-utils.js
> Merge to production - 30 April 2021

- classes/MediaFile.js
- classes/MediaSubfolder.js
- routes/documents.js
- routes/images.js
This PR modifies the existing `MediaFile` and `MediaSubfolder` classse for document subfolder creation, deletion and renaming. It also updates the existing documents endpoints to use these classes. To be reviewed in conjunction with PR#[442](https://github.com/isomerpages/isomercms-frontend/pull/442) on the isomercms-frontend repo.
> Feat: add endpoints for file subfolders

- classes/Resource.js
- classes/ResourceRoom.js
- middleware/auth.js
- routes/documents.js
- routes/images.js
This PR releases the following changes:
- Fix/modify title in index file for resources (#179)
- fix/conflict in variable name (#181)
- Feat/moving media (#178)
This PR should be merged together with [/isomercms-frontend/484](https://github.com/isomerpages/isomercms-frontend/pull/484)
> Merge to production: 27 May 2021

- package-lock.json
This PR updates our packages using `npm audit fix` to resolve our current vulnerabilities.
> Chore: update dependencies

- classes/Collection.js
This PR fixes https://github.com/isomerpages/isomercms-frontend/issues/501.
When a user renames a collection in the Workspace, they should expect the corresponding navigation menu element to be updated. The curious thing was that our `Collection.rename` method already contained code to perform the nav update.
However, the issue was the sequence in which the code in the method was run. Here is a walkthrough of the existing buggy code:
- The rename method takes in several parameters, including `oldCollectionName`, `newCollectionName,` and `treeSha`. The `treeSha` is important since we use git trees to move files within the collection folder.
- Step 1 - we update the `navigation.yml` file by replacing `oldCollectionName` with `newCollectionName`
- Step 2 - we call the git trees API and …
> fix: update nav when renaming collection

- errors/ForbiddenError.js
- middleware/auth.js
- routes/auth.js
- utils/jwt-utils.js
To be reviewed with https://github.com/isomerpages/isomercms-frontend/pull/522
> fix: oauth flow

- .github/workflows/ci.yml
This PR reverts the change made to the `ci.yml` file to pause builds for the staging and dev environments.
> vapt: resume builds

- package-lock.json
This PR upgrades the repo's dependencies - it is done by running `npm audit fix`
> fix: upgrade dependencies

- package-lock.json
- package.json
- server.js
This PR adds helmet to help improve the security of the backend - described [here](https://github.com/helmetjs/helmet#how-it-works). This was a recommendation by Snyk.
> fix: add helmet for security

- .env-example
- middleware/auth.js
- package-lock.json
- package.json
- routes/auth.js
- utils/jwt-utils.js
Duplicate of #217, merging into develop. 
To be merged with [isomercms-frontend/pull/583](https://github.com/isomerpages/isomercms-frontend/pull/583), env variable `ENCRYPTION_SECRET` needs to be added.
> [develop] fix: update logout

- controllers/CollectionController.js
This PR removes unused imports from the Collection Controller
> style: remove unnecessary imports

- services/fileServices/YmlFileServices/CollectionYmlService.js
Code now obtains the index of first file in collection/subcollection using `_.findIndex`
> style: update comment

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
guide us to write more comprehensive issues
> Introduce standard issue templates

- .ebextensions/nginx-max-body-size.config
Merging the hotfix branch back to develop: https://github.com/isomerpages/isomercms-backend/pull/286
> fix(hotfix-develop): update ebextension

- .github/workflows/ci.yml
Update CI/CD user to use more restricted permissions
> fix(hotfix-master): update cicd user

- .github/workflows/ci.yml
Update cicd user with more restricted permissions.
> fix(hotfix-develop): update cicd user

- .ebextensions/nginx-max-body-size.config
- .github/workflows/ci.yml
- .platform/nginx/conf.d/proxy.conf
- package.json
This PR is the hotfix to develop for https://github.com/isomerpages/isomercms-backend/pull/296
> hotfix (develop): migrate to platform hooks

- classes/Collection.js
- classes/File.js
- classes/MediaFile.js
- classes/MediaSubfolder.js
- classes/Resource.js
- classes/ResourceRoom.js
- routes/folders.js
- services/db/GitHubService.js
- utils/utils.js
This PR contains the following changes:
**Bug fixes:**
- Handle 409 errors properly when updating/deleting pages (https://github.com/isomerpages/isomercms-backend/pull/303)
- Change format of git tree update requests to better handle large repos and prevent 502 errors (https://github.com/isomerpages/isomercms-backend/pull/305)
> Merge to prod: 23 Sept 2021

- .eslintrc.json
- jsconfig.json
- middleware/auth.js
- newroutes/__tests__/ResourceCategories.spec.js
- newroutes/__tests__/ResourcePages.spec.js
- newroutes/__tests__/ResourceRoom.spec.js
- newroutes/__tests__/Settings.spec.js
- newroutes/resourceCategories.js
- newroutes/resourcePages.js
- newroutes/resourceRoom.js
- package.json
- server.js
- services/configServices/__tests__/SettingsService.spec.js
- services/directoryServices/BaseDirectoryService.js
- services/directoryServices/ResourceDirectoryService.js
- services/directoryServices/ResourceRoomDirectoryService.js
- services/directoryServices/__tests__/ResourceDirectoryService.spec.js
- services/directoryServices/__tests__/ResourceRoomDirectoryService.spec.js
- services/fileServices/MdPageServices/ResourcePageService.js
- services/fileServices/MdPageServices/__tests__/HomepagePageService.spec.js
- services/fileServices/MdPageServices/__tests__/ResourcePageService.spec.js
- services/fileServices/YmlFileServices/__tests__/ConfigYmlService.spec.js
- services/fileServices/YmlFileServices/__tests__/FooterYmlService.spec.js
- services/fileServices/YmlFileServices/__tests__/NavYmlService.spec.js
- validators/RequestSchema.js
- validators/validators.js
This PR rolls out the following changes:
- Refactored resource room flow
Summary of commits
- https://github.com/isomerpages/isomercms-backend/pull/318
> Merge to prod: 2 December 2021 

- .github/pull_request_template.md
duplicate of FE PR [here](https://github.com/isomerpages/isomercms-frontend/pull/740). adding on BE also
> chore(pr template): adds a pull request template

- package-lock.json
- package.json
This PR adds auto-changelog and its corresponding npm script - npm version - to automatically version our releases.
> chore: add auto-changelog

- middleware/apiLogger.js
- middleware/auth.js
- newroutes/users.ts
- package-lock.json
- package.json
- routes/sites.js
- services/identity/UsersService.ts
- types/error.ts
- types/index.ts
- types/request.ts
See #367 for details on conversion to TS. This is a further extension on that by converting the top level router to typescript too and partially addressing #379.
1. Add types to `newroutes/users`
2. refactor so that we set property on `res.locals` instead of `req`. 
- `type-fest` : package for utility types!
> feat(identity): add types to user router

- .github/workflows/ci.yml
- package.json
see [here](https://github.com/isomerpages/isomercms-frontend/pull/742) for a short write-up on this. 
Closes #129
add tests to existing workflow. 
**note**
this should be merged after #382 as that has an updated `npm run test` command and the associated test env file
> build(ci): add ci

- database/models/User.ts
This PR removes the duplicates validation in the database email column. More more information on this issue, please refer to the appropriate issue.
Closes https://github.com/isomerpages/isomercms-backend/issues/396
> Chore: remove duplicate validation in User model

- src/services/directoryServices/ResourceDirectoryService.js
- src/services/fileServices/MdPageServices/ResourcePageService.js
- src/validators/RequestSchema.js
This PR adds an additional allowable layout type for resource pages. To be reviewed in conjunction with PR #[1064](https://github.com/isomerpages/isomercms-frontend/pull/1064) on the isomercms-frontend repo and PR #[276](https://github.com/isomerpages/isomerpages-template/pull/276) on the isomerpages-template repo.
> Feat: add link as resource page layout type

- src/constants/constants.ts
- src/routes/v2/authenticated/__tests__/collaborators.spec.ts
- src/routes/v2/authenticated/collaborators.ts
- src/services/identity/CollaboratorsService.ts
- src/services/identity/__tests__/CollaboratorsService.spec.ts
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> feat(ut): collaborator stats

- package.json
- src/database/migrations/20221003052424-review-request-creation.js
- src/database/migrations/20221003123422-review-meta-creation.js
- src/database/migrations/20221003130006-reviewer-creation.js
- src/database/migrations/20221007124138-create-review-status.js
- src/routes/v2/auth.js
- src/services/infra/InfraService.ts
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> feat(ut): db migration for rr

- src/database/models/ReviewMeta.ts
- src/database/models/Reviewers.ts
- src/errors/RequestNotFoundError.ts
- src/routes/v2/authenticated/collaborators.ts
- src/routes/v2/authenticated/index.js
- src/routes/v2/authenticated/review.ts
- src/server.js
- src/services/configServices/SettingsService.js
- src/services/db/GitHubService.js
- src/services/db/review.ts
- src/services/identity/CollaboratorsService.ts
- src/services/identity/UsersService.ts
- src/services/review/ReviewRequestService.ts
- src/tests/database.ts
- src/types/dto /error.ts
- src/types/dto /review.ts
- src/types/error.ts
- src/types/github.ts
- src/types/request.ts
- src/types/review.ts
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> feat(ut): rr services

- src/routes/v2/authenticated/review.ts
- src/services/review/ReviewRequestService.ts
See [#1117](https://github.com/isomerpages/isomercms-frontend/issues/1117)
Part of [#1117](https://github.com/isomerpages/isomercms-frontend/issues/1117)
1. add route + handler for unapproval of RR
- squats on `/approve` because this is a deletion of a property
> feat(rr): adds be for unapproval of rr

- src/fixtures/notifications.ts
- src/integration/Notifications.spec.ts
- src/middleware/notificationOnEditHandler.ts
- src/middleware/routeHandler.js
- src/routes/v2/authenticated/__tests__/Notifications.spec.ts
- src/routes/v2/authenticated/index.js
- src/routes/v2/authenticated/notifications.ts
- src/routes/v2/authenticated/review.ts
- src/routes/v2/authenticatedSites/__tests__/Notifications.spec.ts
- src/routes/v2/authenticatedSites/collectionPages.js
- src/routes/v2/authenticatedSites/collections.js
- src/routes/v2/authenticatedSites/contactUs.js
- src/routes/v2/authenticatedSites/homepage.js
- src/routes/v2/authenticatedSites/index.js
- src/routes/v2/authenticatedSites/mediaCategories.js
- src/routes/v2/authenticatedSites/mediaFiles.js
- src/routes/v2/authenticatedSites/navigation.js
- src/routes/v2/authenticatedSites/resourceCategories.js
- src/routes/v2/authenticatedSites/resourcePages.js
- src/routes/v2/authenticatedSites/resourceRoom.js
- src/routes/v2/authenticatedSites/settings.js
- src/routes/v2/authenticatedSites/unlinkedPages.js
- src/server.js
- src/services/identity/NotificationsService.ts
- src/services/identity/__tests__/NotificationsService.spec.ts
- src/utils/notification-utils.ts
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> feat(ut): generic notification creation

- src/routes/v2/authenticated/review.ts
refer [here](https://doc-00-8c-apps-viewer.googleusercontent.com/viewer/secure/pdf/e610cr6c4ma63adcdml4pogbnchl4eae/pegui353t42ckorecf921v6bgvp0156e/1670832900000/drive/16427479467258399849/ACFrOgAkiayUn0t3ypt7dlwyzz7JUQFez3W45VKjnMMYiep4RMNtf9rqvPHeAxS9jaeEkgMDzk_kVr3N767fMolgZ3D1aQ353wDhXmM_rou6oHdeFEs3MIqSgCoMJ-P1GrpaKS0PpA_-LuVXMP47?print=true&nonce=u95t25r8ob148&user=16427479467258399849&hash=hptq0q9qhj4cs9vbo1tlcelb5o40ck6q) (actual report) or [here](https://www.notion.so/opengov/VAPT-Remediation-c604c62d822e4023be266c5a293d3a1e) (brief summary), under "Broken access control"; not giving details due to security 
1. check when updating reviewers to ensure that hte user isn't trying to add themselves as a reviewer
2. check when approving PRs that the user isn't the reviewer and that …
> fix(review): remove self-approval bypass

- src/services/directoryServices/__tests__/ResourceRoomDirectoryService.spec.js
This PR fixes the tests which were failing due to #611 .
> Fix: resource room tests

- .github/workflows/ci.yml
Ubuntu 18.04 is [sunsetting](https://github.com/actions/runner-images/issues/6002)
> chore(github runners): update ubuntu versioning

- microservices/package-lock.json
- microservices/package.json
- package-lock.json
- package.json
This PR updates the following packages to resolve our snyk vulnerabilities:
- is-svg
- @aws-sdk/client-amplify
- @aws-sdk/client-cloudwatch-logs
- @aws-sdk/client-secrets-manager
> Chore: update packages

- package-lock.json
This PR runs npm audit fix on our repo to fix some existing outdated packages.
> Chore: run npm audit fix

- src/classes/Settings.js
- src/routes/v1/authenticatedSites/homepage.js
- src/services/fileServices/MdPageServices/HomepagePageService.js
- src/services/fileServices/MdPageServices/__tests__/HomepagePageService.spec.js
Old constant was being imported as `HOMEPAGE_NAME` and not `HOMEPAGE_FILENAME`
Fixed import
> fix(constants): fixed import

- src/services/infra/InfraService.ts
> chore(Infra Service): fix failing build

- src/services/api/AxiosInstance.ts
This PR adds logging to our axios interceptor to assist with debugging our Github API call usage.
> chore: add logging to endpoints being called

- src/services/review/ReviewRequestService.ts
Close pull request was using the sitename from Sites instead of Repos. This PR fixes the issue
> fix: close pull request

- src/fixtures/markdown-fixtures.ts
- src/fixtures/yaml-fixtures.ts
- src/services/db/GitHubService.js
- src/services/db/__tests__/GitHubService.spec.ts
Github service behaviour was recently changed. The tests did not have good coverage of the added functionality.
Add new edge cases
> tests(github service): add github service tests

- microservices/site-launch/lambda-functions/general-domain-validation/index.ts
- microservices/site-launch/lambda-functions/primary-domain-validation/index.ts
- microservices/site-launch/lambda-functions/redirection-domain-validation/index.ts
- microservices/site-launch/lambda-functions/step-functions-trigger/index.ts
- microservices/site-launch/lambda-functions/success-notification/index.ts
- microservices/site-launch/shared/types.ts
- src/services/identity/QueueService.ts
- src/services/infra/DynamoDBClient.ts
- src/services/infra/DynamoDBService.ts
- src/services/infra/InfraService.ts
Modify enums to be more meaningful
> feat(site launch enums): more meaningful naming

- src/routes/v1/auth.js
the log method wasn't capturing the email
get email from `req.session.userInfo`
> fix(auth.js): log user email properly

- src/config/config.ts
We used to do a try catch to prevent breaking prod. 
Now that we are confident that this works, we should remove the `try,catch` block to make full use of convict.
- Details ...
Doing a simple string search shows that we have had no errors in one week, and since we deployed last Thursday, we can deduce that all env vars that should be in prod + staging are in. 
Just make sure that `FF_DEPRECATE_SITE_QUEUES` and `STEP_FUNCTIONS_ARN` env var exists in staging and prod envs respectively. (supposed to go in as part of release process on 22 June 2023, this PR is written before that process has ended)
> chore(config): change to strict mode

- .env.test
- src/services/infra/__tests__/DynamoDBService.spec.ts
cicd tests failed 
add env vars to `.env.test` to fix the issue
Now, all tests pass:
> fix(cicd): fix cicd tests

- src/errors/IsomerError.ts
- src/errors/SiteLaunchError.ts
- src/services/infra/InfraService.ts
some how the commits werent added, no clue why
some [commits](https://github.com/isomerpages/isomercms-backend/commit/198e2a257522b08f6296a7c4bd21a135e67ed325) dieappeared from this [pr](https://github.com/isomerpages/isomercms-backend/pull/818#event-9726886403) 
recommit changes
> fix(site launch routes): removed commits

- src/constants/constants.ts
- src/routes/formsgSiteLaunch.ts
- src/services/infra/InfraService.ts
[todo]: double cfm with shaz about this behaviour first
SL failure emails currently sent to admin, 
send to support instead
> fix(sl): email adr

- src/classes/UserWithSiteSessionData.ts
- src/config/config.ts
- src/fixtures/sessionData.ts
- src/middleware/authentication.ts
- src/middleware/featureFlag.ts
- src/middleware/index.ts
- src/middleware/routeHandler.js
- src/services/db/RepoService.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/types/express/request.d.ts
- src/types/featureFlags.ts
- src/types/request.ts
- src/utils/growthbook-utils.ts
We need to have context of user attributes for us to do targeted rollouts/experiments.
Closes IS-312
We inject information at both the authentication and authorization middlewares based on what we know about the user at that point in time.
Note: To be reviewed in conjunction with IS-310 which introduces GrowthBook for BE.
- Details ...
> IS-312: Inject User Data into GrowthBook for Segmentation

- src/routes/formsgSiteCreation.ts
Got extra endpoint leading to potential conflicts
remove extra endpoint
> fix(clonesite): remove extra endpoint

- src/services/identity/__tests__/CollaboratorsService.spec.ts
Fixes tests due to changed behaviour of add collaborators.
> Fix: collaborators service tests

- src/services/identity/SitesService.ts
Currently, the feature flag for quickie only allows/prevents commits to staging + staging-lite branches in Github. 
Enabling quickie for a site required a manual step to change the staging-urls directly in the db. Any rollback prior to this also required a manual intervention to go into the DB to mutate the staging-url manually. This is not scalable to both roll out + quickly rollback when a bug is found.
To keep this feature in line with what we typically expect to work with other feature flags, this PR 
1. produces the correct staging url when it has enough information to do so 
2. Updates our DB value with the correct value based on the dynamic boolean value of whether the feature flag is turned on for that repo
- Details ...
> feat(quickie): correct staging url

- src/services/db/GitFileSystemService.ts
some images got .JPG instead of .jpg, end up not rendering in the UI. 
change the check to lower case instead + better logging for ease of debugging
> fix(file ext): fix casing + better logging

- src/services/fileServices/MdPageServices/MediaFileService.js
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> fix(mediafileservice): disable sneky cloudmersive

- src/constants/featureFlags.ts
- src/services/fileServices/MdPageServices/MediaFileService.js
- src/types/featureFlags.ts
- src/utils/file-upload-utils.js
- src/utils/growthbook-utils.ts
cm giving us issues. Increase time out, else eng should be able to turn it off to reduce biz impact
> fix(cm): extra timeout

- src/middleware/routeHandler.ts
- src/routes/v2/authenticatedSites/homepage.js
- src/services/db/GitFileSystemService.ts
- src/utils/neverthrow.ts
Fix multiple issues with rollback, locking, logging and other errors
> IS-802 bugs with rollback

- .github/workflows/ci.yml
- package.json
CI tests were failing as `docker compose up` is timing out despite working fine on local
don't use docker compose, just pass a command directly
> fix(ci): update commands

- .dockerignore
- Dockerfile.develop
- scripts/02_fetch_ssh_keys.sh
Previously we were including the ssh parameters at build time. now, we change it so that it is injected via env vars at run time. 
- fetch via env vars and output to file
```
- ENV_TYPE=DEV
- DEV_SSH_PUBLIC_KEY=<take_from_your_own_ssh_config>
- DEV_SSH_PRIVATE_KEY=<take_from_your_own_ssh_config>
```
> feat(dockerfile): migrate fetching keys to script too

- Dockerfile.develop
- scripts/03_add_keys_to_ssh_config.sh
for some weird reason dev didnt work for me @seaerchin is my witness 
should be semantically similar in code
> fix(dockerfile):use script instead

- .github/workflows/deploy_staging.yml
old role was wrong
update to new role
> fix(workflow): update role

- .github/workflows/deploy_staging.yml
`ecs-container-name` needs to be same as `task-def`
change to fit
> fix(deploy-staging): update workflow

- README.md
- scripts/02_fetch_ssh_keys.sh
This PR fixes issues with ssh key population on local dev. Note that this solution is strictly for dev currently - it still does not work for staging/prod, and will need to be modified further to support this.
> fix: fetch ssh keys on dev

- src/routes/v2/authenticated/collaborators.ts
Right now no logging for changes in site members table. 
add logging
> feat(logging): adding logging

- src/services/utilServices/Sanitizer.ts
copy paste to backend for fe code [here](https://github.com/isomerpages/isomercms-frontend/pull/1809)
> fix(dompurify): further limit src

- package.json
Fixes local dev build command.
> fix: dev script

- .aws/deploy/backend-task-definition.prod.json
- .aws/deploy/backend-task-definition.staging.json
see frontend PR [here](https://github.com/isomerpages/isomercms-frontend/pull/1822)
change tags on SSM for eb
change tags on task def for ecs
> fix(task-def): update task definitions for env vars for dd tags

- src/routes/formsg/formsgSiteAuditLogs.ts
The question phrasing was updated on FormSG but not on our backend.
**Bug Fixes**:
- Updated the form question to get the requestor's email to "Which email address should we send the logs to?"
Same as #1181.
*None*
> chore(audit): update form question phrasing

- src/services/review/RepoCheckerService.ts
might accidently trigger alarms
> fix(site checker): dont trigger alarms

- package-lock.json
> chore(dep): add flag

- .aws/deploy/backend-task-definition.prod.json
duplicate of #1279 - raising as separate so we can double check: the env vars should be a 1:1 mapping from `staging -> prod` 
raise PR for `prod` -> do help to double check!
> feat(task def): update env

- support/routes/v2/formsg/formsgGGsRepair.ts
#1313 introduces git force pushes. While this is ok from the user point of view, this impedes with operations since now ops will need to ask eng to lock the repo first, then edit it on github, then unlock the repo, then submit the repair form (since the repair form also attempts to acquire the lock)
There are 3 modes for the repair form now. 
- Lock only
- Repair without lock  
- Repair with lock
Repair with lock is what the repair form used to do. This is now not the recommended flow for editing sites. The recommended flow to edit the sites manually should be 
1. submit lock only repair form
2. make edits 
3. submit form to repair without lock
Intentionally leaving the option to continue to repair without lock in case there is any lingering divergence bet staging and staging lite. …
> feat(repair): add locking functionailty

- .github/mergify.yml
update snyk title cos previously the regex matched `[Snyk]]` not `[Snyk]` 
update regex to remove terminating `]`
> fix(snyk): update title

- src/services/identity/ReposService.ts
Issues on public repositories have been recently used to distribute malware which look like they're from official sources.
Discussion on Slack (internal) : https://opengovproducts.slack.com/archives/C055FUACLJU/p1714113816195799
For the teams consideration to disable issues for repos on new Isomer sites, though it is still possible to upload files using Pull Requests 😔
> feat: disable issues on new repositories

- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/services/api/AxiosInstance.ts
- src/services/identity/SmsClient.ts
We need to upgrade axios to 1.8.3.
Reference: https://opengovproducts.slack.com/archives/CK9GGK6EP/p1741763549869339
**Features**:
- Upgrade axios to 1.8.3.
> fix: upgrade axios to 1.8.3
