- routes/auth.js
Currently, users get redirected to ${BACKEND_URL}/sites after authenticating with GitHub instead of the frontend. This PR redirects users to ${FRONTEND_URL}/sites instead.
Redoing #3
> change redirect URL to frontend instead of backend

- classes/File.js
This PR changes the format of `folderName` to accommodate the fact that the `index.md` (homepage) file is located in the root of the folder.
Without this change, the `endpoint` for `index.md` will be `https://api.github.com/repos/${GITHUB_ORG_NAME}/${this.siteName}/contents/index.md/`. However, the endpoint is not valid because of the trailing `/`.
This change ensures that the endpoint is `https://api.github.com/repos/${GITHUB_ORG_NAME}/${this.siteName}/contents/index.md` instead, which is a valid endpoint.
> fix base endpoint for homepage

- docs/openapi.yaml
- routes/resources.js
This PR returns `resourceRoomName` in the GET `/resources` endpoint so that the frontend does not need to also call GET `/resource-room` to obtain the field.
> Return resourceRoomName in GET /resources API

- routes/sites.js
Use the `style-sites` branch on the frontend
The `Sites` page is supposed to show the Isomer websites the login user has access to. To do that, we first find the list of repositories ascribed to the user, and filter that list for Isomer websites.
However, currently, the sites endpoint returns only the first page of results when hitting the Github V3 API endpoint `https://api.github.com/user/repos`. As the maximum number of results returned per API call is 100, this means that for users with more than 100 repos, we might not be getting all Isomer repositories associated with that user. 
This can happen in the following example. If the user has 150 repos, and the first 50 repos are non-Isomer repos and the last 100 repos are Isomer repos, then with our current implementation, we get the …
> [sites] Fix sites endpoint

- classes/Directory.js
- classes/File.js
- classes/Tree.js
- routes/menuDirectory.js
- server.js
- utils/menu-utils.js
- utils/utils.js
This pull request adds a new endpoint, `/:siteName/tree`, which returns data that is used to construct the tree for the drag and drop navigation menu in the frontend. In the context of this PR, the word **unlinked** means "not present in the main navigation bar" of the webpage.
The drag and drop navigation menu consists of two sections:
- **Navigation**, which consists of elements in the main navigation bar at the top of the webpage 
- **Unlinked**, which consists of all unlinked pages, collections, or resource room.
To obtain data for **Navigation**, we pull data from the `_data/navigation.yml` file in the site's repository and manipulate it to fit the requirements of the drag and drop tree builder in the front end.
To obtain data for **Unlinked**, we query the Github API to get the full …
> Feat: add endpoint for drag and drop navigation menu

- routes/pages.js
This PR now shows all collection pages, along with the existing simple pages on the `GET pages` endpoint.
Initially only simple pages were shown in the `GET pages` endpoint. The team decided that collection pages would be included as well as we were scraping the 'Collections' tab in the frontend.
This pull request needs to be merged into `master` along with the frontend [PR](https://github.com/isomerpages/isomercms-frontend/pull/64) or else the frontend will break.
> BREAKING CHANGE: Include collection pages in the `GET pages` endpoint

- routes/pages.js
In cases where collection pages are defined wrongly in the `_config.yml` page (for example, a collection title is spelt wrongly'), the `collectionPages` variable in `pages.js` will be an empty object `{}` and cause an error because we later use `collectionPages.map()`. This PR introduces a fix by return the accumulator if `collectionPages` is an empty object.
> fix: make code resilient to invalid collections defined in _config.yml

- classes/Tree.js
This PR adds a case for false collections in the navigation bar which act like collections do (with a dropdown on hover) but are not actual collections in the repository. This PR works with [PR#86](https://github.com/isomerpages/isomercms-frontend/pull/86) in `isomercms-frontend`
> feat: add support for false collections

- routes/sites.js
This PR will restrict the repositories the user sees on the `Sites` page to the repositories that belong to the teams they are on.
Currently, all users receive access to all repositories when they log into IsomerCMS. This is not the intended behavior - we want to show users only the repositories they have write access to.
The way we retrieve repositories right now is to simply list all the repositories a user is associated with through Github's `user/repos` endpoint and filter for `isomerpages` organization repositories.
~Instead, we can use the `user/teams` [endpoint](https://developer.github.com/v3/teams/#list-user-teams) to retrieve all teams that the user is a part of, and then use the `teams/:team_id/repos` [endpoint](https://developer.github.com/v3/teams/#list-team-repos) to …
> [Fix - Sites] Display correct sites for users

- .travis.yml
This PR updates the Travis CI config file to deploy the IsomerCMS backend to the new AWS Elastic Beanstalk environments.
> ci: update eb env and app names

- routes/sites.js
This removes the unnecessary `vnd.github.baptiste-preview` header used in the Github Repos API call.
> fix: remove unnecessary header

- .travis.yml
Reverts isomerpages/isomercms-backend#34 since this commit does not exist in master and causes merge conflicts.
> Revert "feat: setup deploy to staging"

- classes/Config.js
- classes/Directory.js
- classes/File.js
- classes/ImageFile.js
- routes/sites.js
- utils/axios-utils.js
This PR fixes the bug where axios throws an error if the response status is 404 despite having a `validateStatus` param. The error is still thrown because `validateStatus` should exist as a field outside of `params` - this fix moves `validateStatus` out of the `params` field.
> fix: use validateStatus correctly

- classes/Config.js
- classes/File.js
- classes/Settings.js
- package-lock.json
- package.json
- routes/settings.js
- server.js
This PR is to be reviewed with PR#[99](https://github.com/isomerpages/isomercms-frontend/pull/99) in the frontend.
This PR introduces the `settings` route and `Settings` class which will retrieve the relevant settings information to be rendered in the frontend. The type of settings data falls into two classes:
- general config and colors (retrieved from `_config.yml`)
- social media pages (retrieved from `_data/social-media.yml`)
> [Feat] Create settings route and class

- classes/Settings.js
This PR returns the site `url` field from `config.yml` in the `GET /settings` endpoint.
> feat: return site url in Settings endpoint

- classes/File.js
This PR will read documents in using the Git Data's API instead of the Contents API as documents may be larger than 1MB and the Contents API does not support that.
> fix: use blobs to retrieve documents larger than 1MB

- classes/Settings.js
**Note:** This PR is to be reviewed together with PR #[155](https://github.com/isomerpages/isomercms-frontend/pull/155) on the frontend.
Currently, we are reading and writing social media data from the `_data/social-media.yml` file and creating one of these files if they do not exist. However, this is wrong - we don't actually use a `social-media.yml` file in the Isomer V2 templates. Instead this information is found in the `_data/footer.yml` file. This commit fixes that by retrieving information from and writing to the `_data/footer.yml` file instead. The updated code sends all footer content to as a response.
This commit also modifies the Settings class so that when retrieving the settings information, the api calls for both the config and footer files are made concurrently using the …
> feat: use footer.yml instead of social-media.yml

- routes/auth.js
This PR fixes the bug identified in issue #57. Currently, the frontend attempts to call a non-existent endpoint to log the user out. This PR adds in an endpoint to handle the user log out by clearing the existing cookie. To be reviewed with PR #[154](https://github.com/isomerpages/isomercms-frontend/pull/154) on the isomercms-frontend repo.
> Fix: add logout endpoint

- classes/Collection.js
- middleware/auth.js
Currently, when faced with a repo which does not have any collections, our `Collection` class' `list` method throws an error since it tries to use `Object.keys` on the non-existent `collection` attribute.
This commit fixes that by only performing the operation if the `collections` attribute exists on the config object, otherwise an empty array is returned. This allows us to accommodate repositories without any collections. This PR resolves issue #61
> fix: allow collections to be empty in _config.yml

- .github/workflows/ci.yml
Currently, we get the following error when we attempt to deploy to AWS EB with certain commit messages:
```
Deployment failed: Error: Status: 403. Code: SignatureDoesNotMatch,
Message: The request signature we calculated does not match the
signature you provided. Check your AWS Secret Access Key and signing
method. Consult the service documentation for details.
```
This is not because our access key is wrong, but because there are certain characters in our commit message which are not dealt with properly by the beanstalk-deploy package. We know that the following characters have produced problems for us:
```
(    )    '
```
These are due to encoding [issues](https://github.com/einaregilsson/beanstalk-deploy/issues/28#issuecomment-721159380) on the original beanstalk-deploy library.
Rather …
> feat: truncate and remove chars from version desc. before deploy

- routes/auth.js
On the staging version of the cms (`staging-cms.isomer.gov.sg`, which hits our staging backend server `staging-cms-api.isomer.gov.sg`), the frontend is sending the same cookie twice in the cookie header
(in bold) which is causing the API call to fail because the backend can't read the cookie properly
cookie: <other cookies>... **isomercms**=[redacted]; isomercms=[redacted]
I've set up an online dev environment mimicking the setup, `staging-dev-cms.isomer.gov.sg` and `staging-dev-cms-api.isomer.gov.sg`, and deployed the exact same code to them both, and set all configurations to be the same and the cookie sends properly (appears only once), so i'm not sure what the problem is the problem appears to be with the backend,
because i swapped the backends so that `staging-cms.isomer.gov.sg` …
> chore: remove cookie domain

- middleware/auth.js
- routes/pages.js
This PR adds a new endpoint which returns only unlinked pages, that is, pages in the `pages` folder of the repo instead of all
pages in the repo. This is to accommodate our move to a file system hierarchy structure in the frontend.
> feat: add endpoint for unlinked pages

- classes/Collection.js
- routes/collectionPages.js
This PR resolves https://github.com/isomerpages/isomercms-backend/issues/72. It accomplishes 2 things:
- First, when creating new collectionPages, it automatically generates a new collection and updates the config file
- Second, when deleting collectionPages, it checks if the collection is now empty and removes the collection from the config file if so
> Feat: update config for collections on adding and deleting pages

- classes/File.js
- errors/ConflictError.js
- errors/InputValidationError.js
This PR introduces a new error for handling the case where we fail to create a new file due to conflicting file names. This PR is to be reviewed in conjunction with PR #[247](https://github.com/isomerpages/isomercms-frontend/pull/247) on the isomercms-frontend repo.
One thing to note is that we convert the error thrown by the Github API when processing - this is due to the endpoint that we are calling to create a new file also being used to modify existing files, thus the Github API returns us a `422 Unprocessable Entity` error due to the missing sha, when we actually want to reflect that there is a conflict in file names.
> Feat: add new InputNameConflictError

- middleware/errorHandler.js
This PR logs the serialized error with a distinct string, "Unrecognized internal server error" so that we can create a CloudWatch metric filter based on this string to identify and trigger alerts on unrecognized / non-Isomer errors
> chore: log error message with distinct string for metric filter

- classes/File.js
This PR allows ConflictError to be thrown if a 409 error is received from the Github API. To be reviewed with PR [#247]https://github.com/isomerpages/isomercms-frontend/pull/247 on the isomercms-frontend repo.
> Feat: throw ConflictError if 409 received

- classes/Settings.js
This PR modifies the `post` update method on the `Settings` class to update each component (`footerSettings`, `configSettings`) separately, only if the relevant component is defined in the received payload.
This is because on the Edit Contact-Us page ([link](https://github.com/isomerpages/isomercms-frontend/pull/260)), we only update a key-value pair stored in `footerSettings`, so there is no need to store and resend `configSettings` on the `post` update. 
The implementation is a currently rough implementation for the frontend PR, and will be cleaned up, see (frontend TODOs list [link](https://github.com/isomerpages/isomercms-frontend/pull/260))
> fix: update config settings and footer settings separately

- classes/File.js
This PR fixes the behaviour for throwing NotFoundErrors in File. Previously, it was not possible to reach the condition to throw the NotFoundError in read, as a file which could not be retrieved would have have a defined endpoint. This resulted in a different error being thrown. This PR fixes that and also adds in the check during deleting and updating files.
To be reviewed in conjunction with PR [#280](https://github.com/isomerpages/isomercms-frontend/pull/280) on the isomercms-frontend repo.
> Fix: throw NotFoundError for files

- middleware/auth.js
- routes/sites.js
This PR adds a new endpoint to check if users have access to a given site. To be reviewed in conjunction with PR[#280](https://github.com/isomerpages/isomercms-frontend/pull/280) on the isomercms-frontend repo.
To check if a user has access to a site, we check if the user is one of the collaborators on that repo, and throw an error message if either the site does not exist or the user does not have the appropriate permissions. We have opted to throw the same 404 error in both of these cases.
> Feat: add endpoint to check if user has access to site

- routes/sites.js
This PR addresses issue #83 
Previously, site retrieval was slow because the GitHub API for retrieving org repos was paginated, and we retrieved the data sequentially, one page at a time. This meant that it often took up to 7 or even 8 seconds each time this endpoint is accessed (each page took around 3 seconds, perhaps due to the large amount of data being sent).
Since we know the number of repos our `isomerpages` GitHub organization has, we can use this information to speed up our endpoint by making concurrent calls instead of stepping through the API pagination. This PR improves performance by making concurrent API calls to retrieve repo info so that it now only takes around 3 seconds for the endpoint to respond, more than halving the amount of time take previously.
This commit also …
> feat: improve `/sites` endpoint performance

- classes/Settings.js
**Note:** This PR is to be reviewed with PR #[286](https://github.com/isomerpages/isomercms-frontend/pull/286) on the frontend.
The `Settings` class deals with three different types of configuration files: `_config.yml`, `_data/footer.yml`, and `_data/navigation.yml`. Originally, we would write to all three files, even if the only fields that were changed involved only one of the files.
For example, even if I had only changed the `title` field (which affects only the `_config.yml` file), I would end up making API calls to update the remaining two settings files with their original content. With this PR, I would only update the `_config.yml` file and not the other two files.
By only making changes that need to be made, we can increase the speed of response by only updating a file if it …
> feat: only update Settings file if field has changed

- docs/openapi.yaml
- middleware/auth.js
- server.js
This PR adds a `/v1` prefix to all URI paths to version our API. This will be useful for several reasons:
- allows us to gracefully accommodate a v2 api which uses github's graphql API
- allows us to craft tight firewall rules (currently, we search for whether a
URI path contains `/sites` or `/auth`, which would allow nonsense URI paths like
`/authors`)
**Note**: things which we need to do before we merge the PR:
- ~Change the `REDIRECT_URI` env var on backend to include `/v1`~ (if the `REDIRECT_URI` is unspecified it will use the callback URL from the GitHub app)
- Update the `REACT_APP_BACKEND_URL` env var on frontend to include `/v1`
- Update the callback URL for the staging app (and eventually the production app) to include `/v1`
> chore: add `/v1` to all URI paths

- classes/File.js
This PR fixes a bug where certain File types would not throw the proper error if they failed to be read. Certain specified File types have a default `folderName`, which `read` attempts to read from initially, however, this would result in an empty object if the appropriate directory did not exist. An additional check has been added to ensure that the directory exists, and to throw a NotFoundError if it does not.
> Fix: add check for files in directory when reading file

- .ebextensions/nginx-max-body-size.config
- .github/workflows/ci.yml
- classes/Collection.js
- classes/File.js
- classes/Resource.js
- classes/ResourceRoom.js
- classes/Settings.js
- docs/openapi.yaml
- errors/ConflictError.js
- middleware/auth.js
- middleware/errorHandler.js
- middleware/routeHandler.js
- package-lock.json
- package.json
- routes/collectionPages.js
- routes/collections.js
- routes/pages.js
- routes/resourcePages.js
- routes/resourceRoom.js
- routes/resources.js
- routes/settings.js
- routes/sites.js
- server.js
- utils/utils.js
This release to production contains the following changes:
- Renaming of directories with multiple files (#88)
- Increase nginx client max body size so that images up to 5mb can be uploaded (#101)
- Adding new custom errors and applying them to application code (404, 409) (#78, #84, #87)
- Add custom string in error handler so that we can filter for unknown errors on AWS CloudWatch (#82)
- Automatically update navigation file when new collection/resource category is created (#80)
- Add new fields to `Settings` class (#85)
- Endpoint for checking whether user has push access to repo (#89)
- Improve `/sites` route loading time (#90)
- Improve `Settings` class `post` method load time (#81, #92)
> Merge to Prod

- routes/auth.js
GitHub has deprecated the use of authentication via URL query params, but there is still one part of the codebase where we do that - when we retrieve user details via the following endpoint: `https://api.github.com/user`
This was the email from GitHub:
```
On February 2nd, 2021 at 07:50 (UTC) your application (IsomerCMS Local Dev) used its `client_id` and `client_secret` (with the User-Agent axios/0.19.0) as part of a set of query parameters to access an endpoint through the GitHub API:
https://api.github.com/user
Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
```
This commit fixes that by removing the unnecessary query params that we currently attach to the request object.
> fix: prevent sending of client id/secret when using Github APIs

- classes/Directory.js
- middleware/auth.js
- routes/folders.js
This PR is a duplicate of #117 since there was a rebasing error in that PR and staging was reset to the last working commit.
> Duplicate of #117

- middleware/routeHandler.js
@gweiying pointed out a bug in the transaction lock feature as well as a fix for it.
The bug was that a successful API call that used the rollback route handler did not unlock the repo because the handler was missing an `await unlock()` call after success.
> fix: unlock site after successful API call for rollback route handler

- classes/Directory.js
This PR fixes a minor bug in the `Directory` class' `list` method. When the path that we attempt to read from in the GET `/:siteName/files/:path` endpoint does not actually exist on GitHub, we currently throw a `400` error. Instead, we should be re-throwing the `404` error that GitHub responds with.
> fix: throw NotFoundError if given path cannot be found on GitHub

- classes/File.js
- routes/collectionPages.js
- routes/pages.js
This PR is to be reviewed together with PR #[379](https://github.com/isomerpages/isomercms-frontend/pull/379) on the isomercms-frontend repo. It accomplishes several things:
- It fixes an existing issue when attempting to read nested files. The previous endpoint being used required the requested file to be in the first level of the folder provided. Instead we now attempt to retrieve the file and throw a NotFoundError if we receive a 404 status.
- It also changes the existing page and collectionPage endpoints for updating pages to receive unencoded content, and handle the encoding here in the backend rather than the frontend.
- The collectionPage endpoints have also been updated to expect an encodedURIComponent for the pageName, to account for subfolder pages.
> Feat: read from nested files and update page endpoints for nested files

- classes/Config.js
PR #134 missed out on instances which attempted to destructure `contentObject` from the `read` method of the `CollectionConfig`, when we've actually changed the method to return `content` attribute. This PR fixes that.
> fix/CollectionConfig `read` method output

- classes/Subfolder.js
- routes/collectionPages.js
- routes/collections.js
- routes/pages.js
- routes/resourcePages.js
This PR adds functionality for adding empty subfolders into the CMS, as well as the associated changes required. To be reviewed in conjunction with PR #[384](https://github.com/isomerpages/isomercms-frontend/pull/384) on the isomercms frontend repo. A discussion of the reasoning behind this change can be found [here](https://docs.google.com/document/d/1EccpS_ATrfOe4DmU4ChXtU9kV6Jl1rFOdKqBLyG6ym8/edit#).
This PR introduces the following changes:
- The automatic deletion of empty folders, subfolders, and resources has been removed, in line with the ability to create empty folders.
- A new Subfolder class has been created for easier creation and management of subfolders, to automatically update the collection.yml file and handle placeholder file creation.
- An additional check for the …
> Feat: create placeholder for empty subfolders

- classes/Config.js
This PR fixes a small bug when adding files to the order in `collection.yml`. Previously, as the variable `index` was not scoped properly, we always spliced newly created files into the first position in the `collection.yml` file. We have fixed the scoping in this PR.
> Fix: position of newly created files

- .env-example
- classes/NetlifyToml.js
This PR updates the retrieval of the netlify.toml file to be taken from our central isomer-build repo, to resolve https://github.com/isomerpages/isomercms-backend/issues/143.
To do before merging: ~~update new env vars on AWS on both staging and prod~~
> Feat: retrieve netlify.toml from isomer build

- middleware/auth.js
- routes/sites.js
This PR adds in 2 new endpoints, to retrieve the url of the staging site and the last updated time of the repo. To be reviewed in conjunction with PR #[394](https://github.com/isomerpages/isomercms-frontend/pull/394) on the isomercms-frontend.
We are adding an additional last updated endpoint as the existing one being used (`getSites`) retrieves the details of every single repo.
For the endpoint being used to retrieve the staging url, we currently retrieve this using the repo description, as the staging url is automatically populated upon creation of a site. However, we intend to replace this, as it is possible for users to modify the initial description. We can consider adding the staging/production urls into the `_config.yml` file, or in the long term, adding these details to a dynamodb …
> Feat: add staging url and last updated endpoints

- routes/auth.js
This PR fixes our retrieval of the github access token, in line with github's deprecation of auth through query params ([link](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/)). We instead specify the username and password in a separate auth object.
> Fix: move auth out of query param

- routes/folders.js
This PR updates the get all folder content endpoint to only retrieve information from folders which contain a `collection.yml` file, while other folders are ignored.
> Fix: retrieve folders with collection.yml only

- routes/homepage.js
This PR changes the homepage endpoints to handle encoding/decoding, instead of performing this in the frontend, in line with our changes in https://github.com/isomerpages/isomercms-backend/pull/133. To be reviewed in conjunction with PR [#406](https://github.com/isomerpages/isomercms-frontend/pull/406) on the isomercms-frontend repo.
> Fix: encode/decode homepage content

- routes/resourcePages.js
This PR sends the `resourceRoomName` as part of the API response when a resource page is retrieved.
> fix: add resourceRoomName to readResourcePage response

- classes/Collection.js
- classes/Config.js
- classes/ResourceRoom.js
- classes/Tree.js
- routes/collectionPages.js
- routes/collections.js
- routes/homepage.js
- routes/pages.js
- routes/resourcePages.js
- utils/menu-utils.js
This PR changes the library used for encoding on the backend, standardising it on the `Base64` library. The other library used, `base-64` does not support encoding foreign language, hence users were experiencing difficulty saving resource files containing foreign language characters, as they were being encoded with `base-64`. 
Error message on backend logs:
Separately, this PR also fixes a bug where page content is not added to files moved to/ out of subfolders, which causes pages to appear blank after moving out of/ to a subfolder.
> (hotfix to develop) misc bugs

- middleware/auth.js
- routes/auth.js
This PR should be reviewed in conjunction with its [frontend PR](https://github.com/isomerpages/isomercms-frontend/pull/431). 
This PR adds an `/auth/whoami` endpoint that verifies the user's oauth token with GitHub and provides the CMS frontend with the `userId`.
> feat: add whoami endpoint

- routes/directory.js
Currently, if a repo has no images and files folder, a 404 is thrown and the frontend is redirected. This PR catches the 404 and sends an empty directoryContent response to the frontend.
> fix: handles media folders not found error

- routes/sites.js
Allow front end to access isPrivate property of repo when calling sites/
Facilitate checking of whether raw image urls in public repos can be used instead of retrieving blob from backend
> Fix/Return isPrivate property of repos in sites/route

- classes/Settings.js
This PR fixes an issue with the saving of empty fields. Currently, our template checks for the existence of fields in order to determine whether a certain part should be rendered, e.g. it checks for the existence of `feedback` to determine whether to render the feedback blurb inside contact-us. However, we are currently saving these fields as an empty string, which is interpreted as a valid link by our template. This PR fixes this by removing the relevant fields in the `footer.yml` file completely if they are updated to an empty string. 
Also, this PR additionally returns the value of the linkedin-insights for the settings endpoint.
To be reviewed in conjunction with PR#[496](https://github.com/isomerpages/isomercms-frontend/pull/496) on the isomercms frontend repo. Resolves …
> Fix: remove empty footer settings

- .eslintrc.json
This PR replaces the `plugin:prettier-recommended` with the original `prettier` plugin. 
This is because our config does not work with `plugin:prettier-recommended`. As explained in #127, our linting process is split into two: first we lint for code bugs with eslint, and then we fix code formatting issues with prettier. This works through `eslint-config-prettier` and `eslint-plugin-prettier`, which switches off the eslint rules related to code formatting, reserving them for prettier to fix.
The desired behavior when we run `npx eslint --fix .` is that all linting bugs are fixed, but formatting issues are ignored. However, we discovered that when we ran `npx eslint --fix .` with the `prettier-recommended` plugin, formatting issues were beign corrected as well. This is easily fixed by using …
> style: use `prettier` plugin instead of `prettier-recommended`

- jsconfig.json
This PR adds path aliases to the jsconfig.json so that VS Code can understand our aliases and help us to autocomplete them.
> style: add require path aliases to vscode

- routes/directory.js
This is a temporary fix for #196, wrapping the `IsomerDirectory.list()` method in a try-catch to prevent a 404 error from bubbling up when the directory does not exist. 
This should be fixed in the upcoming refactor in one of the following ways:
1) `IsomerDirectory.list()` should either return an empty array when it does not exist
2) The frontend should not expect to receive an empty array if the directory does not exist
> fix: address bug in directory route

- routes/folders.js
This PR fixes https://github.com/isomerpages/isomercms-backend/issues/185.
The current `renameSubfolder` route method does the following:
- Rename all files from `${folder}/${previousSubfolder}/${fileName}` to `${folder}/${newSubfolder}/${fileName}` using git trees
- Modify the `collection.yml` file within the collection folder
However, this neglects to modify the `third_nav_title` fields within the collection subfolder files.
This PR fixes the abovementioned problem by taking the following approach:
- For each file in the `${folder}/${previousSubfolder}` folder
- Create the new content for each file by modifying the `third_nav_title` field in each retrieved file
- Save the new content in the new `${folder}/${newSubfolder}` folder
- Modify the `collection.yml` file within the collection …
> fix: modify third nav title when renaming subfolder

- routes/auth.js
Previously, our cookies weren't expiring and were set as sessions because we used a string instead of an integer. This PR fixes that.
> fix: cookie expiry date

- .github/workflows/ci.yml
This PR comments out the .github/workflow `ci.yml`'s instructions to build changes pushed to the staging branch.
This PR will be reverted at the end of VAPT.
> vapt: pausing staging builds

- .github/workflows/ci.yml
This reverts commit 75ea6492d250cb9413bac6a1f6354a5e9afff571. This PR is a duplicate of #218, which was rested as I erroneously made a merge commit instead of a squash and merge.
> Revert "vapt: pausing staging builds"

- classes/NetlifyToml.js
This PR fixes a bug where the netlify.toml file could not be found on our build repo, after the changes to the location of the build file.
> Fix: update path to netlify.toml

- validators/RequestSchema.js
This PR fixes an issue with our existing schema for frontmatter - as we did not specify that unknown keys were allowed, existing pages which had additional parameters (e.g. breadcrumb) could not be modified. This PR fixes this issue by loosening our constraints on the frontmatter accepted.
> (hotfix to master) loosen request schema

- newroutes/__tests__/UnlinkedPages.spec.js
- newroutes/unlinkedPages.js
- server.js
- services/fileServices/MdPageServices/UnlinkedPageService.js
- services/fileServices/MdPageServices/__tests__/UnlinkedPageService.spec.js
This PR refactors the unlinked pages flow. 
It adds two main files and their tests:
- unlinked pages router
- unlinked pages service
The router contains the following endpoints:
- POST `/sites/:siteName/pages` - create unlinked page
- GET `/sites/:siteName/pages/:pageName` - read unlinked page
- POST `/sites/:siteName/pages/:pageName` - update or rename unlinked page
- DELETE `/sites/:siteName/pages/:pageName` - delete unlinked page
The service instance contains the following methods:
- create
- read
- update
- rename
- delete
The list method will be added in a subsequent PR because we will create a new UnlinkedDirectory service class for that.
> refactor: unlinked pages

- .env-example
- README
- middleware/auth.js
Add the following env vars for local testing:
```
export E2E_TEST_REPO="e2e-test-repo"
export E2E_TEST_SECRET="blahblahblah" // this should match the value of CYPRESS_COOKIE_VALUE on 
// the frontend
export E2E_TEST_GH_TOKEN="" // this can be your own personal GH access token, or  the token from our 
// specialized E2E test user
```
Refer to PR #[600](https://github.com/isomerpages/isomercms-frontend/pull/600) on the backend for more details. 
This PR adds an alternative authentication scheme on the backend server by verifying a secret passed by the E2E frontend test user. This scheme also checks for the scope of the request to be the `e2e-test-repo` and a few whitelisted pages (`Sites`, `whoami`). If passed, the backend server attaches the `E2E_TEST_GH_TOKEN` to the request, and makes …
> test: e2e authentication scheme

- .ebextensions/nginx-max-body-size.config
Deployments to AWS EB fail with the following error: 
`Command failed on instance. Return code: 7 Output: command 00_reload_nginx in .ebextensions/nginx-max-body-size.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.`
We found a Stackoverflow recommendation that fixes the issue and tested it on the CMS staging environment:
https://stackoverflow.com/questions/40766708/issue-with-aws-beanstalk-command/48203336#48203336 
We removed the unnecessary `service nginx reload` command and the deploy succeeded on staging.
> fix(hotfix-master): update ebextension

- .github/workflows/ci.yml
This PR does the following:
- rename the EB staging environment to the new `cms-backend-staging`
- remove all references to the develop branch since we no longer deploy develop code
> ci: update backend staging eb env

- .github/workflows/ci.yml
This PR changes the EB production environment name to the new `cms-backend-prod` env.
This PR is to be merged into the `hotfix/migrate-to-platform-hooks` branch, and then subsequently into master and develop.
> ci: update production eb env name

- .ebextensions/nginx-max-body-size.config
- .github/workflows/ci.yml
- .platform/nginx/conf.d/proxy.conf
- package.json
We discovered that the staging CMS backend EB environment was unable to receive payloads of >1 MB - this led us to realize that there was an issue with the nginx `client_max_body_size  10M;` configuration in the `.ebextensions/nginx-max-body-size.conf` file.
We suspected that this happened because the Amazon Linux 2 platform uses platform hooks for nginx-specific configurations.
This PR does the following:
- migrates the existing .ebextensions nginx configuration to use .platform hooks instead
- adds the `engines` field in the package.json file - was seeing the error `Instance deployment: You didn't specify a Node.js version in the 'package.json' file in your source bundle. The deployment didn't install a specific Node.js version.` …
> hotfix (master): migrate to platform hooks

- classes/Settings.js
This PR adds functionality to allow the editing of the description field in both the `config.yml` file as well as the homepage. To be reviewed in conjunction with PR [#613](https://github.com/isomerpages/isomercms-frontend/pull/613) on the isomercms frontend repo.
> Feat: add ability to edit description in settings

- utils/markdown-utils.js
This PR fixes an issue where having `---` in the page body would truncate the contents when viewed on the CMS. This was due to our reliance on this string to denote the location of the frontmatter. This PR modifies the check for frontmatter to only search for the first 2 occurrences of this, to prevent this behaviour.
> Fix: prevent truncating of page body

- classes/File.js
- classes/MediaFile.js
- services/db/GitHubService.js
This PR fixes a bug where we were not handling 409 errors when sending update requests to Github. When users attempt to modify a page with an outdated sha, a 409 error is received, which we previously did not anticipate. This PR fixes this by correctly catching and throwing an appropriate error.
> Fix: handle 409 errors when editing files

- classes/Collection.js
- classes/MediaSubfolder.js
- classes/Resource.js
- classes/ResourceRoom.js
- routes/folders.js
- utils/utils.js
This PR fixes an issue with git trees being too large for sites with a large number of files. Previously, when we wanted to use git trees to delete/rename directories, we would send the information of every file in the repo as a git tree - this resulted in 502 errors as github was unable to parse such a large amount of files. 
Recently, github has updated their API to allow for specifying that files are deleted via leaving the sha of the target files as `null` (see [link](https://developer.github.com/enterprise/2.17/v3/git/trees/#create-a-tree)). This method is much more space efficient, as the number of files deleted is significantly less than the total number of files in a repo.
We hypothesise that this PR will resolve our issues with unrecognised 502 errors.
> Fix: change git tree object format

- newroutes/__tests__/ResourceCategories.spec.js
- newroutes/__tests__/ResourcePages.spec.js
- services/directoryServices/__tests__/BaseDirectoryService.spec.js
- services/directoryServices/__tests__/ResourceDirectoryService.spec.js
- services/fileServices/MdPageServices/__tests__/ResourcePageService.spec.js
This PR adds tests for resources and resource categories. In addition, the tests for `BaseDirectoryService` have been extended to include one for file movement.
> Feat: add resources tests

- fixtures/config.js
- fixtures/footer.js
- fixtures/homepage.js
- fixtures/navigation.js
- middleware/auth.js
- newroutes/__tests__/Settings.spec.js
- newroutes/settings.js
- server.js
- services/configServices/SettingsService.js
- services/configServices/__tests__/SettingsService.spec.js
- services/fileServices/MdPageServices/HomepagePageService.js
- services/fileServices/MdPageServices/__tests__/CollectionPageService.spec.js
- services/fileServices/MdPageServices/__tests__/HomepagePageService.spec.js
- services/fileServices/MdPageServices/__tests__/SubcollectionPageService.spec.js
- services/fileServices/MdPageServices/__tests__/UnlinkedPageService.spec.js
- services/fileServices/YmlFileServices/ConfigYmlService.js
- services/fileServices/YmlFileServices/FooterYmlService.js
- services/fileServices/YmlFileServices/__tests__/CollectionYmlService.spec.js
- services/fileServices/YmlFileServices/__tests__/ConfigYmlService.spec.js
- services/fileServices/YmlFileServices/__tests__/FooterYmlService.spec.js
- services/fileServices/YmlFileServices/__tests__/NavYmlService.spec.js
- validators/RequestSchema.js
**Note: this PR contains a BREAKING CHANGE.**
This PR continues our efforts to refactor the CMS as specified by this design document ([link](https://docs.google.com/document/d/1664ww4X5PIy0mi5qB_q9JIWQaJ0qiLVIuV1v993Dlas/edit)). In this PR, I refactor the existing endpoints for reading and updating our repo settings:
- GET `/{siteName}/settings` - read settings
- POST `/{siteName}/settings` - update settings
The main change is the introduction of the new `SettingsRouter` class. The `SettingsRouter` uses the new `SettingsService` class which contains the bulk of the implementation logic, and uses the newly-created `ConfigYmlService`, `FooterYmlService`, `NavYmlService`, and `HomepagePageService` to simplify the retrieval and updating of settings data from different source files. There is …
> refactor: settings v2 (BREAKING CHANGE)

- classes/Resource.js
- routes/resourcePages.js
This PR also fixes the following bug:
- Empty resource category handling
- Due to PR Fix/unhandled errors for list directory and read media #310, some existing functionality for handling empty resource categories broke, as non-existent folders now throw an error, rather than return an empty array, as empty resource categories do not have a placeholder file in _posts where files are stored.
- We now correctly return an empty array for this scenario.
> fix: handle empty resource categories in v1

- services/configServices/SettingsService.js
This PR fixes a bug introduced in https://github.com/isomerpages/isomercms-backend/pull/282. In the process of our refactor for the settings flow, we reintroduced a bug in which footer settings which had been deleted (indicated via an empty string for the field sent by the frontend) were being stored as the empty string - this caused an issue with the appearance of icons and links on the footer to empty pages, as our template only checks for the existence of the field before rendering the appropriate icon/link. This PR adds additional checks to remove the appropriate fields in the footer if the user has deleted them.
> Fix: remove footer links if empty

- services/configServices/SettingsService.js
This PR fixes a bug in which users who changed the shareicon of their site would not have it reflected for the homepage.
Newly created sites start off with a default image used by the homepage which shows up for social media previews - this is stored as the `image` field in the `index.md` files in newly created repos. The repo would draw from this field when determining the image preview for the site, in the absence of a `shareicon` field in the `_config.yml` file. 
In one of our recent PRs, we introduced the ability to modify the `shareicon` of a site, which would override the image specified in the index file for all files which did not themselves specify an image. However, there was no way to modify the image in the original `index.md`, and it would have a higher priority than the …
> fix: update image for homepage if shareicon changes

- README
- package.json
Replicating https://github.com/isomerpages/isomercms-frontend/pull/808 on the backend
> Fix: prepend unique prefix for release script

- newmiddleware/auth.js
This PR fixes a bug introduced in #328 - due to the injection of middleware directly into each router, when querying the `req.url`, we now only receive the truncated version of the url that the router processes, i.e. `/v1/auth/whoami` in the `/v1/auth` router would now only return `/whoami` instead of `/v1/auth/whoami` as its `req.url`. The solution is to use `req.originalUrl` instead to preserve the original state of the url.
> Fix: use originalUrl instead of url

- server.js
Our auth refactor made the health check endpoint (`/v2/ping`) inaccessible as it was placed after the unknown route check - this PR fixes the issue by rearranging their order.
> fix: order of ping

- __mocks__/@aws-sdk/client-secrets-manager.ts
- __mocks__/axios.ts
- __mocks__/otplib.ts
- jest.config.js
- package-lock.json
- package.json
- services/identity/MailClient.ts
- services/identity/SmsClient.ts
- services/identity/TokenStore.ts
- services/identity/TotpGenerator.ts
- services/identity/__tests__/AuthService.spec.ts
- services/identity/__tests__/MailClient.spec.ts
- services/identity/__tests__/SmsClient.spec.ts
- services/identity/__tests__/TokenStore.spec.ts
- services/identity/__tests__/TotpGenerator.spec.ts
- services/identity/__tests__/constants.ts
- tsconfig.json
This PR adds unit tests for the services that were migrated to TS in #367.  
1. Add unit tests
2. modules which we have an explicit dependency on had mocks created so that we could mock return values and ensure that the calls were being made with correct arguments (see [here](https://jestjs.io/docs/manual-mocks) for more details on module mocking)
- `jest-mock-axios` : This package is used for an automatic mock of `axios`.
> feat(identity): unit tests for services

- .github/mergify.yml
duplicate of [this](https://github.com/isomerpages/isomercms-frontend/pull/745)
> chore(build): add mergify workflow

- services/directoryServices/ResourceDirectoryService.js
- services/directoryServices/__tests__/ResourceDirectoryService.spec.js
This PR fixes a bug in the resource category renaming - the breadcrumb of renamed resource categories were not being modified correctly due to the `index.html` file not being modified correctly. The reason for this issue was that our directory level operations use a snapshot of the existing state when making operations - this means that any modification to individual files before a directory level operation gets overwritten.
This PR rearranges the order to fix this issue.
> Fix: rearrange order of file and directory operations

- .sequelizerc
Our .sequelizerc file was not specifying the correct config path - this PR fixes the issue.
> Fix: modify sequelizerc file to use config.js

- services/identity/MailClient.ts
This PR fixes the reply email for OTP - previously, it was being sent to a private email rather than an official isomer email. partially fixes https://github.com/isomerpages/isomercms-frontend/issues/826
> Fix: set reply_to param for OTP email

- server.js
This PR fixes an issue where our env health on elastic beanstalk was showing as degraded - this was because the `/v2/ping` endpoint was being routed through the `authticatedRouter`, which expected an appropriate jwt token. This PR reshuffles the order to allow this endpoint to work without a valid jwt token.
Partial fix for https://github.com/isomerpages/isomercms-frontend/issues/826
> Fix: ping endpoint order

- README
This PR adds instructions to run database migrations on a remote RDS database in a private subnet of either the staging or production VPC.
> docs: add instructions to run DB migrations on remote DB

- services/identity/__tests__/MailClient.spec.ts
This PR fixes a minor bug in the mail client tests, where we were not checking for the `reply_to` parameter.
> Fix: mail client test

- .github/workflows/ci.yml
- jest.config.js
- tests/closeConnection.ts
Previously, our ci configuration was not working due to a few issues. These are respectively: 
1. requiring docker containers to be setup prior to running tests (for integration testing) 
2. `source` command not existing in github runner shell
3. jest not automatically exiting
In order, the fixes are as follows: 
1. run `npm run dev:services` command
2. change `source` to `.` 
3. This is more interesting and more detail will be provided - i think this [issue](https://github.com/sequelize/sequelize/issues/6758) covers it up pretty well and i adopted their solution. Basically all the tests pass but jest wasn't exiting and resulted in an indefinite wait. This problem is due to sequelize having a connection pool and the teardown script doesn't close all the connections, merely _one_ …
> test(ci): update ci config

- services/identity/MailClient.ts
- services/identity/__tests__/MailClient.spec.ts
- services/identity/index.ts
see #395 for an associated write-up on the problem. 
Closes #395
1. pass the api key explicitly in the constructor \
> refactor(mailclient): pass api key explicitly

- services/middlewareServices/AuthMiddlewareService.js
This PR addresses an issue with our identification of expired tokens - previously, we were expecting a `TokenExpiredError` for expired tokens, however, we were receiving an abnormal number of unhandled server errors. The reason for this is that we also set an expiry for the cookie the token is attached to - this means that after the token/cookie expires, the token we attempt to decrypt is empty, which results in a `JsonWebTokenError` instead. As users getting logged out due to expiring tokens is an expected error, this PR handles this error in the same way, in order to reduce the number of alerts we receive on our monitoring channels.
> Fix: check for JsonWebTokenError

- global.d.ts
- jest.config.js
- package-lock.json
- package.json
- services/directoryServices/__tests__/ResourceDirectoryService.spec.js
- tsconfig.json
See #400 for a brief description of the issue.
Closes #400
1. add `jest-extended`
2. check that directory level calls occur before file level reads
- `jest-extended` : package to extend `jest` and add more matchers
> test(resourceDirectory): add check for directory/file call order

- .github/mergify.yml
somehow dependabot PRs on FE differ from BE. This prevented mergify from working well; this fixes the rule to account for the differences
1. lowercase b for dependabot rule ._.
> chore(mergify): change dependabot rule to lowercase

- package-lock.json
- package.json
The newest version allows me to import env vars from .env.test on the command line by setting one env var `DOTENV_CONFIG_PATH=.env.test` and passing jest the command line argument `--require dotenv/config`
> chore: Upgraded dotenv to enable running tests in WebStorm.

- src/services/identity/ReposService.ts
This PR removes the site staging and prod links from the description on site creation - we were receiving feedback from schools that the github repo description was being indexed by google, which they were not comfortable with. The links are still accessible via the `_config.yml`, so we can still access them if necessary.
> Chore: remove site links from description

- src/services/directoryServices/ResourceRoomDirectoryService.js
This PR fixes an issue in our update resource room endpoint - as our index.html update was being done before our tree level operation, this was overridden by the tree level renaming operation (which uses a snapshot of the git tree retrieved at the start of the endpoint call), which caused the index.html title to not be updated. This PR rearranges the order to fix this issue. To be reviewed in conjunction with PR #[988](https://github.com/isomerpages/isomercms-frontend/pull/988) on the isomercms-frontend repo.
> Fix: update resource room

- src/services/identity/ReposService.ts
This PR fixes an issue introduced by https://github.com/isomerpages/isomercms-backend/pull/482 - we had previously removed the description in the repo update step as we believed it was not necessary - however, this caused issues with the site creation form, as we were attempting to call update on the repo with nothing to update. This PR removes the extra step to prevent this bug from occurring.
> fix: remove unnecessary update step

- src/fixtures/config.js
- src/services/configServices/SettingsService.js
- src/validators/RequestSchema.js
Closes #454.
**Bug Fixes**:
- The `resources_name` parameter has been removed from the response when calling GET `/v2/sites/:siteName/settings`, as it is an extra parameter and can cause issues on the frontend.
- The `url` parameter has been enhanced to support POST `/v2/sites/:siteName/settings`.
- The parameter only takes in a valid domain name.
- All invalid inputs will throw a 400 BadRequestError.
**Unit tests**:
- Run `npm run tests`
**Smoke tests**:
- Check out the `fix/settings-parameters` branch on the CMS frontend.
- Run `npm run dev`.
- Log in and navigate to any site dashboard, then access the "Site settings" page.
- Modify the value in the "Site URL" input field.
- Verify that the new settings can be saved and correctly displayed upon page refresh.
*None*
> fix: remove resources_name and add support for url

- src/utils/markdown-utils.js
This PR adds a check for trailing slash for all page permalinks, as missing it does not play well with our amplify builds. Resolves https://github.com/isomerpages/isomercms-frontend/issues/1024.
> Fix: add trailing slash to permalink

- package-lock.json
- package.json
- src/constants/constants.ts
- src/database/migrations/20220811070630-change-role-enum.js
- src/database/models/Site.ts
- src/database/models/SiteMember.ts
- src/database/models/User.ts
- src/errors/ForbiddenError.js
- src/fixtures/identity.ts
- src/middleware/__tests__/authorization.ts
- src/middleware/authorization.ts
- src/middleware/index.ts
- src/routes/v1/authenticatedSites/index.js
- src/routes/v2/authenticated/__tests__/collaborators.spec.ts
- src/routes/v2/authenticated/collaborators.ts
- src/routes/v2/authenticated/index.js
- src/routes/v2/authenticatedSites/index.js
- src/server.js
- src/services/identity/CollaboratorsService.ts
- src/services/identity/__tests__/CollaboratorsService.spec.ts
- src/services/middlewareServices/AuthorizationMiddlewareService.ts
- src/services/middlewareServices/__tests__/AuthorizationMiddlewareService.spec.ts
Redo of https://github.com/isomerpages/isomercms-backend/pull/485 because it was too painful to rebase the previous branch.
> feat: collaborators

- package.json
- src/database/migrations/20221003052424-review-request-creation.js
- src/database/migrations/20221003123422-review-meta-creation.js
- src/database/migrations/20221003130006-reviewer-creation.js
- src/database/migrations/20221007124138-create-review-status.js
- src/routes/v2/auth.js
- src/services/infra/InfraService.ts
This PR adds the base db nigrations for review requests; it has some changes from the db schema listed [here](https://lucid.app/lucidchart/a1e55cbb-3938-4ba4-8a9a-2a2c9cdc7a64/edit?page=0_0#).
Related to 
1. add migrations for `reviewers`, `reviewMeta` and `reviewRequest`
2. add a migration for undoing migrations (**locally only**)
> feat(rr): db migrations

- src/routes/v2/authenticated/__tests__/Sites.spec.ts
- src/routes/v2/authenticated/sites.ts
- src/services/identity/SitesService.ts
- src/services/identity/__tests__/SitesService.spec.ts
There is currently no existing API endpoints for getting just the production URL of a particular site. There is an existing site info endpoint but it is too expensive (extra calls to get commits information), and the settings endpoint gets a user-defined value of the production URL, which may not exist or may be empty.
- Introduce a new `/sites/:siteName/siteUrl` API endpoint to get the production URL of the given site.
- Also fixed a regression where the key for the `stagingUrl` has changed.
**Unit tests**: Run `npm run tests`
*None*
> feat: add new siteUrl API endpoint to get the production URL of site

- src/routes/v2/authenticated/review.ts
- src/services/review/ReviewRequestService.ts
The current backend does not support recording a user's viewing status of a particular review request, which makes it impossible for the site dashboard to differentiate between a new/existing review request that the user has/has not seen before.
**Features**:
- A new API endpoint `POST /v2/sites/:siteName/review/viewed` has been added, which does not take in any input and will automatically record all open/approved review requests for that particular site as viewed.
- New functions have been added to ReviewRequestService to mark all review requests as viewed, to update the lastViewedAt attribute for a particular review request, and to delete any existing review request views.
No tests currently. 😭 
*None*
> feat: add review request views API endpoint and functions

- src/routes/v2/authenticated/review.ts
- src/services/review/ReviewRequestService.ts
Currently, there is no specific endpoint for marking a review request as viewed. This would mean that a user that accesses a review request directly using the URL and goes into the site dashboard will incorrectly see the review request as new.
**Features**:
- A new API POST endpoint has been added to allow marking a particular review request as viewed.
There are no tests 😭 
*None*
> feat: add endpoint to mark a review request as viewed

- src/services/review/ReviewRequestService.ts
The current dashboard summary does not display a count of the number of new comments that the user has not seen.
- The existing site dashboard summary endpoint has been enhanced to use the new list comments feature, which provides a boolean for each comment on whether it is the first time the user is seeing the comment. A count is taken and returned to the user.
There are no tests 😭 
*None*
> fix: compute the number of new comments to show

- src/integration/Sites.spec.ts
- src/server.js
- src/services/identity/SitesService.ts
- src/services/identity/__tests__/SitesService.spec.ts
- src/services/review/ReviewRequestService.ts
Currently, the email address of the user that published the site shows the email address stored in the GitHub commit to the master branch. However, as we are using a common access token to interface with GitHub, this email address will always be the same.
**Bug Fixes**:
- The email address of the user that last published the site is now obtained from the review requests table, provided that the commit starts with `isomergithub`, which is the user accounts for Isomer's common access tokens.
There are no tests 😭 
*None*
> fix: use review request requestor email for production commit email

- src/services/review/ReviewRequestService.ts
The order by syntax is incorrect for getting the latest merged review request, which has a cascading effect of causing the whole site info endpoint to not work.
**Bug Fixes**:
- The full ReviewMeta model is now included in the order attribute, as suggested by [this StackOverflow answer](https://stackoverflow.com/a/58524200)
There are no tests.
*None*
> fix: include full model in order by due to presence of alias

- src/routes/v2/authenticated/review.ts
Previously, rr creation was gated only to admins of a site. This was erroneous and rr creation should be allowed by **any site member**. This updates the check + error message
don't check for `admin` role explicitly, merely existence of a role.
> fix(review): allow rr creation by users of the site

- src/fixtures/notifications.ts
- src/integration/Notifications.spec.ts
- src/middleware/notificationOnEditHandler.ts
- src/middleware/routeHandler.js
- src/routes/v2/authenticated/__tests__/Notifications.spec.ts
- src/routes/v2/authenticated/index.js
- src/routes/v2/authenticated/notifications.ts
- src/routes/v2/authenticated/review.ts
- src/routes/v2/authenticatedSites/__tests__/Notifications.spec.ts
- src/routes/v2/authenticatedSites/collectionPages.js
- src/routes/v2/authenticatedSites/collections.js
- src/routes/v2/authenticatedSites/contactUs.js
- src/routes/v2/authenticatedSites/homepage.js
- src/routes/v2/authenticatedSites/index.js
- src/routes/v2/authenticatedSites/mediaCategories.js
- src/routes/v2/authenticatedSites/mediaFiles.js
- src/routes/v2/authenticatedSites/navigation.js
- src/routes/v2/authenticatedSites/resourceCategories.js
- src/routes/v2/authenticatedSites/resourcePages.js
- src/routes/v2/authenticatedSites/resourceRoom.js
- src/routes/v2/authenticatedSites/settings.js
- src/routes/v2/authenticatedSites/unlinkedPages.js
- src/server.js
- src/services/identity/NotificationsService.ts
- src/services/identity/__tests__/NotificationsService.spec.ts
- src/utils/notification-utils.ts
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> feat(ut): generic notifs

- src/fixtures/identity.ts
- src/fixtures/repoInfo.ts
- src/services/identity/SitesService.ts
- src/services/identity/__tests__/SitesService.spec.ts
- src/types/repoInfo.ts
The new identity features do not have sufficient unit test coverage in SitesService, which can be dangerous.
- The remaining unit tests for SitesService has been added for the new identity features.
- The SiteUrl type has been moved into the repoInfo.ts types file, so that it can also be used in the unit tests.
**Unit tests**: Run `npm run test` on this branch to verify that all the new unit tests pass
*None*
> tests: add remaining tests for identity features in SitesService

- src/routes/v2/authenticated/collaborators.ts
- src/types/dto/review.ts
The FE had outdated typings for collaborators, which was fixed by the PR [here](https://github.com/isomerpages/isomercms-frontend/pull/1152); this PR adds the relevant properties to the return value for the `/collaborators` route 
1. use `Jsonify` type to indicate properties
2. omit `SiteMembers` model and parse it to `role`
> chore(collaborators): update typings

- package.json
- src/fixtures/app.ts
- src/fixtures/github.ts
- src/fixtures/review.ts
- src/fixtures/sites.ts
- src/fixtures/users.ts
- src/integration/Reviews.spec.ts
- src/integration/Sites.spec.ts
- src/integration/Users.spec.ts
- src/routes/v2/authenticated/review.ts
- src/services/review/ReviewRequestService.ts
There are currently no integration tests for the review requests feature. This can be dangerous.
- Added some integration tests for the review requests feature
**Bug Fixes**:
- Fixed an issue with the reviews route not waiting for the results of IdentityService first, which can cause the validation check to be skipped when the user is not a member
- Added more sanity checks for comments-related functionality to prevent unauthorised users from adding or retrieving comments
- Standardised the response codes for the non-happy paths
**Unit tests**: Run `npm run test` on this branch
*None*
> tests: add integration tests for review requests and comments

- src/routes/v2/authenticated/collaborators.ts
- src/routes/v2/authenticated/review.ts
previously, #573 added a new middleware for verification of email users and called it in collaborator routes. however, this missed adding a middleware to attach the property that we were verifying, leading to runtime errors.
add required middleware call
> fix(collaborators): add required middleware

- src/routes/v2/authenticated/__tests__/review.spec.ts
There are currently no unit tests for the review requests routes, which can be dangerous.
- Introduced unit tests for the review requests routes
**Unit tests**: Run `npm run test` on this branch
*None*
> tests: add review requests routes unit tests

- src/routes/v2/authenticated/review.ts
- src/services/db/GitHubService.js
- src/services/db/review.ts
- src/services/review/ReviewRequestService.ts
- src/types/dto/review.ts
We don't have a way at present to retrieve raw file contents from github. this PR adds that ability in.
1. add route + service.
**notes**
as mentioned in the fe PR, this is keyed by `:reviewId`, which might be problematic in the future because the rr is an artificial construct and what we really want is a point in time (by the commit hash) of the file contents...
> feat(rr): blob diffs

- src/services/identity/UsersService.ts
- src/services/identity/__tests__/UsersService.spec.ts
See #592 for an overview of the issue
Closes #592
1. remove explicit calls of `findOrCreate` on our db model. instead, this has been replaced with explicit calls to both `findOne` and `create`, which are both wrapped into a single txn to ensure atomicity + consistency
2. test cases updated to ensure that we call explicit methods + use the txn
> fix(usersservice): remove explicit `findOrCreate` calls

- .github/workflows/ci.yml
- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Reviews.spec.ts
- src/routes/v2/authenticated/__tests__/review.spec.ts
This PR adds tests for the notification middleware introduced in #514.
Of special note is the format of the router setup for the test - our actual setup involves invoking the notification creation method only after the response has been sent, but jest ends the test once the response has been received. As such, the test setup involves creating a custom wrapper over the existing notification creation handler to add in the response sent.
> Feat: add generic notification handler tests

- src/services/directoryServices/ResourceRoomDirectoryService.js
This PR fixes a bug in resource renaming - previously we were updating the index file in the location of the old resource room folder instead of the new resource room, which caused the old resource room directory to continue existing - this caused issues for users who attempted to rename a resource room to something they had used before. The name in the `index.html` of the new resource room directory would also be incorrect (using the old name instead). This PR fixes this issue.
> Fix: use new resource room name when renaming

- src/routes/v2/authenticatedSites/contactUs.js
- src/services/fileServices/MdPageServices/MediaFileService.js
- src/services/fileServices/MdPageServices/ResourcePageService.js
- src/services/fileServices/MdPageServices/__tests__/MediaFileService.spec.js
- src/utils/file-upload-utils.js
- src/utils/files.ts
See the notion [link](https://www.notion.so/opengov/VAPT-Remediation-c604c62d822e4023be266c5a293d3a1e) for an overview 
1. prevent users from renaming unless the old extension and the new extension are the same. because we disallow creation of files unless they have certain extensions (`file-upload-utils` defines `ALLOWED_FILE_EXTENSIONS`), this means that existing files already have valid extensions. now, we force the old/new ext to be the same, which implies that we only ever go from existing valid ext -> new valid ext.
> chore(mediafileservice): prevent users from changing file ext

- src/services/identity/CollaboratorsService.ts
- src/services/identity/SitesService.ts
This PR fixes an issue where we were querying for the github repo name of a site through the `Site` table (which contains the human readable version of the name) instead of through the `Repo` table (which contains the desired string). All existing queries referencing the `Site` table for the github sitename have been changed to reference the `Repo` table instead.
> Fix: query for site through repo

- src/routes/v1/authenticated/index.js
- src/routes/v1/authenticatedSites/index.js
- src/routes/v2/auth.js
- src/routes/v2/authenticated/index.js
- src/routes/v2/authenticatedSites/index.js
- src/server.js
Previously, our logs weren't capturing the github username of the isomer user. This led to the github id being logged as `undefined` in our logs.
Closes #620 
Change `apiLogger` to be initialised after `verifyJwt`; this was done through making it a dependency of the required routers (rather than importing) to keep in line w/ existing code conventions
> fix(server): shift api logger to be initialised within each subrouter

- src/services/utilServices/__tests__/AuthService.spec.js
Wrong constant (`signedToken`) used instead of `signedEmailToken` which causes test in AuthService.spec.js to fail
Replace `signedToken` with `signedEmailToken`
Run `npm run test --runInBand AuthService.spec.js` to ensure everything passes
- Details ...
> Fix wrong constant in test

- src/services/identity/DeploymentClient.ts
CSP headers are not preserved with rewrites. 
New sites created will have a redirect rather than a rewrite.
> fix(site creation): make rewrites to redirects

- microservices/README.md
- microservices/package-lock.json
- microservices/package.json
- microservices/serverless.yml
We used to have local development using serverless offline, before we deployed it into the cloud. However, due to limitations of local development, and the differences between local and the cloud environments, there was effort needed to ensure similarity between emulated local and cloud environments. 
This PR removes lingering local emulation of our cloud services that we no longer intend to use. 
Additionally, site launch cloud infra will have staging, production environments. If you wish to develop in an isolated cloud environment, simply create your own version of the infra in the cloud. eg: `npm run deploy:dev -- --stage kishore-test`. 
Notice that the `package.json` has a `source ../.env` before running the `sls deploy` command. I opted to use our .env file at the project root rather …
> Chore(Site launch microservices):managing cloud environments

- docker-compose.yml
we no longer use local stack/step functions
> chore(docker compose): remove local emulation of lambdas

- microservices/package-lock.json
- microservices/package.json
- microservices/serverless.yml
- microservices/site-launch/lambda-functions/failure-notification/index.ts
- microservices/site-launch/lambda-functions/general-domain-validation/index.ts
- microservices/site-launch/lambda-functions/redirection-domain-validation/index.ts
- microservices/site-launch/lambda-functions/step-functions-trigger/index.ts
- src/routes/formsgSiteCreation.ts
- src/routes/formsgSiteLaunch.ts
- src/services/infra/InfraService.ts
The Site Launch form returns an email per site. Ie when using the form to launch 5 sites, the cms backend will return 5 different emails. This can be a hassle for Ops as they have to keep sieving through each of the email to get the site details. 
This PR modifies the site launch logic such that the DNS details of the site launches are consolidated into at most 2 emails (one for successful launches and one for unsuccessful launches) 
Other sub-issues closed: 
The current code in redirection domain lambda is wrong since 
1) The env var was not imported properly
2) The call `octokit.request()` doesn't return an 404 when a file is not found. Instead, it throws an error, which caused our redirection lambda to crash. 
Rather than sending an email directly to Ops per site launch, now only two …
> Feat(site launch): support for multiple sites

- src/routes/v2/authenticated/__tests__/review.spec.ts
Last release added a bunch of checks for sites that are undergoing a migration from github into our db (but not yet completed); this clashes with our code, which expects a **fully** migrated site (sites table in db populated, site members retrieved from db etc). 
This leads to a couple of tests failing in `review.spec.ts` as the calls to calculate those pre-conditions are not mocked. This PR fixes this by mocking said calls.
for methods that have the new checks, there is a new `beforeEach` hook added to mock the call to the precondition. This causes the check to be false (ie, that the site has underwent a full migration), and continues on with the business logic rather than short-circuiting
> chore(review): fix tests for review router

- package-lock.json
- package.json
- src/utils/yaml-utils.ts
the problem is that sanitizing in special pages (homepage, contact us, nav) leads to html tags being removed. though this is expected behaviour, it destructively interferes with user edits.
an example of this is when the user uses <a href = "something" /> to direct users to their internal link; this gets removed sadly and causes errors when we do yaml.parse post sanitization.
sanitize the values post parsing rather than treating the yaml as a raw blob
Upgraded `yaml` from 1.x to 2.x in order to use the `reviver/replacer` functionality. This operates on the value post parsing, which is what we desire. See [here](https://eemeli.org/yaml/#parse-amp-stringify) for more info on this.
This is a [breaking change](https://github.com/eemeli/yaml/releases/tag/v2.0.0) but we only use `.parse` …
> fix(utils): change order of ops and rec sanitization

- src/utils/yaml-utils.ts
sanitization on empty strings lead to empty block comment; also, there is trailing space when sanitization does occur.
`trim` post sanitization + don't sanitize if the string is empty
> fix(utils): sanitize empty string + trim

- src/classes/Settings.js
- src/constants/index.ts
- src/constants/pages.ts
- src/fixtures/github.ts
- src/fixtures/sites.ts
- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Reviews.spec.ts
- src/routes/v1/authenticatedSites/homepage.js
- src/routes/v2/authenticated/__tests__/review.spec.ts
- src/services/fileServices/MdPageServices/ContactUsPageService.js
- src/services/fileServices/MdPageServices/HomepagePageService.js
- src/services/fileServices/MdPageServices/PageService.ts
- src/services/fileServices/MdPageServices/__tests__/ContactUsPageService.spec.js
- src/services/fileServices/MdPageServices/__tests__/HomepagePageService.spec.js
- src/services/fileServices/MdPageServices/__tests__/PageService.spec.ts
- src/types/pages.ts
previously, `PageService` had no associated tests; this PR add the tests in. 
1. write unit tests for `pageService`
- the unit tests are centered around `parsePageName` together with `retrieveStagingPermalink`; the invariants that we want to guarantee will be briefly outlined below
- for static pages (pages whose name are **always fixed**), maintain the invariant that only that specified filepath can be parsed into that name
- guarantee that for resource rooms, we will only get permalink for posts 
- recursive descent (ie, the order in which we attempt to parse is fixed) 
- note that filepaths terminating in `/` will **not** have a name property - consistent w/ how directories behave; we could extend our model to also parse directories but this is not done at present. this should also not …
> test(pageservice): add tests for page service

- src/classes/Settings.js
- src/constants/index.ts
- src/constants/pages.ts
- src/errors/DatabaseError.ts
- src/fixtures/github.ts
- src/fixtures/repoInfo.ts
- src/fixtures/sites.ts
- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Reviews.spec.ts
- src/integration/Sites.spec.ts
- src/integration/Users.spec.ts
- src/routes/v1/authenticatedSites/homepage.js
- src/routes/v2/authenticated/__tests__/review.spec.ts
- src/services/fileServices/MdPageServices/ContactUsPageService.js
- src/services/fileServices/MdPageServices/HomepagePageService.js
- src/services/fileServices/MdPageServices/PageService.ts
- src/services/fileServices/MdPageServices/__tests__/ContactUsPageService.spec.js
- src/services/fileServices/MdPageServices/__tests__/HomepagePageService.spec.js
- src/services/fileServices/MdPageServices/__tests__/PageService.spec.ts
- src/services/identity/SitesService.ts
- src/services/identity/__tests__/CollaboratorsService.spec.ts
- src/services/identity/__tests__/SitesService.spec.ts
- src/services/review/__tests__/ReviewRequestService.spec.ts
- src/types/pages.ts
Part of #585, where the specs failed due to the API changes. This PR fixes the failing tests; most of the fixes are mostly cosmetic but here are a few meaningful changes described below.
1. rework tests to unwrap value
2. for `SitesService.spec`, the spec where `it("should return UnprocessableError when the GitHub commit is not found")` has been altered to only assert that the service is called once. This is because we now short circuit when either the prod/staging commit could not be fetched, rather than continuing on with the code flow. This is because both `staging/prod` commit contain info that we use to derive properties without which the flow isn't meaningful anymore.
> test(app): updated specs to fit with new API  

- src/services/identity/LaunchesService.ts
Currently, the `redirections` table has example of: 
Which is not really true since the website is technically being hosted in the www subdomain, and the redirection occurs at the primary domain instead. 
TLDR refresher: 
blah.gov.sg --A record-> 18.X.X.X 
18.X.X.X returns a 301 redirect to www.blah.gov.sg, where 
www.blah.gov.sg --CNAME-> blah.cloudfront.net, where the website is being hosted. 
Read more [here](https://www.notion.so/opengov/Site-Launch-8c7ee5dc910d426983f9167d3fb8fd2f?pvs=4). 
After this update, the leading ''www" will be removed for clarity. An example row would then be: 
Change the code in backend + manually changing all the values in production DB to reflect this change. 
- Details ...
> fix(launches service): change to primary domain source for clarity

- src/routes/v2/authenticatedSites/__tests__/Collections.spec.js
- src/routes/v2/authenticatedSites/__tests__/ResourceRoom.spec.js
- src/routes/v2/authenticatedSites/collections.js
- src/routes/v2/authenticatedSites/resourceRoom.js
- src/services/directoryServices/SubcollectionDirectoryService.js
- src/services/directoryServices/__tests__/BaseDirectoryService.spec.js
- src/services/directoryServices/__tests__/CollectionDirectoryService.spec.js
- src/services/directoryServices/__tests__/MediaDirectoryService.spec.js
- src/services/directoryServices/__tests__/ResourceDirectoryService.spec.js
- src/services/directoryServices/__tests__/ResourceRoomDirectoryService.spec.js
- src/services/directoryServices/__tests__/SubcollectionDirectoryService.spec.js
- src/services/directoryServices/__tests__/UnlinkedPagesDirectoryService.spec.js
- src/services/fileServices/MdPageServices/__tests__/CollectionPageService.spec.js
- src/services/fileServices/MdPageServices/__tests__/ContactUsPageService.spec.js
- src/services/fileServices/MdPageServices/__tests__/HomepagePageService.spec.js
- src/services/fileServices/MdPageServices/__tests__/MediaFileService.spec.js
- src/services/fileServices/MdPageServices/__tests__/ResourcePageService.spec.js
- src/services/fileServices/MdPageServices/__tests__/SubcollectionPageService.spec.js
- src/services/fileServices/MdPageServices/__tests__/UnlinkedPageService.spec.js
- src/services/fileServices/YmlFileServices/ConfigYmlService.js
- src/services/fileServices/YmlFileServices/__tests__/CollectionYmlService.spec.js
- src/services/fileServices/YmlFileServices/__tests__/ConfigYmlService.spec.js
- src/services/fileServices/YmlFileServices/__tests__/FooterYmlService.spec.js
- src/services/fileServices/YmlFileServices/__tests__/NavYmlService.spec.js
- src/services/identity/__tests__/AuthService.spec.ts
- src/services/moverServices/__tests__/MoverService.spec.js
This PR fixes an issue with our subcollection rename and resource room rename/delete methods. For subcollection rename, when renaming subcollections, we no longer use the `baseDirectoryService.rename` but instead delete and recreate each individual file, meaning it was no longer necessary to pass `githubSessionData`, but our call site still passed this as an argument, which resulted in subcollection renaming not working as expected. The resource room delete/rename methods were missing the `githubSessionData` argument. This PR fjxes this behaviour.
In addition, the existing use of `reqDetails` was changed to `sessionData` to bring it in line with the rest of our methods to reduce confusion.
> Fix/rename subcollection and rename/delete resource room

- src/services/utilServices/AuthService.js
> FE uses !!userId to determine if a user should be directed to the github login flow (which is what our tests work with), this requires a backend change to also return userId when it is the E2E_USER. separately, we should probably maintain 2 types of users for e2e (github + email) or, if we decide that we want to deprecate github in the future, make our existing tests compat w/ email flow
Related to IS-87
add `userId` property when e2e
> fix(authservice): return `userId` when e2e

- src/services/directoryServices/SubcollectionDirectoryService.js
- src/services/fileServices/MdPageServices/CollectionPageService.js
- src/services/fileServices/MdPageServices/ResourcePageService.js
- src/services/fileServices/MdPageServices/SubcollectionPageService.js
- src/services/fileServices/MdPageServices/UnlinkedPageService.js
- src/validators/validators.js
This PR replicates the frontend changes made to restrict the use of `#` as the first character in files and subcollection titles. To be reviewed in conjunction with PR [#1231](https://github.com/isomerpages/isomercms-frontend/pull/1231) on the isomercms frontend repo.
This PR also updates our logging for failure cases on these create/rename endpoints, as the error message was previously not very informative.
> Is 59/fix/disallow special character as first character

- src/services/identity/DeploymentsService.ts
no brand on branded type previously, which resulted in type errors.
1. add `Brand.fromString`
> chore(deploymentsservice): add a brand for <env>Url types

- src/routes/v2/authenticated/__tests__/Sites.spec.ts
- src/routes/v2/authenticated/sites.ts
Links to staging is now defined as `https://staging-cms.isomer.gov.sg/sites/kishore-test/[object%20Object]`
This fix fixes it back to the original state
> fix(staging links): fix failing staging links

- src/routes/formsgSiteLaunch.ts
- src/utils/formsg-utils.ts
The form expects string values. When typing, it is possible for someone to enter a space in the string
Defensively trim all inputs
> chore(site launch form): trim site launch form input

- src/integration/Reviews.spec.ts
- src/services/fileServices/MdPageServices/PageService.ts
- src/services/review/ReviewRequestService.ts
- src/services/review/__tests__/ReviewRequestService.spec.ts
- src/types/dto/review.ts
Frontend requires a link to the cms for each page that was edited within the review request.. This PR adds that in. 
After parsing the page, construct the cms link using the `kind` of the page and redirect teh users there
> feat(rr): construct cms link for users

- .env-example
- src/config/config.ts
- src/database/config.js
This PR adds new env vars which allow us to toggle our DB settings more easily, in response to the frequent `SequelizeConnectionAcquireTimeoutError` we're been encountering on prod.
New env vars added:
- DB_ACQUIRE
- The maximum time, in milliseconds, that pool will try to get connection before throwing error
- currently set to 60000, will increase to 120000
- DB_TIMEOUT
- The maximum time, in milliseconds, before an idle session within an open transaction will be terminated
- currently set to 0 (never timeout), will set to 30000
> chore: add new env vars for db

- src/services/identity/ReposService.ts
This PR fixes an issue with our existing site creation form, which attempts to modify the team permissions of a non-existent team when creating a site.
> Fix: remove modification of non-existent team

- src/fixtures/markdown-fixtures.ts
- src/utils/__tests__/markdown-utils.spec.ts
Right now, we have no tests for the behaviour of the `sanitize` function, which leads to some behaviour being potentially inconsistent.
This was observed in the frontend `sanitize` call vs the backend `sanitize` call, where the frontend call preserves the property `async` as-is, but the backend call adds the empty string to turn it into `async=""`. 
This PR adds a short test for sanitization to ensure that 
1. this behaviour is known
2. that this behaviour doesn't affect functionality.
from the html [spec](https://html.spec.whatwg.org/#boolean-attributes), the 2 forms (`async` and `async=""`) are equivalent and [browser support](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) for the async tag as a whole is wide (only edge support is at v12, others start at v1), so this …
> test(markdown-fixtures): add a test for DOMPurify sanitization

- .env-example
- src/config/config.ts
- src/routes/formsgSiteLaunch.ts
- src/services/identity/LaunchClient.ts
- src/services/identity/LaunchesService.ts
- src/services/infra/InfraService.ts
During development, the CreateDomainAssociation calls are rate-limited to 10 per hour. This low rate limit can cause issues during actual site launches that may affect operations.
To avoid impeding with the actual infrastructure rate limits, this PR mocks all calls to CreateDomainAssociation and GetDomainAssociation in LaunchesService. Only staging, vapt, and prod environments should be making actual calls to Amplify. Additionally, since we are mocking Amplify calls now, we no longer need to wait for 90 seconds after creating domain associations for Amplify to generate the required values.
The mocked objects may seem verbose, but they closely resemble the actual values received when calling Amplify.
There are no breaking changes.
I am concerned that future devs working around site launch …
> Feat(Site Launch): Mock calls to Amplify 

- .env-example
- src/config/config.ts
- src/services/identity/LaunchClient.ts
- src/services/infra/InfraService.ts
Technically we mock both `createDomainAssociation` and `getDomainAssociation` calls, therefore var name is not really accurate
changing the var name before release today to reflect this. 
1pw already updated with the new values. 
new env var: 
export MOCK_AMPLIFY_DOMAIN_ASSOCIATION_CALLS="false"
> style(env var): change naming of var

- .env-example
- src/config/config.ts
- src/services/identity/LaunchClient.ts
- src/services/identity/LaunchesService.ts
- src/services/infra/InfraService.ts
If we try to associate the same domain twice, Amplify will generally throw a `BadRequestException: One or more domains requested are already associated with another Amplify app`, which can inform the user to delete + retry. 
However, this did not hold true if the domain association process timed out, in which case Amplify did _**not**_ throw an error, and neither did it create a new Domain Association during the `CreateDomainAssociation` call. 
To replicate the bug, this sequence of errors would need to happen: 
1) Submit the form for blah.gov.sg for blah-test app.
2) Receive an email for the DNS Results
3) Wait for 24 hours for domain association to time out
4) Retry step 1 
5) Receive an email with the exact same DNS results as step 2. 
One would think that the email received in step 5 …
> feat(site launch): Allow for ops to remove timed out domain associations

- src/fixtures/markdown-fixtures.ts
- src/utils/__tests__/markdown-utils.spec.ts
- src/utils/markdown-utils.js
Previously, there was inconsistent behaviour caused by sanitization on the backend. This is because of dompurify's sanitization config, where it will automatically html encode certain special characters if it detects that there is a html tag. 
This process affects not just content within the tag, but the string as a whole. For example, 
```ts
const x = "& <b>&something</b>"
```
will have both ampersands encoded even though the first one is outside of the b-tag. 
Closes LS-81
In order to make sure that sanitization takes place properly, this PR establishes an invariant, as follows: 
**frontmatter content is never html encoded**. 
This is chosen over html encoding all content in our frontmatter due to the existence of the 3 special pages (homepage/nav/contact-us), where users are able to …
> [LS-81] fix(markdown-utils): change sanitization process + add unescape

- microservices/site-launch/lambda-functions/redirection-domain-validation/index.ts
Bug in prod, it does not append the prepending 'www.'. (eg. https://github.com/isomerpages/isomer-redirection/commit/5aaacbf246a0f141a6bc7a1a3d1b4d2896c087e9) 
Add `www.` 
Prod has already been deployed. This PR is for version control only. We will be tacking automated deployment to the cloud in the `isomer-infra` repo in the future
> fix(redirection lambda): fix `www` error

- src/routes/v2/authenticated/__tests__/Sites.spec.ts
- src/routes/v2/authenticated/sites.ts
Site members were not able to view the staging site because the value was wrapped in an `ok`. 
Closes [138]
This unwraps the value and fixes test cases 
1. Become a site member of a site
2. Go to the dashboard, make sure you are able to view the staging url
> fix(sites): unwrap the ok value if no errors

- src/routes/formsgSiteLaunch.ts
- src/services/utilServices/SendDNSRecordEmailClient.ts
Currently, the emails that are being sent to operations is very bare. This had led to copy pasting errors before, leading to issues with the site launch process in the end / our users have complained that the this information is unclear. As a low handing fruit, this PR changes the way the DNS results are being rendered for lesser chances of error. 
Closes IS-94
This PR has two main changes. 
1. Adds inline HTML styles to make the tables look nicer, refer to the screenshots below for a visual change.
2. Refactoring of the code. Right now, our `formSgSiteLaunch.ts` has too much responsibility, I have created a  `SendDNSRecordEmailClient.ts` whose responsibility would be to return the body of the email content. 
Feedback wanted: While I am certain I want to shift the logic needed to generate …
> fix(site launch email): make table nicer

- src/utils/file-upload-utils.js
This PR fixes an issue where svg images were not allowed to be uploaded.
> Fix: add svg to allowed image types

- src/routes/formsgSiteCreation.ts
- src/services/identity/ReposService.ts
- src/services/infra/InfraService.ts
Currently, the new site creation only allows for email based logins. This is disruptive for ops as there are still some agencies that use the github based logins, and it might be confusing for them to have some websites in the email flow, and some in the github flow. 
Closes 154
Rather than only allowing for email based logins, ops will now have the choice of either email or github logins. 
This PR effectively brings back the code [here](https://github.com/isomerpages/isomercms-backend/pull/713/files) and [here](https://github.com/isomerpages/isomercms-backend/pull/679), but only executes the relevant code iff ops wants to use the email login flow.
The member email is disregarded if ops select the github login flow. 
- Details ...
Staging is now live with this form, …
> feat(site creation): add support for email + github logins

- src/server.js
- src/services/api/AxiosInstance.ts
- src/utils/tracer.ts
currently we got no observability/metrics for email logins etc, which makes it hard to monitor what routes are being hit..
1. add tag onto datadog trace so that the trace contains info on the user type. because this is set on the trace, we also know the http request path. this could be potentially extended by forwarding our session data object onto our isomer axios instance and tying it into the trace
Go to this [link](https://app.datadoghq.com/apm/traces?query=@_top_level:1%20service:isomer-http-client%20env:local%20@user.type:github&cols=core_service,core_resource_name,log_duration,log_http.method,log_http.status_code&historicalData=false&messageDisplay=inline&sort=desc&spanType=service-entry&spanViewType=metadata&start=1683133494852&end=1683134394852&paused=false) and observe that you …
> feat(datadog): add tracing for http requests out

- src/utils/markdown-utils.js
Empty keys on the object leads to us calling `Object.keys` on a `null` value, which causes an error.
check for falsy values
> fix(markdown-utils): add check for falsy values

- src/integration/Sites.spec.ts
- src/routes/v2/authenticated/sites.ts
- src/services/identity/SitesService.ts
- src/services/identity/__tests__/SitesService.spec.ts
- src/types/repoInfo.ts
We are making unnecessary Github calls on /sites page especially on email login flow when this could be a call to our DB. In light of us reaching the limits of Github api, we should try to prevent excessive calls.
Closes IS-165
Added a check on getSites to return the list of site names for the user from our DB (only if it is a non-admin and non-github flow user).
- Details ...
Note minor dependency on https://github.com/isomerpages/isomercms-frontend/pull/1265
Needs to be deployed together
> feat: return sites from db for email login

- src/services/db/GitHubService.js
- src/services/db/__tests__/GitHubService.spec.js
Copying from @alexanderleegs's write up in slack: 
issue with releasing the refetch behaviour change - specifically for concurrent editing of pages in similar locations with different users, there is the risk of race conditions. E.g. User A and B both want to modify folder 1; User A edits a page in folder 1, but before he submits the operation, user B deletes the folder - we suspect this will cause a floating page in the deleted folder 1 that is inaccessible via CMS. This issue is already present in production currently, but it's mostly mitigated by our refetch behaviour, because retrieving updated data on refocus will immediately stop users from making these changes to recently updated files/folders.
Our proposed solution involves adding guards to create and …
> fix(githhub service): get call to github to prevent race condition

- src/services/db/GitHubService.js
This PR fixes a bug in our update behaviour - we were previously checking that the directory a file was in exists before making any update call, but this was failing for our root directory. This PR skips the check if the file belongs to our root directory. Note that `Create` does not need to have this same behaviour - we never create files inside our root folder.
> Fix: handle updating of files in root directory

- src/services/directoryServices/SubcollectionDirectoryService.js
This PR fixes an issue introduced with our create guards when renaming a subfolder - the files were previously created first, then the `.keep` file, but this should be reversed.
> fix: create .keep first when rename subfolder

- src/utils/tracer.ts
`dd-trace` did not fully sample, so we might have missed traces. this is sub-optimal when we want to determine the # of email/github requests hitting our backend api.
see [here](https://docs.datadoghq.com/tracing/trace_collection/library_config/nodejs/) - we just don't let the dd agent decide the sample rate.
> chore(tracer.ts): changed samplerate to 1

- src/middleware/__tests__/errorHandler.spec.ts
- src/middleware/errorHandler.js
refer [here](https://isomeropengov.atlassian.net/browse/IS-104?atlOrigin=eyJpIjoiOTJlMGY5ZDk3MTQ3NDdkN2EzNmFjZjNkMTI1MzUwZjAiLCJwIjoiaiJ9) for overview. brief summary is that auth tokens are being logged and written into our logs. 
Closes IS-104
1. for the error object, we check if there exists an authorization header. if there is, both `request` + `config` is removed. this is heavy handed but required because the library (`serialize-errors`) resolves circular references by [walking down teh properties](https://github.com/sindresorhus/serialize-error/blob/main/index.js#L95), which imght have more references to the header. a brief copy-pasting of the attached log + searching for `token ghp` revealed 15 references, of which some were deeply nested, so this was preferred. 
2. the test setup …
> [IS-104] fix(errorhandler): tweak serialisation of error object

- .env-example
- package-lock.json
- package.json
- src/config/config.ts
- src/services/infra/DynamoDBClient.ts
- src/services/infra/DynamoDBService.ts
Currently, we are migrating from serverless to pulumi and in the process, removing any usage of queues and replacing them with the usage of dynamo db. This is the first PR of a 3 part PR that that focuses on CRUD operations from the dynamoDB. The creation of the DB is done in the Infra PR [here](https://github.com/isomerpages/isomer-infra/pull/1). 
Closes IS-88
Ability to perform CRUD operations on the DB. 
This is not the full implementation, I am keeping the integration work separate from this implementation. This PR is meant to only provide CRUD operations. To aid in the initial testing, I have mocked the values that are to be passed into the `LaunchesService` class. This is the reason why you will notice that the arguments to the methods are **not** used at the moment. 
**Breaking …
> Feat(dynamo db): Crud operations for Dynamo DB 

- src/routes/v2/authenticated/__tests__/Sites.spec.ts
- src/routes/v2/authenticated/sites.ts
Previously we weren't unwrapping the `Result` when we give a resp back to frontend, which results in an `Object object`. This leads to a error when we click the link to go to the live site.
Closes [IS-199]
1. unwrap result
1. go to the CMS
2. login via email
3. go to any site
4. make an edit
5. request a review and approve the PR (or just toggle state in db also ok)
6. publish the site
7. click on `go to live site` in the modal
8. you should be directed to the live site
[IS-199]: https://isomeropengov.atlassian.net/browse/IS-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(sites): unwrap result instead of returning

- package-lock.json
- package.json
- src/routes/formsgSiteLaunch.ts
- src/services/utilServices/SendDNSRecordEmailClient.ts
- src/types/dig.ts
- src/types/node-dig-dns/node-dig-dns.d.ts
Currently, during site launch, if there exists AAAA records for a domain, it must be dropped. There has been some instances when this was not dropped and it conflicts with our process.
Closes IS-109
We perform a dig command to check for AAAA records associated with a domain and add these records into the email we send to Ops to remind them that these records must be dropped.
- Details ...
- `node-dig-dns` : helps perform dig on node.js runtime and returns response as a JSON
Step 0: Set your export MOCK_AMPLIFY_DOMAIN_ASSOCIATION_CALLS="true"
Step 1. Run this from server.js to trigger a fake formsg response, with appropriate values for the emails and repos you have setup
const formResponses = [
{
submissionId: "",
requesterEmail: …
> Add details to drop Quad-A records in email

- microservices/site-launch/shared/types.ts
- src/config/config.ts
- src/server.js
- src/services/infra/DynamoDBClient.ts
- src/services/infra/DynamoDBService.ts
- src/services/infra/InfraService.ts
- src/services/infra/StepFunctionsService.ts
- src/services/infra/__tests__/DynamoDBService.spec.ts
This is the first PR in the effort to remove the usage of queues in our backend. 
Doesn't fully close IS-186, but am putting a feature flag in the spirit of merging some work into prod first. 
The flag `ARE_QUEUES_DEPRECIATED` in `InfraService.ts` will determine whether or not to use the existing queues or use the dynamodbs vs queues for the site launch process. Idea is after the integration work in the infra side + enough testing, we can swap swap the value of the flag for one site launch process, and then if there are no issues for a while in production, we can remove this feature flag + queues related code altogether. 
- Details ...
**Reviewer Notes**
I am not sure if its only me but the typing given in the AWS SDK for dynamo DB is abit off ._. 
I have given a …
> feat(dynamo db): integrate with dynamo db

- src/middleware/notificationOnEditHandler.ts
- src/routes/v2/authenticated/__tests__/review.spec.ts
- src/routes/v2/authenticated/review.ts
- src/services/review/ReviewRequestService.ts
- src/services/review/__tests__/ReviewRequestService.spec.ts
Currently we are fetching all the PRs (Open + Closed) from our DB. Then we do a for-loop over every PR to get its meta, number of comments etc. from Github API. 
This causes unnecessary calls to Github. In line with our effort to reduce Github API calls, and with the fact that there could be at most 1 open PR for a repo (so far), we can further streamline this.
Closes IS-171
We only retrieve the latest (newest by createdAt timestamp) PR that is in "OPEN" or "APPROVED" state. 
Since we may have more than 1 Open PR in future, the changes allow for us to revert back to using `findAll` in a relatively simple way.
- Details ...
**Site dashboard**
- should show only 1 open or approved review request
**Workspace**
- should show the review request alert when there's a review …
> feat: fetch only latest open PR from DB

- package-lock.json
- package.json
- src/services/api/AxiosInstance.ts
- src/utils/headerInterpreter.ts
Currently, Isomer uses a huge amount of tokens due to not caching. This leads to scaling issue, where our github token limits are quickly reached and users are unable to access the CMS.
Closes [IS-172]
1. use an external package `axios-cache-interceptor` to utilise ETags for cache. See [here](https://www.notion.so/opengov/A-brief-primer-on-ETags-94669d1abed44dcbb02ee0ffc36d0a7d?pvs=4) for info on etags. 
- note that this is using **in memory** storage. the implications are that: we could potentially have some requests that **could be cached** but are not (current ETag value is 1 -> user A edits -> ETag value now 2 -> other instance doesn't knows -> queries from other instance -> ETag value updated)
- potential for stale reads - github will tell us if the old etag value is outdated or not …
> fix(headerinterpreter): use custom interpreter

- src/services/identity/DeploymentClient.ts
`DeploymentClient` was referring to `aws.amplify.region` which doesn't exist
change to `aws.region`
> fix(deploymentclient): fix config.get

- src/classes/Directory.js
`Directory.list` can return an empty object. However, our frontend expects an empty array (it calls `val.map`), which causes it to crash on an empty object returned. 
Change the default empty object return to empty array. this is safe because the call sites for `Directory.list` uses a `.reduce` with `[]` as the base acc, showing that they expect empty array (`<Collection | Subfolder>.js`). The callsite in `directory.js` also uses an empty array as the base if there's an error thrown during `.list` (this bug might appear there too).
> fix(directory): default to empty array

- src/logger/cloudwatch.logger.ts
- src/services/identity/LaunchClient.ts
- src/utils/mutex-utils.js
`AWS_REGION` was previously referred to as either `const` in code or env var. this streamlines it to getting it from env vars (through convict). 
1. use `config.get(aws.region)`
- `logger` in `microservices` not migrated due to it drawing in imports
> chore(aws region): shift from const -> env var

- src/services/directoryServices/ResourceRoomDirectoryService.js
This PR fixes an issue where sites attempting to create a new resource room will fail if their `config.yml` has a `resource_room` param, even if it is blank. An additional check has been added to ensure that the param exists.
> Fix: check if resources name is empty when creating new resource room

- src/routes/formsgSiteCreation.ts
- src/routes/v2/authenticated/users.ts
- src/services/identity/CollaboratorsService.ts
- src/services/identity/UsersService.ts
This PR fixes an issue with our email verification process for github users. Previously, for users who were logging in via Github for the first time, they would need to verify and associate their email to their isomer user. However, this input was not parsed in any way, so users would be able to include capitalisation in their associated email. This caused issues when users later tried to login via email - as we forcefully lowercase the email in this case, users were no longer able to access their original isomer user and a new user was created for them instead.
In order to make our behaviour more consistent, we're opting to lowercase all references to email. We will also need to convert some existing isomer user entries - these users have multiple accounts mapped to the same email with a …
> Fix: make email lowercase

- src/services/db/review.ts
Previously, when we were retrieving files from github, we ran into 404s under 2 conditions: 
1. file didn't exist previously (in `master`) but did now (in `staging`) 
2. file existed previously (in `master`) but doesn't now (in `staging`).
because we rely on a `GET` request to github for both of `staging/master`, under either 1 of the above conditions, we will get a 404 which will in turn translate into a 500 on our end. 
1. This fixes the issue by adding a default empty string return when it is a 404 error
- the case where the file didn't exist previously + didn't exist now means that it won't be raised for comparison anyway.
> fix(review): add empty string when 404

- src/errors/BaseError.ts
- src/errors/IsomerError.ts
This PR introduces the base types for Isomer Errors
Closes IS-210
In contrast to the description of task, instead of overloading the logger's error method, we decided to treat logger and error distinctly
Current logger accept a Loggable which is a string or Record<string, unknown> which is a structured log format.
All errors and other types which can be logged will therefore provide a utility function that convert them to one of the above - string or a Record
Hence instead of the logger figuring out how to convert IsomerError and potentially other types in future, it will only accept fixed and predictable types
- Details ...
> feat: introduce types for isomer error

- src/routes/v2/authenticatedSites/__tests__/Settings.spec.js
- src/validators/RequestSchema.js
see [here](https://github.com/isomerpages/isomercms-frontend/pull/1306)
1. change request schema
> fix(requestschema): change to allow for 16 digits for fb pixel

- src/classes/File.js
- src/classes/MediaFile.js
- src/errors/AuthError.js
- src/errors/BadRequestError.js
- src/errors/BaseError.ts
- src/errors/ConfigParseError.ts
- src/errors/ConflictError.js
- src/errors/DatabaseError.ts
- src/errors/EmptyStringError.ts
- src/errors/ForbiddenError.js
- src/errors/IsomerError.ts
- src/errors/MediaTypeError.js
- src/errors/MissingResourceRoomError.ts
- src/errors/MissingSiteError.ts
- src/errors/MissingUserEmailError.ts
- src/errors/MissingUserError.ts
- src/errors/NetworkError.ts
- src/errors/NoAvailableTokenError.ts
- src/errors/NotFoundError.js
- src/errors/PageParseError.ts
- src/errors/RequestNotFoundError.ts
- src/errors/TokenParsingError.ts
- src/errors/UnprocessableError.js
- src/middleware/errorHandler.js
- src/services/fileServices/MdPageServices/CollectionPageService.js
- src/services/fileServices/MdPageServices/PageService.ts
- src/services/fileServices/MdPageServices/__tests__/PageService.spec.ts
We are restructuring the error handling as per discussed RFC, starting with CollectionPageService
Closes IS-212
This PR introduces named parameters for Base Isomer Error. Eventually all the errors should have this, but base error seemed to have the smallest surface area for a initial PR. But because of this change, all "child" classes of the base error will have a small change in their constructors where `super(...)` is called.
We are introducing new fields to the existing error classes - `meta`, `code`, `isV2err`, `componentCode` and `fileCode`.
The error handler is also doing a conditional check to convert the internal representation to external facing. For now, the external rep is just a combination of the `componentCode-fileCode-code`.
As the initial PR, I have modified …
> IS-212 - Migrate collection page service to new error format

- src/config/config.ts
- src/server.js
the step functions arn was not injected in.
Additionally, the env vars are not present in prod :sadge:, but this should have be caught by config.
changing the default values to warns devs if the end var does not exist. 
- Details ...
- `FF_DEPRECATE_SITE_QUEUES = false`
- `STEP_FUNCTIONS_ARN = found in 1pw`
> Fix: step functions env var

- src/middleware/authentication.ts
This PR fixes an issue with error handling caused by throwing an error in an async method in our verifyAccess middleware.
> Fix: wrap async method in try catch

- src/services/directoryServices/SubcollectionDirectoryService.js
This PR fixes a bug in which rearranging the order of a subcollection would something cause collection.yml information to disappear. This issue was caused by us using `includes` instead of `startsWith` to find the list of entries which belonged to the subcollection, which subsequently caused related names to disappear (e.g. changing the order of `Curriculum` would cause `Co Curriculum` to also match this criteria, and hence `Co Curriculum` would disappear)
> fix: rearrange subcollections

- src/services/fileServices/MdPageServices/MediaFileService.js
There exists older repos in which we are unable to rename the files in prod because constrains were placed on the previous file change
disregard checks for the old file name
I have replicated the files that the agency had trouble renaming and placed it in my repo. 
I was now able to [rename](https://github.com/isomerpages/kishore-test/commit/40f8115dc9fdb7f50639cd724b689efc654c3531) the files properly via cms
> fix(mediaFileServices): dont perform check on original file

- tsconfig.json
I keep getting this error that ts files will over ride build files. 
Adding `build` dir to be excluded in this to prevent the errors, but I am not sure if this is the correct way to go about doing this.
> fix(tsconfig): ignore build files

- src/integration/Users.spec.ts
- src/services/utilServices/MailClient.ts
- src/services/utilServices/__tests__/MailClient.spec.ts
Postman API send mail post request to endpoint `/transactional/email/send` returns status code 201 indicating the request has been created, but does not guarantee that the email will be sent and delivered. 
Closes IS-135
After a reasonable delay, verify with Postman that the mail has been delivered. If otherwise, log the status of the email to be tracked. 
- After a 1 minute delay, send a get request to endpoint `/transactional/email/{id}` for the status of the sent email.
- Log the status of the email. If the email has yet to be delivered, log the full email data from Postman.
**Notes**:
This change will cause `Users.spec.ts` to encounter warnings for remaining asynchronous operations after the tests are complete. This is because `MailClient.ts` has a separate routine …
> fix(email): log mail status after reasonable delay

- src/services/identity/LaunchesService.ts
DNS records were not showing properly. Idk if this was due to github screwing up yesterday or I forgot to test them :( 
This feature despreately needs tests, Ill prioritise them after the E2E tests in next sprint :sadge: 
Modify routes to return the correct values
for now manual only, the FE generated DNS records return the correct values
> fix(site launch routes): fix bug

- microservices/site-launch/shared/types.ts
There is an duplicate of type definitions in this repo and infra. While this is not ideal, this was chosen to keep the infra repo private. There lies a risk when devs work on this feature that might change this shape and break corresponding infra. 
Add a comment to warn dev not to change type def.
> chore(types): add warning message about changing the shape here

- src/constants/constants.ts
- src/routes/formsgSiteLaunch.ts
- src/services/infra/InfraService.ts
When site launch fails, it contains error message that is useful for us to consume. This might confuse end users if they were to receive such an email. 
Ideally, if there are any error messages, the user should be given some info if it is recoverable, else it should ping us for manual remediation. 
As a first cut, the failure email heads straights to admin@isomer.gov.sg, so that we are able to take a look at it during launch. 
- Details ...
> Fix: siteLaunchEmailNotification

- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Privatisation.spec.ts
- src/integration/Reviews.spec.ts
- src/integration/Sites.spec.ts
- src/routes/v2/authenticated/__tests__/Sites.spec.ts
- src/routes/v2/authenticated/sites.ts
- src/server.js
- src/services/db/TokenService.ts
- src/services/identity/SitesCacheService.ts
- src/services/identity/SitesService.ts
- src/services/identity/__tests__/SitesService.spec.ts
- src/services/utilServices/RepoCache.ts
`lastUpdated` field for site info has been removed from backend and frontend dashboard for email login users due to excessive token use.  Querying `lastUpdated` for each individual site cost 1 token use each which is too expensive for commonly visited such as dashboard. 
Closes IS-169
`lastUpdated` along with other repo info can be queried in bulk through Github endpoint. Each query allow a maximum of 100 repos and cost only 1 token use. It would take only 10 token uses to get repo info of all sites under `isomerpages` (pageCount 10 for up to 1000 repos). Hence, we can query all repos info at regular intervals and store in a cache to be served on request. Currently, its set to refresh at once per 5 minutes, and with a maximum of 5 instances, which will lead to 10 * 12 * 5 = 600 token uses …
> Feat/IS-169 add site lastUpdated with caching

- src/routes/v2/authenticated/review.ts
- src/services/review/ReviewRequestService.ts
This PR fixes an issue where compareDiff was not filtering placeholder files. This affected any review requests which involved placeholder files, as our frontend does not handle that specific file type. To fix this, we moved the filter from `compareFullReviewRequest` to `compareDiff`, which is called by both relevant endpoints.
> fix: review request placeholder files

- src/services/middlewareServices/AuthenticationMiddlewareService.ts
- src/services/middlewareServices/__tests__/AuthenticationMiddlewareService.spec.ts
The terms collaborator and contributor has semantic differences our our code base.
to be reviewed with [fe pr](https://github.com/isomerpages/isomercms-frontend/pull/1362)
Changing collab to contri naming here for calrity. 
- Details ...
Ran collaborator tests spec here, same result as last week during release.
> chore(e2e): change naming for clarity

- src/services/api/AxiosInstance.ts
Currently our logs of requests to GitHub api only has the endpoint and not the request method. This presents difficulties in identifying which api its calling and whether its a read/write request.
Closes IS-366
Add request method to GitHub api logs. 
> feat(axios): add method to github api logs

- package-lock.json
- package.json
- src/errors/PreviewParsingError.ts
- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Privatisation.spec.ts
- src/integration/Reviews.spec.ts
- src/integration/Sites.spec.ts
- src/routes/v2/authenticated/sites.ts
- src/server.js
- src/services/identity/PreviewService.ts
- src/services/identity/SitesService.ts
- src/services/identity/__tests__/SitesService.spec.ts
- src/services/identity/__tests__/UsersService.spec.ts
- src/services/utilServices/Sanitizer.ts
- src/types/previewInfo.ts
CMS dashboard page displays Isomer logo for all sites
Closes IS-266
This PR implements new POST backend endpoint that takes in a list of site names and try to get urls of preview images for those site. It tries to get the favicon from production site as preview image by parsing the HTML from index page, using a GET request to the url of the production site. If it is unsuccessful, undefined will be returned.
**Features**:
- new `/sites/preview/` POST endpoint that returns the image urls for the favicons of the requested sites.
**BEFORE**:
**AFTER**:
Visual test by visiting the dashboard of all sites. 
- `dependency` : jsdom, which is previously already a dependancy of the backend. This PR adds `@types/jsdom` to `package.json`. 
Requires …
> feat(preview): added preview images

- src/middleware/stats.ts
- src/routes/v2/authenticated/__tests__/Sites.spec.ts
- src/services/api/AxiosInstance.ts
- src/services/infra/StatsService.ts
Adds metric tracking for `pa-corp`.
1. add `statsD` call for new endpoint
2. get the trial site as a `const` in code - **not very tied to this**, we could do either env var or db table instead of this but my understanding is that the trial site is unlikely to change + we are implementing ld soon, which makes the extra effort not worth.
see the data [here](https://app.datadoghq.com/dashboard/8tj-6k5-p2v/isomercms?fullscreen_end_ts=1690257331702&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1689652531702&fullscreen_widget=116425520844967&from_ts=1689647396729&to_ts=1690252196729&live=true)
> feat(stats): track gh calls

- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Privatisation.spec.ts
- src/integration/Reviews.spec.ts
- src/integration/Sites.spec.ts
- src/server.js
- src/services/review/ReviewRequestService.ts
- src/services/review/__tests__/ReviewRequestService.spec.ts
[wip i fixing test cases]
[Credits to @caando for code changes] 
Currently, when calling the the route `/viewed` twice, this might lead to errors thrown in the backend. While the logic is sane, the reason why the errors occur is because there is a race condition when two threads attempt to create at the same time. 
`Upsert` rather than `create`. Note that the `comments.spec.ts` already needed these file changes to work. 
**Limitations**
~~This not the ideal way to solve race conditions. The ideal method is to create a lock and then keep the function `markAllReviewRequestsAsViewed` atomic. However, at this point of time, that might be over-engineering here as the only impact that could happen with unlikely concurrent calls to `markAllReviewRequestsAsViewed` is the dashboard does not turn …
> fix(reviewRequestService): upsert in case of concurrent api calls

- src/services/identity/ReposService.ts
This PR introduces a minor change to site creation to add in the blocking of squash and merge - the reason for this is to prevent users from accidentally using squash and merge to merge prs, which would cause issues in future when attempting to merge staging to master again. See https://github.com/isomerpages/isomer-tooling/pull/47 for the one off fix for existing repos
> chore: update site creation to block squash and merge

- src/routes/v2/authenticated/index.js
- src/routes/v2/authenticated/metrics.ts
- src/services/infra/StatsService.ts
- src/types/dto/feedback.ts
- src/types/user.ts
Adds metric endpoint for submitting user feedback.
1. Written feedback is submitted to our (isomer admin) email. 
2. authentication is done via `verifyAccess` - no additional verification done because this implies that they are a site member already. not inclined to validate `req.body` (we _should_ tbh) as my baseline assumption is that our users aren't savvy enough to extract cookie and ping endpoint via tools (lmk if i shud tho).
> feat(stats): add metrics endpoint

- src/routes/v2/authenticated/sites.ts
- src/services/infra/InfraService.ts
No access controls for admins, can be reviewed with [fe pr](https://github.com/isomerpages/isomercms-frontend/pull/1384).
Only admins can call the BE route.
> feat(siteLaunch): restrict to admin

- package.json
previously, our build output was located at `build/src` now, it's only at `build`. this causes the build script to be screwed up, resulting in a failed deploy
update `npm run start`
> fix(package.json): update build script

- src/services/infra/StatsService.ts
The axios types have changed after upgrading in #850.
**Bug Fixes**:
- The `Method` type has changed to `string` in StatsService due to an upgrade of the `axios` package which has changed the return type
1. Unit tests
2. Build the repo to check that the type error no longer appears
_None_
> Fix axios method type to return string

- src/config/config.ts
- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Privatisation.spec.ts
- src/integration/Reviews.spec.ts
- src/integration/Sites.spec.ts
- src/server.js
- src/services/db/GitFileSystemService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/services/review/ReviewRequestService.ts
- src/services/review/__tests__/ReviewRequestService.spec.ts
- src/tests/setup.ts
- src/types/gitfilesystem.ts
Closes IS-351 and IS-405.
**Features**:
- This PR adds a new RepoService that aims to be a drop-in replacement of the legacy GitHubService
- This RepoService **extends** (instead of implements) the GitHubService so that we can progressively TypeScript-ify GitHubService (and eventually replace it). This allows existing methods to continue being called, keeps RepoService backward compatible and methods can be re-implemented later (such as `read` and `readDirectory` in this PR).
- Eventually, this RepoService will be independent from GitHubService, and other classes can potentially use both concurrently. RepoService will only have methods that are specific to an Isomer site repository (mainly just CRUD operations), whereas GitHubService will only have methods that …
> feat(GGs): Add drop-in replacement RepoService

- src/services/utilServices/AuthService.js
previously, no `.default` added on import leading to errors (due to `export default` interaction wtih `require`)
add `.default` to `require` import
> fix(authservice): update import

- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Privatisation.spec.ts
- src/integration/Reviews.spec.ts
- src/services/db/GitFileSystemService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/services/identity/SitesService.ts
- src/services/identity/__tests__/SitesService.spec.ts
- src/types/commitData.ts
Create a function that provides the latest commit information for a given branch. The return type should match the existing function with the same name in GitHubService. However, the latest commit of branch should be retrieved from the local file system for a whitelisted repository, but continue the existing behaviour of retrieving from GitHub API for a non-whitelisted repository.
Note: In addition to the existing properties, the commit SHA should also be returned, to allow for rolling back of changes.
Closes IS-404
RepoService contains the logic to call the appropriate function depending on whether the repository is whitelisted or not, whereas GitFileSystemService contains the logic to retrieve the latest commit information from the local file system.
- Details ... …
> IS-404: Write extend repo service to get latest commit of branch

- src/errors/GitFileSystemNeedRollbackError.ts
- src/errors/GitFileSystemNeedsRollbackError.ts
- src/services/db/GitFileSystemService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/types/gitfilesystem.ts
Closes IS-400.
**Features**:
- The update operation using the local file system is now supported.
- In the event of an error, the file system may potentially be in an inconsistent state. A new rollback function was added to support resetting the file system to the last working state.
- Pushes will happen asynchronously so that the user can continue working on the CMS while the backend pushes to GitHub.
1. Unit tests
2. E2E tests to verify that there is no regressions
*None*
> feat(GGs): implement update operation

- src/services/db/GitFileSystemService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/services/directoryServices/BaseDirectoryService.js
- src/services/directoryServices/__tests__/BaseDirectoryService.spec.js
- src/types/github.ts
Create a new function in RepoService and GitFileSystemService to support deleting files and folders
Closes IS-401
RepoService contains the logic to determine the service to utilise depending on whether the repository is whitelisted or not, whereas GitFileSystemService should contain the logic to delete files and folders.
There are 2 new functions in RepoService - `delete` and `deleteDirectory`, but both of them utilise a single `delete` function from GitFileSystemService.
This new function should create commits that are similar to the ones created by GitHubService currently. All other Git-related quirks should also be maintained (i.e. deleting the .keep file inside a folder in order to delete it).
- Details ...
To ensure all tests pass with `npm run test`
There are 2 …
> IS-401: Write extend repo service to support delete files folders

- .platform/hooks/predeploy/01_mount_efs.sh
- .platform/hooks/predeploy/02_fetch_ssh_keys.sh
- .platform/hooks/predeploy/03_add_keys_to_ssh_config.sh
- .platform/hooks/predeploy/04_add_github_to_known_hosts.sh
- .platform/hooks/predeploy/05_set_git_profile.sh
This PR contains all the scripts we need to run on an infra-level to make CMS BE ready to integrate with our Git File System Service.
Closes IS-317, IS-319, IS-337, IS-375, IS-390
This PR contains pre-deploy hooks which we instruct Elastic Beanstalk to perform before starting app deployment.
Note: There are 3 different types of hooks - `prebuild`, `predeploy` and `postdeploy`. We are using the predeploy hooks as we need to setup these config before our app starts serving requests.
There are 5 scripts corresponding to the following actions:
This fetches a file system ID & mount location from SSM and mounts the corresponding EFS volume. 
Note that we have decided to perform EFS creation manually outside the use of scripts/hooks as it is a 1-time operation
Next, we will be using SSH …
> feat: add platform predeploy hooks

- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Privatisation.spec.ts
- src/integration/Reviews.spec.ts
- src/integration/Sites.spec.ts
- src/routes/v2/authenticatedSites/index.js
- src/server.js
- src/services/db/GitFileSystemService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/services/directoryServices/BaseDirectoryService.js
- src/services/directoryServices/__tests__/BaseDirectoryService.spec.js
- src/services/fileServices/MdPageServices/MediaFileService.js
- src/services/fileServices/MdPageServices/__tests__/MediaFileService.spec.js
⚠️ **Note: This PR will only be rebased after #892 and #894 are merged** ⚠️ 
Closes IS-402.
**Features**:
- The moving and renaming of files and directories functionality has been implemented as `renameSinglePath` or `moveFiles`.
- The existing functionality for moving files by deleting then creating has been retained temporarily. The refactoring can be left for later.
1. Unit tests
*None*
> feat(GGs): implement moving and renaming of files and directories

- src/services/db/GitFileSystemService.ts
Closes IS-432
Make mkdir synchronous
- Details ...
> fix: use synchronous fs mkdir

- src/classes/Collection.js
- src/classes/Config.js
- src/classes/Resource.js
- src/classes/ResourceRoom.js
- src/routes/v1/authenticatedSites/collectionPages.js
- src/routes/v1/authenticatedSites/collections.js
- src/routes/v1/authenticatedSites/folders.js
- src/routes/v1/authenticatedSites/homepage.js
- src/routes/v1/authenticatedSites/navigation.js
- src/routes/v1/authenticatedSites/netlifyToml.js
- src/routes/v1/authenticatedSites/pages.js
- src/routes/v1/authenticatedSites/resourcePages.js
This PR fixes an issue introduced by the upgrade of `base64-js`, which previously worked without an explicit import. The affected endpoints are all v1 endpoints, but several api calls on the frontend still use v1 endpoints. We should modify the endpoints being used on the frontend to use v2 endpoints instead, but I've opted for this solution first, since at least 2 of the remaining endpoints do not work with a direct swap (edit nav uses a v1 endpoint that has no equivalent functionality in v2, and edit page uses an outdated v1 endpoint that the v2 endpoint changes the dto of).
> fix: require base64

- src/middleware/routeHandler.js
- src/services/db/GitFileSystemService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
The GGs MVP solution is imperfect.
**Bug Fixes**:
- The `getLatestCommitOfBranch` function was only successful in getting the Git logs for branches that also exist locally. This has now been adjusted to retry with an `origin/` prefix if it failed the first time, so that it gets the latest hash of the origin remote.
- Note: The reason why we do not just default to using `origin/` prefix is because there might be some local changes that have not been pushed to GitHub yet for the staging branch. The `origin/staging` remote would be stale during the period of time where the local commits have not yet been pushed to GitHub. Hence, first using the local branch ensures that we always return the latest commit information.
- The `git mv` function is too strict and causes …
> fix(GGs): hotfixes from bugs identified during testing

- src/services/identity/SmsClient.ts
Currently we are oblivious when Twilo goes down. 
This logs a specific string which we can later use to to trigger alarm. We **_only_** log for 5xx errors since we dont want to trigger alarms for say invalid numbers. 
However, since this is infra level stuff, this is a bit hard to test + cannot guarentee that there wont be any false positives. To monitor post deploy if this solution is ok. 
- Details ...
Post release we would need to create a custom metric for our backend.std.out errors to match for `Postman is returning 500 error for sending sms` + create a corresponding alarm for that metric.
> feat: Log 5xx errors for sms client

- src/integration/Reviews.spec.ts
When the PR #867 was introduced, the test case was mocked so there was no proof of functionality (at the unit test level) + no test cases to actually prevent regression. 
Add integration test for this.
**BEFORE**:
NOTE: This is run on a codebase where the changes introduced in #867 was _**reverted**_. 
**AFTER**:
integration tests
> feat(integration): reviews inte test

- src/integration/Reviews.spec.ts
Reverts https://github.com/isomerpages/isomercms-backend/pull/909 - now that our mutex lock works, the test throws a 423 error instead, and we're unable to replicate the conditions which we were testing on production anymore (prod instead returns 423 for 2 update calls in quick succession)
> chore: remove test for concurrent viewed call

- src/classes/UserWithSiteSessionData.ts
- src/config/config.ts
- src/fixtures/sessionData.ts
- src/middleware/authentication.ts
- src/middleware/featureFlag.ts
- src/middleware/index.ts
- src/middleware/routeHandler.js
- src/services/db/RepoService.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/types/express/request.d.ts
- src/types/featureFlags.ts
- src/types/request.ts
- src/utils/growthbook-utils.ts
We are currently using env vars to rollout GGS implementation which requires a rebuild each time we change something.
Closes IS-506
Use GrowthBook feature flag. Introduces a new flag `ggs_whitelisted_repos` with a json structure of `{ "repos": string[] }`. Please check the portal for more info.
Note: To be reviewed in conjunction with IS-310 and IS-312
- Details ...
- Ensure whitelisted repos are being read in from GB. To do so, can add a simple `console.log` in `isRepoWhitelisted` function of `RepoService`.
- Ensure all unit tests pass especially for `RepoService.spec.ts`
Please remove existing env var of `WHITELISTED_GIT_SERVICE_REPOS` from EB.
**Deprecated environment variables**:
- `WHITELISTED_GIT_SERVICE_REPOS`
**New feature flags**
- `ggs_whitelisted_repos`: …
> IS-506: Migrate GGS Whitelist Feature Flag to GB

- src/middleware/authentication.ts
- src/tests/setup.ts
Hotfix for the following error:
```
{
"name": "TypeError",
"message": "Cannot read properties of undefined (reading 'githubId')",
"stack": "TypeError: Cannot read properties of undefined (reading 'githubId')\n    at AuthenticationMiddleware.verifyAccess (/var/app/current/src/middleware/authentication.ts:59:30)"
}
```
Removing unneeded env var setup for tests
> Hotfix - Staging E2E, Tests

- package-lock.json
- package.json
- src/services/identity/ReposService.ts
Creating the DNS indirection domain will fail when multiple site launches are performed in a single site launch form submission.
**Bug Fixes**:
- An octokit plugin (`@octokit/plugin-retry`) is used to automatically retry on retry-able errors. This includes the 409 error code returned by GitHub due to concurrent edits made to the indirection repository.
Unable to test directly as this is a site launch change. However, the following code was used to simulate concurrent creation of files:
```javascript
const { Octokit } = require("@octokit/rest");
const { retry } = require("@octokit/plugin-retry");
const FILE_CONTENTS = "Hello, world!";
const GITHUB_TOKEN = "TOKEN_HERE";
const MyOctokit = Octokit.plugin(retry);
const octokit = new MyOctokit({
auth: GITHUB_TOKEN,
request: …
```
> fix(sl): add retries when creating indirection domain

- src/constants/constants.ts
- src/middleware/routeHandler.js
- src/server.js
We are rolling out GGS to more sites and we need to ensure that GGS scales with increase in number of concurrent sites.
Closes IS-548
With relation to https://github.com/isomerpages/isomer-tooling/pull/51, we found out the following:
> Having a shared simple-git instance for all repos works fine without errors, provided that we increase the MAX_CONCURRENT_PROCESSES to be equal the the number of repos we want to support concurrently.
Assuming each Git process has an upper bound of 10MB of memory usage, and given a RAM size of 2GB, we can support a max of 200 processes.
Allowing for some buffer, we will make this number 150 as a upper bound. Note that this is still way higher than our realistic expected usage.
We observed a total of 3500 calls / hour which works to be roughly 60 per minute. …
> IS-548: Add max concurrent git processes

- package-lock.json
- package.json
- src/integration/Sites.spec.ts
- src/server.js
- src/services/identity/ReposService.ts
We need to ensure new repos/site creations are automatically cloned into the EFS
Closes IS-342
We are already creating a local git folder with the base template under `/tmp` and doing a `git push` to create it on github. Instead of creating it in `/tmp`, now it will create within the `EFS_VOL_PATH` and instead of http git remote, it uses ssh protocol.
Note: Had to change from isomorphic-git to using simple-git as we are using SSH auth. SSH auth is not supported in isomorphic git.
Example of site created with this code: https://github.com/isomerpages/harish-test-staging/tree/staging
- Details ...
1. Create a site using the staging site-creation form
2. Ensure the site is created on GitHub. Default branch should be staging as shown in below screenshot.
3. Both staging …
> IS-342: Clone repos into EFS vol path

- .github/pull_request_template.md
It is becoming harder for one eng to keep track of all the other feature flags that are avail. It is also well known a lot of production bugs in big tech companies are results for failed roll outs for experiments. (eg, amplify build times vs repo privatisation) 
Eng to manually tick off that their features are compat with the permutations of the features (or at least spend some time thinking intentionallu about it) 
- Details ...
- No - this PR is backwards compatible with ALL of the following feature flags in this [doc](https://www.notion.so/opengov/Existing-feature-flags-518ad2cdc325420893a105e88c432be5)
> feat(template): add ffs as a manual check-in

- src/constants/constants.ts
- src/services/db/GitFileSystemService.ts
- src/services/db/GitHubService.js
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/GitHubService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
Part of IS-446.
⚠️ **Most of the lines changed are due to reordering of lines, feel free to review commit-by-commit if you prefer** ⚠️ 
**Features**:
- The existing `updateRepoState` functionality has been enhanced such that it can also be used for Git repositories on the local file system (i.e. GGS). This is the first step required to allow E2E test repos to be reset on the local file system.
- The `isomer-indirection` repository was not present in the list of admin repos, and has now been added.
Unit tests.
*None*
> feat: add ability to update repo state for GGS

- src/routes/v2/authenticatedSites/__tests__/RepoManagement.spec.ts
- src/routes/v2/authenticatedSites/index.js
- src/routes/v2/authenticatedSites/repoManagement.ts
- src/server.js
- src/services/admin/RepoManagementService.ts
- src/services/admin/__tests__/RepoManagementService.spec.ts
- src/services/middlewareServices/AuthenticationMiddlewareService.ts
- src/utils/mutex-utils.js
Part of IS-446.
**Features**:
- A new endpoint `/v2/sites/:siteName/admin/resetRepo` has been added to allow for e2e test repos to be easily reset to the specified commit.
- If the repository is GGS-whitelisted, it will execute the Git commands on the local file system (`git reset --hard` and `git push -f origin`). It also checks beforehand that the commit exists, otherwise a 400 error is returned.
- If the repository is not GGS-whitelisted, it will call an existing GitHub endpoint to update the repo state, which is an existing functionality used on the frontend to reset repos. GitHub automatically checks if the commit exists and will reject if it does not, but we return a 502 error as we cannot differentiate between this issue vs GitHub-related issues.
**Further …
> feat: add new admin endpoint to reset repository

- .github/pull_request_template.md
Env vars are required in quite a few places but we have to remember this manually. This PR updates the PR template so there's a reminder
Update PR template to have check for env var to add to 1pw + ssm
> docs(pr-template): add checkbox for ssm and 1pw for env var

- .env.test
- .platform/hooks/predeploy/06_fetch_ssm_parameters.sh
- src/config/config.ts
- src/routes/formsgSiteClone.ts
- src/routes/formsgSiteCreation.ts
- src/server.js
See [here](https://isomeropengov.atlassian.net/browse/IS-558?atlOrigin=eyJpIjoiOTQyOTA0ZWIyZDNjNDhmYzhiYzJjMDgxZTY5ZjJmMTYiLCJwIjoiaiJ9)
1. add an endpoint at `/formsg/clone-repo`
2. add handler to clone at that endpoint based on the [form's](https://form.gov.sg/6512935d3efe7a0012034f61) reply. The form has validation build in (email domain **must** be `.open.gov.sg` and **must** verify email + repo is a required field)
- `SITE_CLONE_FORM_KEY`: used to decrypt the form sg submissions (already added to 1PW on both `staging` and `prod` env vars; not yet added to `staging` EB yet)
this was tested **locally** through updating the `EFS_VOL_PATH` + `originUrl` (use `https` instead of `ssh` as i was facing auth issues) and found working
> feat(formsg): clone repo on webhook trigger from forms

- src/validators/RequestSchema.js
Closes IS-471.
**Bug Fixes**:
- The location section of the contact us frontmatter is now optional. Code changes are mostly just indentation, except for the last line where the `required()` part is removed.
Testable only with frontend.
*None*
> fix(contactus): allow location section to be empty but not contact information

- src/routes/v2/authenticatedSites/__tests__/MediaCategories.spec.js
- src/routes/v2/authenticatedSites/mediaCategories.js
- src/services/db/GitHubService.js
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitHubService.spec.ts
- src/services/directoryServices/MediaDirectoryService.js
- src/services/directoryServices/__tests__/MediaDirectoryService.spec.js
- src/services/fileServices/MdPageServices/__tests__/MediaFileService.spec.js
- src/types/gitfilesystem.ts
See [here](https://github.com/isomerpages/isomercms-frontend/pull/1578) for description
- add `page` and `limit` to the media endpoint. we don't paginate directories (for now) due to reasons stated in the other PR. 
- also added 2 more endpoints for fetching files/directories separately. the reasons are given in the other PR. As github **does not** allow us ([no link header](https://docs.github.com/en/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28#using-link-headers)) to paginate the repository content [endpoint](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content), this pagination exists solely on our end, **not on github**. 
- this means that we only save on 1 network call (from be -> fe) and we don't save on the network call …
> ref(media): paginate media endpoint

- src/services/db/RepoService.ts
- src/types/gitfilesystem.ts
**NOTE: ** This PR requires the corresponding FE PR [here](https://github.com/isomerpages/isomercms-frontend/pull/1581)
Right now, we return the image fully per call. This isn't optimal because we have to load the image fully even when we don't need it. As an example, consider the image move - we don't require the images (only titles), but we do a full load inclusive of the image data. 
1. Defer fetching the image to the `readMediaFile` endpoint instead of returning wholesale from `listDirectoryContents`
**Tests coming in another PR**
> ref(media): defer image loading

- src/database/migrations/20231019073829-add-staging-lite-hosting-id.js
In the creation of staging lite apps, we need to store the id. 
Alternative Consideration: 
We dont really need this column, because we could derive this by just keeping this within the staging url. (the staging url actually has the app id here). The reason for adding this is because of 
1. the unknowns of what if we need a rollback for quickie (esp for privatisation), the info is lost. 
2. speed of dev. I intend to decouple releasing of quickie from actually laying the infra work needed for quickie (including private sites. Rather than maintaining a mental model of 'oh some amplify github repos have staging branches and some dont, we make ALL sites have a staging github repo, but it will not be used (at least in the case of private repos) until next year. 
TLDR; this helps lay the …
> feat(staging-id): add column to store the id

- src/constants/constants.ts
- src/database/models/SiteMember.ts
- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Notifications.spec.ts
- src/integration/Privatisation.spec.ts
- src/integration/Reviews.spec.ts
- src/integration/Sites.spec.ts
- src/routes/v2/authenticated/__tests__/review.spec.ts
- src/routes/v2/authenticated/review.ts
- src/routes/v2/authenticated/sites.ts
- src/server.js
- src/services/identity/CollaboratorsService.ts
- src/services/identity/IsomerAdminsService.ts
- src/services/identity/UsersService.ts
- src/services/identity/__tests__/CollaboratorsService.spec.ts
- src/services/middlewareServices/AuthenticationMiddlewareService.ts
- src/services/middlewareServices/AuthorizationMiddlewareService.ts
Closes IS-654.
**Features**:
- A new collaborator role `ISOMERADMIN` has been added to identify users in the IsomerAdmins table. This additional role allows Isomer admins to have access to sites and act as if they are an admin of that particular site.
- The logic for the review request summary has been updated to reject GitHub login users if the site has already been migrated. This is to prevent GitHub users from editing their existing sites after we migrate them from GitHub to email login, and to encourage them to edit using their email-login account.
- Unit tests
- Smoke tests (on https://github.com/isomerpages/isomercms-frontend/pull/1604)
*None*
> feat: allow Isomer admins to edit on email-login and adjust permissions

- src/constants/featureFlags.ts
- src/middleware/routeHandler.js
- src/services/db/RepoService.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/types/featureFlags.ts
Right now, our GGS flag adopts a two tiered approach - first, we get the list of repos from growthbook then we validate based on that. 
This is a _whitelist_ approach, where we add sites as they shift to ggs. This is effortful and going forward, we want to make our flag a _blacklist_ approach, where we allow sites by default until we need to blacklist them. 
Add new flag on growthbook that returns a boolean value checking if the user type is email and whether site is blacklisted. (it's true if user is email && site isn't blacklisted)
**these steps have to be done pre deploy**
**these steps have to be done post deploy**
> refactor(ff): make site launch flag a bool flag

- .env-example
Auth redirect endpoint still uses the v1 endpoint and should be updated to v2.
- The auth redirect endpoint has been upgraded to v2.
Login via GitHub, it should work as normal.
⚠️ **The GitHub OAuth apps need to be updated AT THE SAME TIME, otherwise new logins will fail (existing logins are unaffected)** ⚠️ 
**CHANGED environment variables**:
- `REDIRECT_URI` : Any instances of `v1` in the string should be replaced with `v2`. Values in 1PW have already been updated, and the "Authorization callback URL" settings need to be updated:
> chore(auth): upgrade auth redirect endpoint to use v2

- package-lock.json
- package.json
- src/fixtures/media.ts
- src/routes/formsg/formsgGGsRepair.ts
- src/services/db/GitFileSystemService.ts
- src/services/db/GitHubService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/services/review/ReviewRequestService.ts
- src/types/media.ts
- src/utils/__tests__/media-utils.spec.ts
- src/utils/media-utils.ts
Part of 681 and 682.
**Features**:
- The response when getting each media file now includes the timestamp that it was added.
- For GGS repos, the added time is correct in the sense that it is the "birthtime" of the file.
- For non-GGS repos, because Git has no concept of file creation timestamps, we have to get this information from the Git commit history. However, one caveat is that it is possible for the user to have deleted the file and created another with the same name, so we cannot rely on getting the earliest commit of that path. Since we generally only create commits when they upload, we can make a "best guess" using the latest commit.
- The `neverthrow` library has been upgraded to take advantage of [better type …
> feat(media): include added time for every file

- src/services/db/GitFileSystemService.ts
- src/services/identity/ReposService.ts
By right we are supposed to use `root = false`, to quite the [doc](https://github.com/steveukx/git-js) 
```
.cwd({ path, root = false }) Sets the working directory for all future commands either in the current chain of commands (where root is omitted or set to false) or in the main instance (where root is true).
```
Ran this agains this against ~30 sites at one go, no errors like the ones we previously observed
> fix: reposervice fix cwd

- src/services/identity/ReposService.ts
forgot to add in one more to #1004 
no more .cwd(path) signatures found
> fix(reposService): simple git path cwd

- src/fixtures/media.ts
- src/services/db/GitFileSystemService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/types/media.ts
- src/utils/__tests__/media-utils.spec.ts
- src/utils/media-utils.ts
Part of 720.
**Features**:
- The frontend needs to report the size information when deleting media, lets now send it together as part of the query to get the media data information.
**Bug Fixes**:
- The file sha was accidentally removed, now added back.
Unit tests.
*None*
> feat(media): add size information when getting media data

- src/services/db/GithubCommitService.ts
Quickie has been facing some behaviour recently. I am not sure if this fixes it, but logically this tweak feels like better code as sane defaults > not having them -> undefined which is falsely and then subsequently makes `isStaging` === false
> fix(githubCOmmitService): add sane defaults

- src/services/review/ReviewRequestService.ts
Our logs get a lot of false-positives that files are missing, but that is because our `ALLOWED_FILE_EXTENSIONS` does not take into account upper-case.
**Bug Fixes**:
- Allow ReviewRequestService to check for the upper-case versions as well, and handle them as a proper image.
- NOTE: We are not allowing end-users to upload images with upper-case file extensions. This change is just to add support for backward compatibility.
1. Go to `sla-geoworks` site on CMS (ensure you have it cloned locally on your own GGS)
2. Check that the logs do not throw any errors regarding being unable to get the Git blob hash for uppercase file extensions.
*None*
> fix(rr): capture file extensions that are in uppercase

- src/services/db/GitFileSystemService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/types/gitfilesystem.ts
The ordering of the media files should be by the addedTime in descending order.
- The media files are now sorted by the addedTime in descending order for users on GGS (i.e. email-login users).
- Unfortunately, it is very expensive to get the addedTime for each file from the GitHub API, as there is no concept of creation timestamp (since it is entirely based on commits). We currently do get this information when individual files are requested, but it would get very expensive if we do this for all files at once.
- Hence, we are retaining the existing behaviour of sorting by the file name for GitHub-login users, but we will let email-login users have the sorting by addedTime.
Unit tests, smoke tests on the frontend.
*None*
> fix(media): change media sorting to addedTime descending

- src/routes/v2/authenticatedSites/mediaCategories.js
- src/services/db/RepoService.ts
- src/services/directoryServices/MediaDirectoryService.js
Our images modal in FE is broken when search is used due to pagination. 
Review this tgt with [fe](https://github.com/isomerpages/isomercms-frontend/pull/1668) 
Screenshots 
[ ] Go into a repo with lots of images (at least > 15 since thats what we paginate by)
[ ] Search for any image that would be > 15th index when alphabeticaly ordered. (eg. seach for an image that start with z) 
[ ] ensure that you can see the image in the modal
> fix(pagination): images fix pagination

- src/services/identity/DeploymentClient.ts
- src/services/identity/DeploymentsService.ts
Stagign lite apps were created with master and stagign branches on site create, when it should have been just the staging-lite branch,
change deployed branch
tested local function call directly, verified that 
1. staging lite creates just the lite branch
2. main app with 2 branhces are created
> fix(staging-lite): apps were created for wrong br

- src/services/db/RepoService.ts
Fix ui bug when searching. Last time total length used to be the length of all the files, so this lead to the last few pages on search to be null.
> fix(pagination): total length

- src/services/db/GitFileSystemService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
Birth time shows 0 on EFS for some weird reason.
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> fix: use cTimeMs instead of birthtime due to EFS

- src/services/identity/DeploymentClient.ts
- src/services/identity/DeploymentsService.ts
Stg lite never configure properly, the url not correct + the redirect rules were not present + for reasons I do not know why there were blips when some of the sites had their jobs queued + it did not start even after a while. As such am pinging Amplify to release the jobs. Not sure if this completely fixes it, not sure why we have this issue now, so intent here is to add the release job + monitor for tickets. 
running this in server.js 
```
deploymentsService.createAmplifyAppOnAws(
"kishore-test-dev-gh",
"kishore-test-again-delete-me",
false
)
deploymentsService.createAmplifyAppOnAws(
"kishore-test-dev-gh",
"kishore-test-again-delete-me-staging-lite",
true
)
```
note that there will be two apps being created in amplify. Staging lite will have the redirect rules for images + files, while …
> fix(siteCreate): add redirect rules

- docs/gigDnsApi.yaml
We are working with GIG from ITSM to explore the possibility of automatically updating DNS records for agency domains as part of the future site launch process. 
As the first step, we are requested to create a swagger API spec to show how the API endpoints could look like before GIG can implement them. 
Closes [IS-611]
This PR added a swagger file under `docs` folder. 
To view the API specs on Swagger UI, use one of the two methods:
- View it on the [public link from Swagger Hub](https://app.swaggerhub.com/apis/admin556/gig-dns_management_api/1.0.0)
- Download the file and load it directly to [swagger editor](https://editor-next.swagger.io/)
- Details ...
[IS-611]: https://isomeropengov.atlassian.net/browse/IS-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
> Added swagger doc for GIG DNS API

- src/routes/formsg/formsgGGsRepair.ts
The remore was not set properly. Reason why this error was not caught eariler was beacuse git itself is tolerant to this error, but our BE logic is not as we check a strict string check. 
add .git at the end
> hotfix(repair-form): set remote url correctly

- src/services/db/GitHubService.ts
- src/services/db/GithubCommitService.ts
- src/services/db/RepoService.ts
Moving forward, since we have migrated most sites out of gh, we will only offer quickie for sites that are in ggs. 
As such, this pr removes the dependency of a no longer supported flow so as to allow for a simpler mental model. 
Additionally, there were weird abstractions bet GithubService + GithubCommitService -> removed the responsibilities to be isolated.
Test cases will be added in the leaf node of these prs, cicd will also be fixed upstream.
> feat(quickie): only gitfile should have quickie

- src/fixtures/sessionData.ts
- src/services/db/GitHubService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitHubService.spec.ts
adding test cases for the two new functions `renameSinglePath` and `deleteDirectory` introduced into `GithubService` in #1042. Note that these functions already existed, but this pr adds the test cases to the right file.
> test(githubService): add tests

- src/middleware/routeHandler.ts
Remove rollback of stg-lite in Github flow
Stg-lite only applies for repos in GGS flow
> fix: remove stg-lite rollback for non-ggs flow

- src/constants/constants.ts
- src/services/db/GitFileSystemService.ts
- src/services/db/GitHubService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/types/gitfilesystem.ts
- src/utils/files.ts
Sites with a lot of images cannot load their images on the CMS.
- Perform a filter first before getting the Git blob hash, which was found to be quite expensive for a large number of files.
**Bug Fixes**:
- The addedTime attribute was accidentally reverted earlier, fixed that so that the added times are now correct on EFS.
- Skip checking the `.git` folder, so we should have less error messages in the logs.
Smoke test:
*None*
> fix(media): filter first before getting git blob hash

- Dockerfile
- docker-compose.yml
- package.json
We want to shift our infra over to ecs instead of eb as ecs is faster to deploy + easier to work with. This PR dockerises our app as a first step. 
1. add docker file
2. add docker compose
- hot reload is enabled still by using volume mapping; we map the vol on disk to the docker volume so that on chnage of the files on disk, docker notices
- as our containers are part of the same network, the postgres url has to use the docker volume instead. (see comment for format in code)
> feat(docker): shift app to docker

- src/services/db/GitHubService.ts
- src/services/db/__tests__/GitHubService.spec.ts
- src/types/github.ts
Closes [IS-835](https://isomeropengov.atlassian.net/browse/IS-835?atlOrigin=eyJpIjoiNGJiMzk4NTM4NmRlNGYxYmEzODU5MjY5MzY1YWQwOGYiLCJwIjoiaiJ9)
There are 13 instances of `any` in the file `GitHubService.ts`. The usage of `any` should be avoid if possible to maintain the type safety of Typescript. 
Defined explicit types for all instances of `any` in `GitHubService.ts` 
- Details ...
- Ensure type safety by replacing all instances of `any` with explicit types in `GitHubService.ts` file 
Clone the branch and run backend locally to confirm there is no error from type checking
[IS-835]: https://isomeropengov.atlassian.net/browse/IS-835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IS-835 Removed all instances of any from GitHubService.ts

- src/services/db/GitHubService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/types/github.ts
Closes [IS-836](https://isomeropengov.atlassian.net/browse/IS-836?atlOrigin=eyJpIjoiM2JkYjcxYjAwZjkwNDdkNWI3NmQ5ZGE2NmY1ZTdkN2IiLCJwIjoiaiJ9)
There are a lot of instances of type `any` in the file `repoService.ts`, and we need to replace them with explicit types to ensure type safety. 
Replaced all instances of type `any` in `repoService.ts`
- Details ...
- Replaced all instances of type `any` in `repoService.ts`
CI test to confirm no error in type checking 
[IS-836]: https://isomeropengov.atlassian.net/browse/IS-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ref(ts migration): replaced all instances of any with explicit types in repoService.ts

- src/routes/v2/authenticatedSites/media.ts
- src/services/db/GitFileSystemService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
fix for renaming subfolders
We made a change to fast load images as huge repos with a lot of images had very slow load times.
We used to do: get all files -> calculate hash -> filter/paginate
Now, we get all files -> filter/paginate -> calculate hash
For the get all files to be fast, we removed the sha calculation in the first step of get all files. However, this affected other ops which use list directory contents
Specifically, when we try to rename a subfolder, we need to delete the current directory and re-create a new one
When deleting the current directory, it uses list directory method, but the sha is not present. So when it does a verification of oldSha === newSha, it fails as oldSha is undefined. This causes BE to think that the file was recently changed, so it blocks the delete …
> fix: add conditional sha calc

- src/routes/v2/authenticatedSites/__tests__/Media.spec.ts
- src/routes/v2/authenticatedSites/media.ts
- src/services/db/GitFileCommitService.ts
- src/services/db/GitFileSystemService.ts
- src/services/db/GitHubService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileCommitService.spec.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/db/__tests__/GitHubService.spec.ts
- src/services/db/__tests__/RepoService.spec.ts
- src/services/fileServices/MdPageServices/MediaFileService.js
- src/services/fileServices/MdPageServices/__tests__/MediaFileService.spec.js
- src/validators/RequestSchema.js
> [!NOTE]
> Large PR due to unit tests, feel free to browse by commits
The current delete file endpoint often encounters the repo lock, prevent users from deleting multiple files at once.
- A new endpoint has been introduced to allow for deleting of multiple files in a single repo lock transaction.
- Unit tests.
- Smoke tests (written on https://github.com/isomerpages/isomercms-frontend/pull/1753)
*None*
> fix(media): introduce delete multiple files endpoint

- src/middleware/routeHandler.ts
Closes [IS-834](https://isomeropengov.atlassian.net/browse/IS-834?atlOrigin=eyJpIjoiYzg1MGM2Mjk0ZGM1NGRkYzlmOTk3OTAxMWJjMWM4NTkiLCJwIjoiaiJ9)
There are many usages of `any` in the file `routeHandler.ts` which is not type safety in Typescript. 
Replaced all usage of `any` with explicit types in `routeHandler.ts`
- Details ...
- Replaced all usage of `any` with explicit types in `routeHandler.ts`
Run the code locally to confirm no type checking error or waiting for the CI to pass 
[IS-834]: https://isomeropengov.atlassian.net/browse/IS-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ref(ts migration): replaced all instances of any in routeHandler.ts with explicit types

- src/routes/formsg/formsgSiteLaunch.ts
- src/services/utilServices/SendDNSRecordEmailClient.ts
- src/types/caaAmplify.ts
- src/types/dig.ts
Prevent [this](https://www.notion.so/opengov/On-Call-Runbook-ab4bffa2472d47ef9b657242632da7f9?pvs=4#c16acb00f4524e84b1ebd6509fdf82db) from occurring by warning the agency and ops beforehand regarding a possible site launch failure route. 
Check for existence of CAA records, and if found, check if they 'trust' Amazon, else ask them to add DNS records that specifically allow for this. 
- Details ...
set export MOCK_AMPLIFY_DOMAIN_ASSOCIATION_CALLS="true" and add this in server.js
```
const formResponses = [
{
submissionId: "",
requesterEmail: "kishore@open.gov.sg",
repoName: "kishore-test",
primaryDomain: "isomer.gov.sg",
redirectionDomain: "www.isomer.gov.sg",
agencyEmail: "kishore@open.gov.sg",
},
{
submissionId: "",
requesterEmail: "kishore@open.gov.sg",
repoName: …
```
> fix(sl): warn ops regarding CAA records

- src/database/config.js
logging damn noisy, and the logging doesnt show the actual arguments anyways. maybe a better design is to allow this for prod, but I have never used these statements for production logging, and to be honest, most of the time it has hindered my ability to debug becasue this has been pure noise. 
I can actually see my console.logs now without scrolling infinitely
> feat(logging): remove logging

- src/routes/formsg/formsgSiteLaunch.ts
- src/services/infra/InfraService.ts
Currently our better uptime is done on create, but it should be on success instead. 
shifting the creation of this to post success, not during the launch process. 
- Details ...
Tests
> fix(betterUptime): make better uptime on success

- .github/workflows/ci.yml
- .github/workflows/deploy_staging.yml
we previously deployed to ecs on push to the `staging` branch. this PR swaps it back as efs has issues mounting onto a separate vpc. 
swap out `ci.yml` changes
> fix(ci): reverts ci changes to allow staging updates

- src/services/utilServices/SendDNSRecordEmailClient.ts
Both CAA records are tagged "issue", but one of them should be "issuewild".
**Bug Fixes**:
- Changed the tag for one of the CAA records to be "issuewild"
*None*
> fix(sl): include issuewild if CAA records are needed

- src/routes/v2/authenticated/review.ts
When a user is creating a new review request, we also try to obtain the diff between the staging and master branches. However, the logic requires a valid review request to be present, which may not be the case when the user is in the midst of creating one.
**Bug Fixes**:
- For the time being, there is no reason for us to know if the review request is present, as we are only comparing between the staging and master branches. Hence, we can skip the check for the existence of the review request.
- This is important when creating a new review request, as the review request ID is not present.
*None*
> fix(rr): skip checking the existence of review request for blob

- src/services/db/GitFileSystemService.ts
We get a lot of false positives on git push failures which is affecting on-call productivity. 
Closes IS-847
we should log only when git push is a complete failure (i.e. after 3 tries)
- Details ...
- On first 2 push failures, it should log differently from the third try
- To test, we might need to simulate a divergence in EFS vs GH states
- Perform edits on GH for a repo that is currently on EFS
- Go to CMS now and perform some edits. These edits cannot be push due to the divergence
- Check the logs to ensure that only the third try and error case prints out the actual Git error (i.e. should read like `error: failed to push some refs .......` )
> fix: remove unnecessary push logs

- docs/gigDnsApi.yaml
Closes [IS-812](https://isomeropengov.atlassian.net/browse/IS-812?atlOrigin=eyJpIjoiZWNiNzI1ZDNmZjEwNDM0YmIyODM5MjcxZDU5YWE4MDQiLCJwIjoiaiJ9)
The GIG DNS API swagger doc is outdated with a few new incoming requirements from GIG team. 
Updated the API swagger doc to reflect the latest requirements from GIG team: 
- Added `PUT` call to the API suite for updating DNS records 
- Added an optional field `rootDomain` to `PUT` and `POST` calls in the request body
- Added an optional query parameter `rootDomain` and a required parameter `email` to `DELETE` call 
- Details ...
- Updated the API swagger doc to reflect the latest requirements from GIG team. 
**AFTER**:
- The swagger file can be loaded manually on [swagger.io ](https://editor.swagger.io/)
- The …
> ref(doc): updated GIG DNS API swagger doc

- src/routes/formsg/formsgGGsRepair.ts
- src/services/identity/ReposService.ts
This PR adjusts our site repair form to copy from the existing staging branch when repairing staging-lite, instead of using `git clone`, which is slower due to the additional network call.
> chore: copy instead of clone

- .github/workflows/ci.yml
- .github/workflows/deploy_prod.yml
We have no workflow that deploys to production now. We require a new workflow to push to both ecs and eb (so that deployment for be consistent across both)
Add a new `deploy_prod` workflow that does the deploy to ecs/ecr
update `ci.yml` so that it uses a new job to run the above workflow. we do this instead of just invoking hte new workflow directly cos they have the same trigger (push) so it might fail if both `ci + deploy_prod` ran tgt
> feat(deploy-prod): add step to `ci.yml` to deploy to production

- src/constants/constants.ts
- src/routes/v2/authenticatedSites/__tests__/Homepage.spec.js
- src/routes/v2/authenticatedSites/homepage.js
- src/validators/RequestSchema.js
Our homepage frontmatter is not validated strictly.
**Features**:
- Added homepage frontmatter validation. The information about the constraints are obtained from:
- Static code analysis of the homepage components on the [isomerpages-template repo](https://github.com/isomerpages/isomerpages-template/tree/next-gen).
- Observation on optional/required fields directly on the CMS.
- Experimentation with various combinations + actual user homepages.
*None*
> feat: add validation for homepage frontmatter

- src/errors/SiteCheckerError.ts
- src/services/review/RepoCheckerService.ts
- src/types/siteChecker.ts
this pr adds the core parsing and reporting logic for the site link checker. 
high level algo 
1. grabs all images and files path 
2. parses all `.md` files and grabs a list of permalinks
3. if any duplicate permalinks are found, output to logs
4. parses all `.md` files and takes the content and convert everything to html.
5. parse the html code to get instances of `img` and `a` elements, and checks if the referenced path are all ok. 
6. outputs the list of incorrect referenced path to logs
- Details ...
add this in server.js to see the link checker run in the repo 
```
console.log("repoCheckerService")
const repoCheckerService = new RepoCheckerService()
const result = repoCheckerService.checkRepo("<name-of-repo>")
console.log("result") …
```
> core parser logic

- Dockerfile
- package.json
right now, we run the same command for start across all our environments. this PR adds a different start command **by environment**
1. utilise the fact that `CMD` is ran as the entrypoint **at run-time**. this means that env vars will be available 
2. create different commands for start **by environment** and use the env-var to differentiate
3. due to variable expansion, the command will be transformed from `start:ecs:$ENV_TYPE` into `start:ecs:dev/prod/staging`.
**NOTE: UNTESTED PR, TEST ON STAGING PRIOR TO MERGE**
> fix(start-commands): update commands to be different by env

- Dockerfile
- scripts/02_fetch_ssh_keys.sh
- scripts/03_add_keys_to_ssh_config.sh
- scripts/04_add_github_to_known_hosts.sh
The ECS tasks are running the web application as root, which causes permission issues on EFS when co-existing with the EB instances.
**Bug Fixes**:
- Ensure that we execute the docker container as the webapp user.
> fix(docker): ensure that the app runs with webapp

- .aws/deploy/backend-task-definition.prod.json
- .aws/deploy/backend-task-definition.staging.json
- src/integration/Sites.spec.ts
- src/routes/v2/authenticated/__tests__/Sites.spec.ts
- src/routes/v2/authenticated/index.js
- src/routes/v2/authenticated/sites.ts
- src/server.js
- src/services/review/RepoCheckerService.ts
- src/types/siteChecker.ts
adding backend routes to allow for site checker to be done via the fe. corresponding fe pr will be up soon
hooking up existing func call done for form sg into a route to be called form fe.  gb will be introduced in the fe so as to not introduce 4xx errors. this is not private info anyways, dont really care if an agency is able to view their own site's broken links just by querying this path. 
a locking pattern is added to prevent multiple runs of the same repo state that might use unnecessary compute. 
there are two main api calls, a checker and a result getter. the front end will be call the checker through a manual button for now, (this is user triggered). the getter will be called once every 10 seconds. (or window refetch i dont have a strong opinion here). …
> feat(routes): add link checker routes

- .env.test
- package-lock.json
- package.json
- src/integration/Users.spec.ts
- src/services/utilServices/MailClient.ts
- src/services/utilServices/__tests__/MailClient.spec.ts
The current mail sending functionality does not support adding of attachments to the email.
**Features**:
- Use `form-data` to craft the message object and also allow for inserting of files as attachments.
- Adjust email from address to `donotreply@isomer.gov.sg`, which is required for sending emails with attachments.
- `form-data` : Package for handling multipart form data requests
**Other deploy steps**
> feat(mail): support sending emails with attachments

- src/routes/formsg/formsgGGsRepair.ts
- src/services/identity/ReposService.ts
This reverts commit d25129cd41e0b19a1b5e6a34ffeb9802ca565f11. We were facing issues when repairing large repos, possibly due to memory issues - this PR reverts to git clone for slightly slower operations but allowing it to work for large repos again.
Note that we should also monitor CPU utilisation when running the site repair form for large sites - we were previously facing issues on this when using `cp`
> chore: revert to copy instead of clone

- src/config/config.ts
- src/server.js
- src/services/utilServices/RateLimiter.ts
- src/utils/jwt-utils.js
Our rate limiter is implemented wrongly. Couple of problems exist:
1. careless conversion of units. the unit of env var was already ms, but the code assumes it is in s instead. for clarity, renaming the env var from `tokenExpiry` to `tokenExpiryInMs`
2.  We are currently trusting proxy, where we trust the proxy to expose the client ip. The [documentation](https://expressjs.com/en/guide/behind-proxies.html) states that 
> When setting to true, it is important to ensure that the last reverse proxy trusted is removing/overwriting all of the following HTTP headers: X-Forwarded-For, X-Forwarded-Host, and X-Forwarded-Proto otherwise it may be possible for the client to provide any value.
This is not entirely true from reading the Cloudflare's …
> fix(rateLimiter): correct rate limits

- src/integration/Sites.spec.ts
- src/routes/v2/authenticated/sites.ts
- src/server.js
- src/services/fileServices/MdPageServices/PageService.ts
- src/services/review/RepoCheckerService.ts
- src/services/review/__tests__/ReviewRequestService.spec.ts
Users have given feedback regarding link checker. 
1. Decoding issues 
The repo had the file 
`/images/Life @ JPJC/2023 Events/LTC2023/ltc photo 1.JPG`
User had sourced this in one of their pages using the path `/images/Life%20%40%20JPJC/2023%20Events/LTC2023/ltc%20photo%201.JPG`
In the live site, this is a vaild link.
When running 
```
const uri = '/images/Life%20%40%20JPJC/2023%20Events/LTC2023/ltc%20photo%201.JPG';
console.log(decodeURIComponent(uri));
console.log(decodeURI(uri));
```
we get the result 
```
> "/images/Life @ JPJC/2023 Events/LTC2023/ltc photo 1.JPG"
> "/images/Life %40 JPJC/2023 Events/LTC2023/ltc photo 1.JPG"
```
which is expected as the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI#decodeuri_vs._decodeuricom …
> fix(linkChecker): bug fixes

- docker-compose.dev.yml
- package.json
- src/errors/RouteNotFoundError.ts
- src/middleware/catchNonExistentRouteHandler.ts
- src/routes/v2/authenticatedSites/__tests__/Media.spec.ts
- src/routes/v2/authenticatedSites/media.ts
We had an issue where a request such as "media/images%20blah/pages"  timeing out, see incident [here](https://opengovproducts.slack.com/archives/CK68JNFHR/p1708651983715799). while we do have an overall catch all in our main router, there are quite a number of calls in our subrouter that fails. 
for the media subrouter, this should return a 404. this is not applied across all the routes as some of the routes depend on the fall through behaviour to function. therefore, this pr is only scoped to return only for the media subrouter 
1. adding a `next()` to every subrouter 
2. adding an error handler to every subrouter such that if subrouter captures a group and does not handle it, an error should be thrown. unfortunately, this caused quite a number of functionality to break, rather this …
> fix(api): fix media route timeout

- src/config/config.ts
- src/server.js
- src/services/utilServices/RateLimiter.ts
- src/utils/jwt-utils.js
Reverts isomerpages/isomercms-backend#1183 - errors on login that occur specifically for staging/prod envs
> Revert "fix(rateLimiter): correct rate limits"

- src/integration/Users.spec.ts
- src/routes/v2/authenticated/users.ts
- src/services/identity/UsersService.ts
- src/services/utilServices/AuthService.js
- src/services/utilServices/__tests__/AuthService.spec.js
The update operation on the number of attempts for each OTP is subject to race conditions, which causes the value to be overwritten when many requests are made simultaneously.
**Bug Fixes**:
- Use [sequelize's increment operation](https://sequelize.org/docs/v6/core-concepts/model-instances/#incrementing-and-decrementing-integer-values) instead of update, which is done on the database itself and does not run into concurrency issues.
- Use transactions to lock the row from further updates.
*None*
> fix(otp): increment instead of update for concurrency

- src/config/config.ts
- src/server.js
- src/services/utilServices/RateLimiter.ts
- src/utils/jwt-utils.js
There was an issue with  #1183 due to the removal of the 
`trust proxy` setting in express. There are two packages that rely on express apis,  `express-rate-limit` and `express-session`. due to changes in the way we used `express-rate-limit`, I thought that this setting can be removed, and this was only done with the intention of a cleanup and does not affect the functionality of how we are currently using `express-rate-limit`.
The [documentation](https://github.com/expressjs/session?tab=readme-ov-file#cookiesecure) for `express-session` also states that:
>  If secure is set, and you access your site over HTTP, the cookie will not be set. If you have your node.js behind a proxy and are using secure: true, you need to set "trust proxy" in express
Checking in with the vapt folks to sense …
> fix(autoLogoutIssue): failing whoami

- src/routes/v2/auth.js
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> fix(otp): unwrap ResultAsync value

- src/routes/v2/__tests__/Auth.spec.js
- src/services/db/__tests__/GitFileSystemService.spec.ts
The Auth test is failing due to a change in the return type.
**Bug Fixes**:
- Fixed the return type of the mock implementation.
- Also removed an extra console.log to avoid flooding the terminal.
No tests, just make sure CI passes.
_None_
> tests: fix failing auth test

- src/services/admin/AuditLogsService.ts
- src/services/admin/__tests__/AuditLogsService.spec.ts
- src/types/auditLog.ts
The CSV file is very limiting and is very difficult for users to tell exactly what changed from the commit message.
**Features**:
- Add a link to the relevant GitHub item (either commit or PR) for users to find out more information about the individual audit log items.
- Also added some basic unit tests for some of the supporting functionality. The core functionality remains untested as it is still subject to change.
_None_
> feat(auditlogs): add relevant GitHub link for each audit log entry

- src/services/api/AxiosInstance.ts
we were setting the tags for the trace as a **bootstrap** process. this means that the `tracer.init` call does not bootstrap properly (as `tracer.use` is meant to be called at start-up, **prior** to actual tracing). 
this PR changes it so that the tags are set on the span.
1. instead of calling `tracer.use`, which is a bootstrap call, change to get the active span and calling `setTag` on that span.
> fix(tracer): fix tag setting on span

- package-lock.json
- package.json
- src/logger/console.logger.ts
- src/logger/constants.ts
- src/logger/logger.ts
- src/logger/pino.logger.ts
- src/routes/formsg/formsgGGsRepair.ts
- src/utils/tracer.ts
this pr adds a structured logging library (`pino`) to our codebase. it also supersedes `winston` (which hasn't been working anyway).
Closes [ISOM-772]
1. add both `pino` and `pino-pretty` (will be described below) 
2. replaced `consoleLogger` implementation with a call to `pino` with transport as `pino-pretty`. `pino` pipes logs **by default** to `stdout`. this means that on local, the logs get transformed by `pino-pretty` before going to `stdout`, so it'll be seen as unstructured text instead of json. 
3. for production loggers, we **also pipe to `stdout`** - this gets picked up by aws and forwarded to the correct log group. **this is actually how logging works now** - our `winston` logger has been missing a `transport` and broken since forever. this was also chosen **over** using …
> feat(pino): add logger

- src/config/config.ts
- src/constants/constants.ts
- src/services/identity/LaunchesService.ts
- src/services/infra/InfraService.ts
- src/services/utilServices/SendDNSRecordEmailClient.ts
- src/types/siteLaunch.ts
ops has been doing this manually, we want to add this as part of sl process for a more resilient redirection service
add in the two records
this also changes the shape of the site launch message, this has been updated in the infra pr [here](https://github.com/isomerpages/isomer-infra/pull/66) 
- Details ...
- Details ...
**BEFORE**:
**AFTER**:
```
const formResponses = [
{
submissionId: "",
requesterEmail: "kishore@open.gov.sg",
repoName: "kishore-test",
primaryDomain: "yahoo.com",
redirectionDomain: "isomer.gov.sg",
agencyEmail: "kishore@open.gov.sg",
},
]
formsgSiteLaunchRouter.handleSiteLaunchResults(formResponses, "test")
```
> fix(redir): add in other 2 records

- src/utils/tracer.ts
We have no view on nodejs runtime metrics to see garbage collection lock and event loop lag (which could totally be happening with sync IO operation for fs/git). datadog can report that data for us.
See [documentation](https://docs.datadoghq.com/tracing/metrics/runtime_metrics/nodejs/?tab=environmentvariables#data-collected)
Enable `runtimeMetrics:true` for dd-trace
Additional monitoring could cause additional cpu load. Instances should be monitored carefully on release.
> chore(telemetry): report runtime metrics

- src/services/db/GitFileCommitService.ts
we lack observability here. we experienced a silent failure in terms of divergence, and not a clue on how to debug since we cannot replicate this + no unusual errors around that time. 
this is a last ditch effort to see if we can get more info on this issue, but personally am not too optimistic about this pr since by right the top level handlers should log errors
> chore(commitService): add logging

- src/services/identity/ReposService.ts
- src/services/review/RepoCheckerService.ts
- src/services/utilServices/MailClient.ts
- src/utils/fs-utils.ts
We have quite a number of blocking I/O calls that has lead to unwanted CPU spikes in the event pool thread. 
This PR scrapes any existence of I/O calls and ensures that there is no lingering sync fs calls made from node. 
use `fs.promises` instead
Looking at the spike after running the site checker
- Details ...
**Features**:
when running the site repair form:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
```
grep -rE '(accessSync|appendFileSync|chmodSync|chownSync|closeSync|copyFileSync|cpSync|existsSync|fchmodSync|fchownSync|fdatasyncSync|fstatSync|fsyncSync|ftruncateSync|futimesSync|lchmodSync|lchownSync|lutimesSync|linkSync|lstatSync|mkdirSync|mkdtempSync|opendirSync|openSync|readdirSync|readFileSync|readlinkSync| …
```
> perf(I/O): rm blocking fs calls

- .aws/deploy/backend-task-definition.prod.json
- .aws/deploy/backend-task-definition.staging.json
previously, we updated env tags for `production` to `prod` but turns out it's being used in more than a few places. just change back to `production` + tag properly on docker labels also
1. change container/run-time tags to `production` 
2. update docker labels
> fix(tags): update tagging for dd

- src/services/review/RepoCheckerService.ts
when pages are empty, we currently throw a link checker error which trips up alarms 
it is ok for a page content to be empty (eg, newly created page)
remove the existing errors being reported
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> fix(link checker): wrong error reported

- package.json
previously we were using `bash` to run the release script, which might not be obvious. this changes the release script to be invoked via `npm`
alias old command to script
> chore(package): use npm

- Dockerfile
https://www.notion.so/opengov/2024-03-27-careers-gov-sg-misconfiguration-15469dbae95942588574db9d8e819177?pvs=4#c009bcd4e261452289d0d74463b37cb9
https://linear.app/ogp/issue/ISOM-881/add-dig-to-image-for-backend
add `bind-tools` (`dig` + `nslookup` is part of this)
> fix(dockerfile): add dig to image

- src/services/db/GitFileSystemService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
To get the last commit, we issue a full `git log` command which can returns and parse thousands of lines and commits. 
Some sites have a HUGE amount of commits (e.g. `nlb-biblioasia` which has over 50k commits!)
```bash
git log | grep 'commit ' | wc -l
```
Use the arg `--max-count=1` to restrict resultset to just one commit when fetching the last commit 😑 🤷 
Assuming you have `nlb-biblioasia` locally (peer of your isomercms checkout), run this script to show the difference between the 2
```javascript
const SimpleGit = require("simple-git")
const git = SimpleGit()
const ITERATIONS = 20;
async function run() {
// prime FS cache if needed
await git.cwd('../nlb-biblioasia').log(['staging']);
let startTs, latest;
startTs = Date.now();
for (let idx=ITERATIONS; idx--; ) {
latest = (await …
```
> fix: reduce log size to just last commit

- src/middleware/routeHandler.ts
Currently, we are releasing the lock before the promise gets resolved, which then leads to the lock becoming effectively useless as it does not guarantee that each mutation on the repo is isolated from one another. This would prob lead to more users complaining that there are concurrent editors, but there might be further optimisations that could be done to reduce the frequency of this. 
dont release lock early
- Details ...
**BEFORE**:
**AFTER**:
[ ] Go into any site and perform CRUD operations on a page level for a repo in efs.
> fix(lock): fix early release of lock

- src/validators/RequestSchema.js
currently we have some agencies that use external links for their navbar. this brings back the backward compat with those agencies. 
for more context, refer [here](https://opengovproducts.slack.com/archives/CK68JNFHR/p1711596585315799) 
@seaerchin am adding another key, looks ugly but is affecting prod sites as of right now. let me know if you have concerns regarding this
> fix(navbar): allow ext links

- src/services/infra/StatsService.ts
- src/services/review/ReviewRequestService.ts
- src/services/review/__tests__/ReviewRequestService.spec.ts
`computeShaMappings()` does one query `this.users.findByPk(userId)` for each author of all commits on the review. All the DB queries are issued in parallel. For large changeset with many commits, we expect the set of authors to be less than the number of commits, and so the process sometimes issues many redundant queries in parallel.
Goal: reduce the number of queries to the minimum required.
* From the list of commits, identify the sets of unique authors
* Fetch author data in parallel as before on that minimized set
* Generate the mappings from the author data
TODO:
* ~~The same inefficient process of blindly retrieving user details (possibly with redundant calls) exist for `computeCommentData()`, the same fix should be done there as well.~~ DONE!
* We could …
> ISOM-824 feat: don't fetch redundant author info from db

- src/middleware/routeHandler.ts
For write routes, the site lock is released too early, which makes the lock useless
This is a sibling PR to https://github.com/isomerpages/isomercms-backend/pull/1256, which introduced the same fix for the rollback routes.
Only release the lock AFTER the action for the handler is completed. 
Notes:
1. For this to work (same a rollback routes), there is an assumption that ALL write route handlers are async and resolve when their job is done, but that is NOT enforced from typings. The handler is of type `RequestHandler` which is not specified to return a `Promise`, it returns `void`.
2. The handling of the express flow still looks wrong and should be discussed. When the handler is successful, and the lock fails to release, does it really make sense to call `next(err)`? The query was handled …
> fix: only release the lock after the handler is done

- src/middleware/routeHandler.ts
APM traces do not show the name of the handlers because they are wrapped by anonymous functions
sample trace [here](https://ogp.datadoghq.com/apm/trace/4623130037215300159?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=2269893028902401593&spanViewType=metadata&timeHint=1712017202477&view=spans)
Note: The PR changes indentations, watch the changeset with the ignore whitespace setting on. [Direct link here](https://github.com/isomerpages/isomercms-backend/pull/1260/files?w=1).
Carry the name of the wrapped function onto the wrapper.
Function names are typically read-only, so we must use [`Object. defineProperty()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) to set the name.
> feat: carry the name of the wrapped handler

- src/server.js
something in me wanted to check if we indeed exit if we fail to connect to db, and the answer is... no 
[node.js](https://nodejs.org/docs/latest-v18.x/api/process.html#processexitcode_1) states that 
> A number which will be the process exit code, when the process either exits gracefully, or is exited via process.exit() without specifying a code.
so it does not actually do the exiting, which leads to silent failures
> fix(server): server should die if unable to connect to db

- src/services/identity/NotificationsService.ts
Creating a review request can create a lot of notification, where the prelim search is very expensive. See [sample trace here](https://ogp.datadoghq.com/apm/trace/1838468539673357242?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=4348314207189470064&spanViewType=metadata&timeHint=1712136769385&view=spans), screenshotted below for reference:
The search query does an unnecessary join on the site table. The join is not needed since the site id is already known.
TODO: Remove unnecessary join
Note that even on much smaller traces, not at peak time (~9pm), the pattern of having the selects take much longer than the insert/updates hold. Here is [another sample trace](https://ogp.datadoghq.com/apm/trace/8161601024562039339?colorBy=service&env=production& …
> fix: remove unnecessary join and site retrieval

- src/middleware/routeHandler.ts
- src/routes/formsg/formsgSiteCreation.ts
- src/routes/formsg/formsgSiteLaunch.ts
- src/routes/v2/authenticated/collaborators.ts
- src/routes/v2/authenticated/notifications.ts
- src/routes/v2/authenticated/review.ts
- src/routes/v2/authenticated/sites.ts
- src/routes/v2/authenticated/users.ts
- src/routes/v2/authenticatedSites/media.ts
- src/routes/v2/authenticatedSites/repoManagement.ts
- src/routes/v2/sgidAuth.ts
- src/utils/apm-utils.ts
We have a lot of spans in APM traces which are `<anonymous>`. While not a deal breaker to get value out of APM, it is annoying.
The anonymous functions are due to the way some methods are declared in classes, which is done to be able to specify types.
e.g. in [`ReviewsRouter.ts`](https://github.com/isomerpages/isomercms-backend/blob/develop/src/routes/v2/authenticated/review.ts#L92-L100), the assignment syntax creates anonymous methods
```typescript
compareDiff: RequestHandler<
{ siteName: string },
{ items: EditedItemDto[] } | ResponseErrorBody,
unknown,
unknown,
{ userWithSiteSessionData: UserWithSiteSessionData }
> = async (req, res) => {
// ... 
}
```
while in [`collectionPages.js`](https://github.com/isomerpages/isomercms-backend/blob/develop/src/routes/v2/authenticatedSites/collectio …
> Improve APM spans (no more <anonymous>)

- src/validators/RequestSchema.js
This PR adds an additional allowance for legacy nav bars to have an `external` field for top level navs (e.g. 
```
- title: News
url: https://www.mlaw.gov.sg/news/
external: true
```
Related to https://github.com/isomerpages/isomercms-backend/pull/1250
> fix: external links in top level nav

- src/database/migrations/20240405132731-add-notification-indexes.js
Our notifications table is large, and we run frequent SELECT queries on it, but postgres does not automatically index foreign key columns, so WHERE clauses on these columns will require a full table scan, which results in inefficient db queries. This PR adds indexes to the foreign keys in the notifications table to speed up our queries.
Note that `site_id` is only indexed with `user_id`, since we never filter by `site_id` alone.
- Run migration on staging and master before merge
> chore: index notifications table

- .github/mergify.yml
see [here](https://github.com/isomerpages/isomercms-frontend/pull/1865)
see [here](https://github.com/isomerpages/isomercms-frontend/pull/1865)
> chore(ci): enhance mergify

- .github/mergify.yml
merged previous mergify PR but managed to paste wrongly -> this resulted in **all non sem-ver minor** PRs up being merged.
this is 
1. [PR](https://github.com/isomerpages/isomercms-backend/commit/08ec28a66a954863135fa651ac3d338d1898ca7f) for `base-64` (we don't use this - maybe can remove) 
2. [PR](https://github.com/isomerpages/isomercms-backend/commit/a06afdddea52fa87124ec07ff228b0c4f6e8ec96) for `marked` -> we **do use this**! however, the change is to update `marked` to conform to changes in the markdown spec (to resolve ambiguity...)
- change rule from `minor` -> `major`
- looked at marked's 12.0 update [here](https://github.com/markedjs/marked/releases/tag/v12.0.0); ss attached below for convenience; as most of the changes are helpful to us (we only call `marked.parse`), i'm **not** …
> fix(mergify): fix copy/paste mistake

- .aws/deploy/backend-task-definition.staging.json
- .github/workflows/aws_deploy.yml
https://linear.app/ogp/issue/ISOM-884/add-github-source-code-linkage-on-dd
Closes ISOM-884
1. add required env vars into the task def **on the app container**
a. tried adding on dd container initially - didn't work
3. inject the required env vars via `sed` during the workflow
- Details ...
- check the page [here](https://linear.app/ogp/issue/ISOM-884/add-github-source-code-linkage-on-dd) post deployment of this PR to staging. 
- the linkage should be **green** for `service:isomer, env:staging, version:0.77`
> feat(dd): add source code linkage

- src/middleware/authorization.ts
The Auth middlewares are not named correctly:
Example trace:
[Trace link for reference](https://ogp.datadoghq.com/apm/trace/3862022928270485881?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=6340181816854815641&spanViewType=metadata&timeHint=1712392136957&view=spans)
Use the method namer introduced in [this PR](https://github.com/isomerpages/isomercms-backend/pull/1267)
> fix: name auth routers

- src/middleware/errorHandler.js
Resolves ISOM-916. Previously, our catch-all error handler was using `logger.info`, which meant that unrecognised/unhandled errors were being tagged as info in datadog. This PR modifies them to use `logger.error` instead.
> chore: change error handler to use logger.error

- src/services/identity/UsersService.ts
- src/services/identity/__tests__/UsersService.spec.ts
Incorrect comments on not being able to use `findOrCreate()` with a transaction.
(Also I think the old code for create might have been incorrect, because the first argument to `create()` must be an object, not a string (?) 🤔 
While `.findOrCreate()` does in fact accept a transaction (see [API documentation](https://sequelize.org/api/v6/class/src/model.js~model#static-method-findOrCreate)), I think the update to `lastLoggedIn` doesn't need to be in the transaction. Even if there is a conflict with multiple writes overwriting each other, the updates would be so close by that's the inaccuracy is not business critical.
Because of that, we can simplify the code by using the default transaction behaviour of `.findOrCreate()`, instead of providing our own transaction.
1. Use `.findOrCreate()` in …
> refactor(UserService): simplify login by using findOrCreate()

- src/services/identity/UsersService.ts
The code for `sendEmailOtp()` and `sendSmsOtp()` have a behaviour of find-then-create-or-update. However that not done in a transaction, and is not sync-safe.
Sequelize has `findOrCreate()` which does create transaction by default, so we can just use that instead. 
Additionally the method `createOtpEntry()` is not very useful since there are 2 code path which are conditional on the otp types, and these are already distinct in the methods `sendEmailOtp()` and `sendSmsOtp()` themselves.
Also there was one possible issue (not sure): The 2 OTP methods did not have the same behaviour to reset the OTP expiry (only the email OTP would reset the expiry). I'm not sure if it's on purpose or not, so it's worth having someone commenting on it. I'll start a thread in the PR to indicate the potential …
> refactor(OTP): simplify code by using upsert() 

- src/routes/formsg/formsgSiteAuditLogs.ts
The month number has an off-by-one error as it is zero-indexed, which means for April, `getMonth()` will return `3` instead of `4`.
**Bug Fixes**:
- Fix the off-by-one error so that invalid dates (such as `2024-02-31` is not being produced erroneously).
*None*
> fix: off-by-one error for month number

- src/services/identity/UsersService.ts
- src/services/identity/__tests__/UsersService.spec.ts
We have a whitelist of domains and specific allowed emails in DB. Before we allow a OTP to be sent to an email, we check against the whitelist if the input email is allowed.
The way this is done is to fetch the entire table content (with a slight filter for expiry) and do a match in code 😑 
It would be much more efficient to use the database query capabilities to run the match on the DB directly. We can expect that to be both faster and transfer much less data.
Run a raw efficient query to return an easy yes/no state on whether an email matches an entry in the whitelist.
We can not use the ORM capability because we are not matching a cell value to some input. Instead we are matching the input against the cell value with a `endsWith` behaviour. This is done by using the `<input> like …
> fix(canSendEmailOtp): use a query to find whitelist match, rather than fetching the whole table

- .aws/deploy/backend-task-definition.prod.json
- .aws/deploy/backend-task-definition.staging.json
- .aws/deploy/support-task-definition.prod.json
- .aws/deploy/support-task-definition.staging.json
- .github/workflows/deploy_prod.yml
**NOTE: DO NOT MERGE, PENDING INFRA DEPLOY**
This adds in the missing deployment files for our support ecs service **on production**. this is raised as a separate PR so we can go through these 2 files in excruciating detail. the base PR is #1269.
For reviewers, please help to crosscheck against what i did below for env vars + deployment workflow to make sure i haven't missed anything
- create a new task definition for `support` for deployment to production. 
- update our existing `deploy_prod` workflow to have a step to deploy the support ecs service.
for verification, these are the steps that i took: 
**task def**
- copied over the existing `support-task-def` for `staging` to `production` 
- thereafter, i **deleted** the `secrets` section and replaced it with the one for …
> ci(sidecar): add deploy files for prod

- Dockerfile
- Details ...
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
**AFTER**:
> fix(dockerfile): revert to copy . . 

- src/services/db/GitFileSystemService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
Described in linear: 
missing media files in pages leads to a 5xx when the resource name itself cannot be processed
as an example, consider a link (some_link)[/%2fa/b] -> this resolves to //a/b, which is not processable by our backend as it results in an error like so: Error when getting Git blob hash: Error: HEAD:images/technews//tvws-part2.JPG  and in turn causes a 5xx. 
this 5xx is caused because GitFileService (iirc) will try to determine the blob hash (see if can find the file on disk) and in doing so, it will get an error (as the file doesn't exist), leading to the 500.  
see here for an example where this occurs
in order to reproduce this: 
Additionally, we also see a `fatal: path '.git' does not exist in 'HEAD'` in the logs every time the workspace is refreshed. 
This is because …
> fix(5xx): should return 4xx when file not found

- .aws/deploy/support-task-definition.prod.json
- .aws/deploy/support-task-definition.staging.json
There was an error with the production deployment - the task role specified in the task definition is the `staging` task role and leads to the `support` service not having sufficient perms in `prod`. 
1. update task role to `prod` 
2. update dd log group for `support` for both staging + prod to avoid conflicts with existing `backend` log group. (note that this is dd internals and not app stuff - we don't need this but just for clarity)
> fix(task def): update log groups for support + role for prod

- src/integration/Users.spec.ts
- src/services/identity/UsersService.ts
- src/services/identity/__tests__/UsersService.spec.ts
`UserService.canSendEmailOtp()` uses a whitelist to determine if emails are allowed to receive OTPs.
The whitelist contains
1) domains that the input can be matched against by suffix match
2) full email that the input can be matched again with exact match
At the moment the code basically download the full content of the whitelist table, and does a filter and check in code locally. 
It would be much better to leverage the query capability of the DB, to ask if a whitelist entry exists and get a small yes/no type result.
Replace app-level code filtering by a single DB query.
The DB query will return: either:
* the first whitelist entry that matches
* nothing if there is no match
The PR will log the whitelist match, so we can verify if anything is wrong.
[Sample …
> Feat: Optimize canSendEmailOtp

- .aws/deploy/support-task-definition.prod.json
- .aws/deploy/support-task-definition.staging.json
The log group was previously renamed to `prod-support/ecs/dd-agent` and `stg-support/ecs/dd-agent` for prod and staging respectively, but these log groups were not yet created via Pulumi, causing the deployments for the support service to fail.
**Bug Fixes**:
- Temporarily revert the log group back to the old log group (which already existed) until the new log group is correctly created on isomer-infra.
*None*
> fix: revert log group to isomer-infra

- src/middleware/traceUser.ts
- src/server.ts
We do not have the user information in traces. Since DataDog offers [an API](https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md#user-identification) to track the user, we should use the capability.
Use the [dd-trace setUser() API ](https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md#user-identification) to populate user id in traces.
This is done in a middleware that will run right after the session middleware, so we can report whatever user is in session.
Should we track the user email and github id in traces as well? (basically the entire content of the session's UserInfo object ?) Working with emails make its faster for us to identify people, but is that a privacy concern? (potentially not since we also have a lot of emails in logs?)
Verified working on staging: …
> ISOM-942: add user info to traces

- src/services/fileServices/MdPageServices/MediaFileService.js
- src/utils/file-upload-utils.js
CloudMersiove is supposed to return 200 for all scan calls, and the response body will indicate if the media contains viruses or not. 
Unfortunately, we see instances where CloudMersive returns a 400, which means it is OUR error, since we are the one who make the call (it's not a client error). Our app correctly returns 500 when this happens because the 400 responses are not expected.
Unfortunately, our logging for CloudMersive errors only contains the http status message like so:
> Error when calling Cloudmersive Virus Scan API: Bad Request
Which is not enough information for us to troubleshoot what about the request is wrong (e.g. a rate limit error? a body error? etc.)
[Sample trace here](https://ogp.datadoghq.com/apm/trace/8271674638636057839?colorBy=service&env=production&graphType=fl …
> ISOM-951: Better cloudmersive logging

- src/services/identity/__tests__/CollaboratorsService.spec.ts
This PR fixes tests which were broken by #1324.
> fix: collaborators test

- .github/mergify.yml
Previously we used `snyk-bot` but now it is `isomeradmin`
Change `author` to `isomeradmin`
> fix(mergify): update as snyk now uses isomeradmin

- package-lock.json
- package.json
- src/middleware/featureFlag.ts
- src/utils/growthbook-utils.ts
Using `autorefresh:true` in `growthbook.loadFeatures()` is an anti pattern.
`autorefresh:true` [translates to a subscribe on the instance](https://github.com/growthbook/growthbook/blob/v2.0.0/packages/sdk-js/src/GrowthBook.ts#L115-L122), which means the flags may be updated during the lifetime of a request.
In recent version of growthbook, `autorefresh:true` [has been deprecated](https://github.com/growthbook/growthbook/blob/v2.8.0/packages/sdk-js/src/GrowthBook.ts#L155-L158) in favour of a more explicit constructor setting `subscribeToChanges:true`, with a documented behaviour warning for middlewares [in documentation](https://docs.growthbook.io/lib/js#nodejs):
```
// Important: make sure this is set to `false`, otherwise features may change in the middle of a request
subscribeToChanges: …
```
> chore(growthbook): handle refreshes at module level

- support/routes/v2/formsg/formsgSiteLaunch.ts
When there was no records that were found, dns:node throws an error. While we did handle it, there should have been an additional return statement to exit early rather than propagating into an error state. 
If the error is of type `ENODATA`, return early with some default values instead.
- Details ...
Locally enter these values into `support/routes/v2/formsg/index.ts`
```
formsgSiteLaunchRouter
.digAAAADomainRecords({
primaryDomainSource: "singaopreoae.sg",
} as SiteLaunchResult)
.then(console.log)
.catch(console.error)
formsgSiteLaunchRouter
.digCAADomainRecords({
primaryDomainSource: "singaopreoae.sg",
} as SiteLaunchResult)
.then(console.log)
.catch(console.error)
```
assert that the console log outputs 
This fix is meant to go into prod line asap
> fix(sitelaunch): do not throw for no dig results

- src/services/db/GitFileSystemService.ts
Some incidences of a divergence between EFS and GitHub recently occurred. In reality, we trust EFS as our source-of-truth. Hence, it makes sense for our to automatically recover from divergences by doing a force push to GitHub.
There still exists a case when Ops might edit on GitHub while site users are editing which can cause the pushes to override Ops' changes. For this, a solution will be to enable Ops to lock the repo -> perform the edit -> perform GGS repair using form + unlock affected repo automatically. For now, engs can manually add/remove the lock on DDB
Closes ISOM-947
On failure to git push, we retry twice. On the second retry, we use a git push --force option to forcefully push EFS commits to GitHub.
- Details ...
To simulate this on staging I created a …
> feat: git push force to github on second retry

- src/logger/logger.ts
- support/routes/v2/formsg/formsgSiteLaunch.ts
The existing statements does not print the error (since errors are not serializable) as mentioned [here](https://github.com/isomerpages/isomercms-backend/pull/1355#discussion_r1584027034)
In addition, we have not been using the child loggers as effectively as possible to provide the context needed to debug efficiently when errors arise. A obvious example is our constant noise of `Github API call made`, but we have no context surrounding that particular call being made.
To fix this issue, this pr introduces a small introduction of using child loggers, which has already been declared in our codebase by @seaerchin. A child logger is used to create a new logger instance that inherits all of its parent's metadata (e.g. logger name) and attach new metadata for all logs written by that child …
> chore(sitelaunch): better error message

- .env.test
- src/fixtures/review.ts
- src/services/db/GitFileSystemService.ts
- src/services/db/RepoService.ts
- src/services/db/__tests__/GitFileSystemService.spec.ts
- src/services/review/ReviewRequestService.ts
- src/services/review/__tests__/ReviewRequestService.spec.ts
Closes https://linear.app/ogp/issue/ISOM-833/benchmark-impact-of-local-git-diff-on-cpu-usage
Local diff was implemented a while back but kept behind a feature flag.
Feature flag has not been enabled in production due to concerns about performance especially for larger diffs.
**Everything below is in the context of motac2 with ~444 files changed in one RR**
[Trace for unoptimised implementation](https://ogp.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Astaging%20service%3A%2Aisomer%2A%20resource_name%3A%2Acompare%2A&agg_m=count&agg_m_source=base&agg_t=count&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=false&graphType=flamegraph&historicalData=false&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&s …
> feat: optimise local diff

- src/constants/constants.ts
- support/routes/v2/formsg/formsgSiteLaunch.ts
There was a bug in the implementation of #1355. This worked for sites that were already launched. Newer sites which do no resolve to any host name throws a `ENOTFOUND`, which should be an ok error.  
To fix this issue, we explicitly check for this error code as well to ensure that this does not error out. 
- Details ...
tldr; below we are testing for 
1. domains that have caa + aaaa record (google.com)
2. domains that dont resolve to a host name (dontexist.sg)
3. domains that do resolve to a host name but dont have an aaaa/caa record (isomer.gov.sg)
Locally enter these values into `support/routes/v2/formsg/index.ts`
```
formsgSiteLaunchRouter
.digAAAADomainRecords({
primaryDomainSource: "isomer.gov.sg",
} as SiteLaunchResult)
.then(console.log)
.catch(console.error) …
```
> fix(sl): fix error code

- .aws/deploy/backend-task-definition.staging.json
we only added source code integration to `production` but not to `staging`. 
this PR adds that in through the [required](https://docs.datadoghq.com/integrations/guide/source-code-integration/?tab=nodejs#tag-your-telemetry-with-git-information) env vars.
> fix: add git to dd for staging

- .aws/deploy/backend-task-definition.prod.json
- .aws/deploy/backend-task-definition.staging.json
- .github/workflows/aws_deploy.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_staging.yml
Closes ISOM-935.
**Features**:
- Adds the required labels for Datadog to monitor our RDS systems.
- Ref: https://docs.datadoghq.com/database_monitoring/setup_postgres/aurora?tab=docker#grant-the-agent-access
- Also adds `DD_DBM_PROPAGATION_MODE` env var to the app docker container.
- Ref: https://docs.datadoghq.com/database_monitoring/connect_dbm_and_apm/
_None_
> feat: add Datadog monitoring for RDS

- src/services/identity/SitesCacheService.ts
I don't think this PR solves the root cause, still an in depth discussion might be warranted. This is a fix regarding [incident](https://opengovproducts.slack.com/archives/C075J2VV5UK). 
To replicate this locally,  go to `SitesCacheService.ts` and modify the function `getAllRepoData()`
```
export async function getAllRepoData(
accessToken: string | undefined
): Promise<RepositoryData[]> {
console.log({ accessToken }) // this one is local dev hor dont push to production
// wait until time is a mutliple of 5 seconds
const now = Date.now()
const waitTime = 5000 - (now % 5000)
await new Promise((resolve) => setTimeout(resolve, waitTime))
const { repos: firstPageRepos, links } = await fetchPageOfRepositories({
accessToken,
page: 1,
getLinks: true,
})
console.log(firstPageRepos)
if …
```
> fix(cache): cached results on the same request

- src/services/identity/SitesService.ts
During debugging of the github login issue, a problem faced was determining whether the issue was internal (we using stale data) or external (github giving us stale data). 
If we had the list of sites returned, it would have helped us to troubleshoot this issue.
This PR logs the list of sites as well as an identifier for the user's id. no sensitive information is logged in our system here. i didn't log any further down (this is done at `SitesService`) because any further down (eg: `SitesCacheService`) discards the `userId`, which is required for user identification
> chore: log all sites retrieved

- src/constants/constants.ts
- src/types/dnsChecker.ts
- support/routes/v2/isobot/index.ts
- support/routes/v2/isobot/ops/botService.ts
The DNS checker Slackbot currently lives inside a lambda.
**Features**:
- Move the lambda function into the CMS support container.
- There's quite a bit of permutations on the possible states, so the code is a little jank. Open to suggestions on how we can improve it.
- Use the slash command `/stagingasjklasd` inside our Slack (this is connected to our staging instance)
- Verify the output for a few domains
*None*
> feat: move DNS checker slackbot from lambda

- .aws/deploy/support-task-definition.prod.json
- .aws/deploy/support-task-definition.staging.json
- package-lock.json
- package.json
- src/config/config.ts
- support/constants.ts
- support/index.ts
- support/routes/v2/index.ts
- support/routes/v2/isobot/index.ts
- support/routes/v2/isobot/ops/botService.ts
At present, we are using express' router for interfacing with slack, which is less ergonomic than using bolt. this is problematic because we want to offload some tasks from form -> slack bot, which might be more cumbersome using bolt.
Shift from using express to using `bolt` + `ExpressReceiver`. This simplifies code-flow abit, but note that there si some validation logic which isn't captured here but will be downstream
**NOTE:** This is untested at present
- go to SSM 
- search for `SLACK` 
- check that there are four secrets (2 tokens * 2 envs)
> ref(bot): use bolt for app

- package-lock.json
- package.json
laze to use snyk and keep rebasing + i want to try chat gpt's pr desc LOL
Bump versions for various AWS SDK dependencies from 3.575.0, 3.578.0, and 3.590.0 to 3.577.0.
- Updated @aws-sdk/client-amplify to 3.577.0
- Updated @aws-sdk/client-cloudwatch-logs to 3.577.0
- Updated @aws-sdk/client-dynamodb to 3.577.0
- Updated @aws-sdk/client-secrets-manager to 3.577.0
- Updated aws-sdk from 2.1619.0 to 2.1623.0
1. Run the build and ensure it completes successfully.
2. Perform regression testing to ensure existing functionality is not broken.
3. Verify that the updated AWS SDK clients are functioning as expected by executing sample API calls.
Keeping dependencies up-to-date helps ensure compatibility with AWS services, and may include important bug fixes and performance improvements.
---
> fix(deps): update AWS SDK JS dependencies to 3.577.0

- .github/workflows/ci.yml
- package-lock.json
- src/services/db/__tests__/GitFileSystemService.spec.ts
we want to have visibility on our tests on datadog.
1. use dd test visibility action to forward to dd
2. add the action right before the test step as per their docs to avoid interference with the tracers
> chore: add datadog test action

- src/services/db/GitHubService.ts
- src/services/db/__tests__/GitHubService.spec.ts
Uses our admin token to privatise repos, to fix github's changes to disallow write tokens to change repo status.
> fix: use admin token for privatisation

- src/integration/NotificationOnEditHandler.spec.ts
- src/integration/Reviews.spec.ts
- src/services/review/ReviewRequestService.ts
currently, the way our comments work is getting the associated `reviewMeta` via the `pullRequestNumber` then usign that to get the `reviewId`. however, we conflate the `pullRequestNumber` (actual pr number in github) with the `reviewId` given by the user (logical id for our review request, unique across every review, even if pr number is the same)
1. ~use `reviewId` provided by the request to both create and get comments~ -> the `reviewId` provided by the request actually isn't the `reviewId` in our database. this is the **PR number**. because of this, we have to use the `(prNumber, siteName)` tuple to extract the `reviewMeta`!!! i've added a test for this under `GET comments`
2. still preserve getting `reviewMeta` as a check to ensure that the review request exists
> fix: comment logic
